wip W-Y platoon
cmss13-devs/cmss13-pve pull request #136
Opened 2024-03-04 11:03 UTC by bearrrrrrrr

# About the pull request

WIP for W-Y platoon

# Explain why it's good for the game

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

![image](https://github.com/PvE-CMSS13/PvE-CMSS13/assets/54826962/3d94538f-70f5-43a3-9b88-360ed8819425)

</details>

# Changelog

:cl:
add: Added something
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
spellcheck: fixed a few typos
ui: changed something relating to user interfaces
code: changed some code
refactor: refactored some code
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
mapadd: added a new map or section to a map
maptweak: tweaked a map
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2024-03-04 19:27 UTC, morrowwolf commented
Hit "ready for review" when you're ready for review

2024-03-09 23:56 UTC, AndroBetel requested changes

2024-03-09 23:56 UTC, AndroBetel commented on code/game/jobs/job/marine/squads.dm
> +/datum/squad/pmc/pve
should be a subtype of /datum/squad/marine, see my UPP platoon for example

2024-03-14 02:15 UTC, bearrrrrrrr commented
??????????

2024-03-19 13:22 UTC, KoishiVibe commented
are ya winnin fren?

2024-04-26 16:37 UTC, AndroBetel commented on code/modules/gear_presets/pmc_pve.dm
> +/datum/equipment_preset/uscm/pmc/load_name(mob/living/carbon/human/new_human, randomise)
this is fucked up. but it's cool. but it's still fucked up.

If anything - i dont mind removing it and using it as OOC guide for PMC names

2024-04-26 17:48 UTC, AndroBetel approved these changes
*approving myself, woah*

2024-04-30 01:44 UTC, DexterDude requested changes
Map review time!!!

This is just an initial review, going to do a deeper check in a few when I have more free time.

- I think the singularity part of the map being present is weird. Generally shipmaps try to imply that the ship is much larger than the map actually is. Singularity being present in a hangar bay is a bit odd.
-  should have vendors for coffee/cigarettes for rp
- hangar is too cramped, it needs a bit more space to allow for a large vehicle to get around the hangar bay and enter through the back without having to drive over the landing pad, just in case GMs decide to use a larger dropship.
- Map has no real cargo area for incoming equipment and also has no launch pad & computer

![reviewspot1](https://github.com/PvE-CMSS13/PvE-CMSS13/assets/25943228/db425879-f7cc-434c-a5aa-1865b0640287)

![reviewspot2](https://github.com/PvE-CMSS13/PvE-CMSS13/assets/25943228/aebbfbe7-19e8-4c23-829b-2c88da949714)

![reviewspot3](https://github.com/PvE-CMSS13/PvE-CMSS13/assets/25943228/587d865b-f544-4891-a82d-03b9c739b6ab)

![reviewspot4](https://github.com/PvE-CMSS13/PvE-CMSS13/assets/25943228/4ba76fd7-0ca8-4dd6-9cee-da487107c6d8)

![reviewspot5](https://github.com/PvE-CMSS13/PvE-CMSS13/assets/25943228/61f84402-d831-4f22-a71f-52e1d2a0a5e4)

![reviewspot6](https://github.com/PvE-CMSS13/PvE-CMSS13/assets/25943228/8e3ff588-3568-4f74-b735-2e1d47b641c0)

if you disagree with any of this (like if you believe certain things are intentional) do let me know

2024-04-30 01:48 UTC, DexterDude commented
forgot to mention, but this podlock south-east in the hangar is also un-named, should be named hangar lockdown or something similar

![hangardoors](https://github.com/PvE-CMSS13/PvE-CMSS13/assets/25943228/a59fdbf6-5cb6-4e19-beb6-9bb5f9980d88)

2024-05-01 00:45 UTC, AndroBetel commented
map review changes done

2024-05-06 00:24 UTC, DexterDude commented
Still need to do an in depth review, but you did miss the area around the W-Y logo in the canteen. It needs the rounded corners.

2024-07-18 18:48 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-07-27 21:46 UTC, Doubleumc requested changes
Change dropship name to something other than "Orphan Stomper". Too goofy. Suggestions: "Problem Solver", "Guns For Hire", "Peacemaker", "Breadwinner", "Cash Flow" -- anything you could put on a financial report and not get yelled at by the director.

Other than that, looks good to me.

2024-07-31 06:21 UTC, KoishiVibe commented
> Change dropship name to something other than "Orphan Stomper". Too goofy. Suggestions: "Problem Solver", "Guns For Hire", "Peacemaker", "Breadwinner", "Cash Flow" -- anything you could put on a financial report and not get yelled at by the director.
> 
> Other than that, looks good to me.

Probably could also toss some edge in there. Reaper's Stockbroker, whatever.

2024-08-05 05:48 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-08-15 05:27 UTC, Doubleumc commented
Feel free to reopen when the issues have been addressed.

2024-12-01 14:39 UTC, closed without merging