Remote Outpost Gamemode + New Map + GM Tools
cmss13-devs/cmss13-pve pull request #180
Opened 2024-03-25 04:51 UTC by FslashN

DO NOT TM THIS LIVE WITHOUT ME

There are a lot of changes in this one, way more than I would have liked, and I really need to double down on the details. If you want to run this, let me know so I can observe.

Introduces a new mode, the Remote Outpost. It's a ground type game mode, similar to Distress Signal (Lowpow), but it has two custom platoons instead of one.
Introduces a new faction, the USCM Ground forces, or Outpost, who are really part of the USCM and are only their own faction in terms of code. I did a bunch of refactoring to make this happen, as the faction code wasn't quite as nimble as I would have liked.

New map, Blackstone Bridge (or Ridge, I may change my mind later), an unfinished highway and bridge through a mountain tunnel, with a nearby USCM outpost. The outpost was constructed on top of an older colony mining site due to the threat of CLF activity in the area. The planet isn't defined, you can use it for a variety of missions and scenarios as I will detail later. Come up with your own narrative. But the basic idea is that the minerals dried up very quickly and a shanty town that was build around a nearby mining site was torn down; the USCM outpost was constructed on its remains, which is really just a collection of underground maintenance tunnels.

The map is broken up in to several sections, which I won't detail here, but it offers a lot of different ways to entertain the players. There is a cave system, underground tunnels, points of interests, and so on.

There is a lot of refactoring done in a lot of different places. Hopefully things work, as the changes are mostly back-end. I did introduce some new graphics and sounds, but they are all fairly minor.

Big new features: Map Manipulation GM menu. It's visible under GM stuff and allows you to do three mains things.
Destroy maps in seconds, with tailored degrees of destruction. Much faster and better looking than using bombs.
Tweak and toggle specific map setting. For now it only works with Blackstone Bridge, as that is the only map that supports it.
Fully manipulate the Nightmare Generator system in the lobby, including changing scenario settings as you want, and to fire it before round start. Full access means there are a lot of possibilities now open.

The Map Manipulation menu probably took about as much time as the map itself, probably more.

There are also some experimental vehicle changes that I am still debugging. Prevents everything but tanks from going up/down stairs and through deep water. There is also some code to prevent weird platform behavior, but for now it doesn't quite work the way I want to.

Should be the short of it. I'll add more if I need to.

2024-03-30 07:03 UTC, KoishiVibe commented
horrible opinions:
- Replace Gauss Turrets with regular, special locked turrets? Kinda sad seeing them barely do shit. 
- Need more disposal bins around. Gotta be able to tidy up. 
- Maybe add a clipboard with a list of to-do items, as a quick nudge in the right direction, in the medical bay?
- Add a book on making medicines near the chem machine incase the operator is big stupid (me)
- look into adding barbed wire equipped MG nests, there were problems of xenos climbing right over them apparently
- more dedicated support personnel to operate the thingies? I beg....

but this is first run, so things will probably get better later.

2024-03-30 20:45 UTC, FslashN commented
> In the sickbay, there's sleepers with body scanner consoles, so as a result, they don't work for either purpose.

Mapping errors, fixed.

2024-03-31 05:31 UTC, FslashN commented
> horrible opinions:
> 
>     * Replace Gauss Turrets with regular, special locked turrets? Kinda sad seeing them barely do shit.
> 
>     * Need more disposal bins around. Gotta be able to tidy up.
> 
>     * Maybe add a clipboard with a list of to-do items, as a quick nudge in the right direction, in the medical bay?
> 
>     * Add a book on making medicines near the chem machine incase the operator is big stupid (me)
> 
>     * look into adding barbed wire equipped MG nests, there were problems of xenos climbing right over them apparently
> 
>     * more dedicated support personnel to operate the thingies? I beg....
> 
> 
> but this is first run, so things will probably get better later.

I will likely remove most of the turrets on the map as I like the idea of marines doing most of the shooting. But I will keep a few and probably make them stronger. I'll look into disposal bins. There are quite a few around, but I can try to squeeze some more in. To-do items probably won't happen as I don't want to nudge the players in any particular direction. If someone is lost, a GM is always on hand to help out.

MG wired nests I'll need to observe more. More non-combat personnel is iffy. I have mixed feeling on introducing any more roles that don't have any specific objectives, as that just means more people or GMs to manage. There are the civies of you want to RP, as everyone else is pretty much set on what they need to do. But nothing is out of the question. I do want to focus on the roles we have and see if I can make some of them even better.

Thanks for the feedback!

2024-04-01 03:46 UTC, XSlayer300 commented
The APC cannot really fit into the LZ, if it has been deployed via dropship. The Dropship must leave before going to the entrance of the tunnels leading to the base itself.

2024-04-01 09:48 UTC, FslashN commented
> The APC cannot really fit into the LZ, if it has been deployed via dropship. The Dropship must leave before going to the entrance of the tunnels leading to the base itself.

That is a bit of a problem, but luckily a pretty easy thing to adjust.

2024-04-01 16:50 UTC, morrowwolf requested changes

2024-04-01 16:50 UTC, morrowwolf commented on code/__DEFINES/skills.dm
> +#define SKILL_UNSKILLED 0
Each skill should have its own define for 0 so as to easily jump to the defines if they want to change it.

2024-04-01 16:50 UTC, morrowwolf commented on code/__DEFINES/vendors.dm
> +//If the vendor has some specialized behavior that needs to override other behavior. Crutch, best to refactor appropriate code.
*stare

2024-04-01 16:50 UTC, morrowwolf commented on code/__DEFINES/xeno.dm
> +#define XENO_HITS_TO_DESTROY_WELDED_DOOR 20
Sort of adjacent changes that should be atomized into their own PRs but I suppose it's fine.

2024-04-01 16:50 UTC, morrowwolf commented on code/datums/factions/faction.dm
> +//Overwrite this if the check needs to account for something special, like sub-factions. uscm.dm for an example.
For comments like this you want to use /// so it can get picked up by the automatic documentation stuff.

2024-04-01 16:50 UTC, morrowwolf commented on code/datums/factions/uscm.dm
> +	switch(faction_to_check)
This feels like it should just be subtypes. Utilize OOP where possible. Secondly, this feels like it could be a variable.

2024-04-01 16:50 UTC, morrowwolf commented on code/game/gamemodes/game_mode.dm
> +	RegisterSignal(SSdcs, COMSIG_GLOB_XENO_SPAWN, PROC_REF(handle_xeno_spawn))
Should be a flag, we don't want this on every gamemode.

2024-04-01 16:50 UTC, morrowwolf commented on code/game/gamemodes/game_mode.dm
> +/datum/game_mode/proc/handle_xeno_spawn(datum/source, mob/living/carbon/xenomorph/spawning_xeno, ai_hard_off = FALSE)
Same as above

2024-04-01 16:50 UTC, morrowwolf commented on code/game/jobs/job/command/cic/captain.dm
> +		if(JOB_USCM_GROUND_CO)
Should probably be a subtype

2024-04-01 16:50 UTC, morrowwolf commented on code/game/jobs/job/command/cic/executive.dm
> +		if(JOB_USCM_GROUND_AO)
Subtype

2024-04-01 16:50 UTC, morrowwolf commented on code/game/jobs/job/marine/squad/leader.dm
> +/obj/effect/landmark/start/marine/leader/uscm_ground/two
I know it's dumb but it should like be /one and /two and the base would be abstract

2024-04-01 16:50 UTC, morrowwolf commented on code/game/jobs/job/marine/squad/leader.dm
> +/obj/effect/landmark/start/marine/leader/uscm_ground/two
Will continue from here when I get more time. Gotta check other PRs.

2024-04-01 16:50 UTC, morrowwolf commented
Round uno of review.

2024-04-02 17:38 UTC, FslashN commented on code/__DEFINES/skills.dm
> +#define SKILL_UNSKILLED 0
They do have their own defines for 0, which is the _DEFAULT. Since you changed some of them to actual numbers but not others, I had to manually override the skills. _UNSKILLED means they don't have the skill. I don't really see problem with this as the define is contained next to the other skill defines.

2024-04-02 17:38 UTC, FslashN commented on code/__DEFINES/vendors.dm
> +//If the vendor has some specialized behavior that needs to override other behavior. Crutch, best to refactor appropriate code.
Pay no attention to the man behind the curtain...

2024-04-02 17:42 UTC, FslashN commented on code/__DEFINES/xeno.dm
> +#define XENO_HITS_TO_DESTROY_WELDED_DOOR 20
No argument there.

2024-04-02 17:42 UTC, FslashN commented on code/datums/factions/faction.dm
> +//Overwrite this if the check needs to account for something special, like sub-factions. uscm.dm for an example.
I'll keep that in mind.

2024-04-02 17:46 UTC, FslashN commented on code/datums/factions/uscm.dm
> +	switch(faction_to_check)
There is a specific reason for this. Some factions are subfactions of the parents and have most of their functions rolled in with the parent, but some specific cases require dynamic list checking for which we need a proc. Check the code for USCM and how it returns region access. It would not be entirely necessary if each subfaction had its defined faction type, but it's fine for now.

2024-04-02 17:49 UTC, FslashN commented on code/game/gamemodes/game_mode.dm
> +	RegisterSignal(SSdcs, COMSIG_GLOB_XENO_SPAWN, PROC_REF(handle_xeno_spawn))
Wouldn't hurt, sure. I'll look into it.

2024-04-02 17:52 UTC, FslashN commented on code/game/jobs/job/command/cic/captain.dm
> +		if(JOB_USCM_GROUND_CO)
`generate_entry_message()` calls to parent, which I believe calls for more text to generate. OCO is already a subtype of CO, so I would need to override the message somehow and call to parent. Let me know if you have some ideas.

2024-04-02 17:53 UTC, FslashN commented on code/game/jobs/job/command/cic/executive.dm
> +		if(JOB_USCM_GROUND_AO)
Same here.

2024-04-02 17:56 UTC, FslashN commented on code/game/jobs/job/marine/squad/leader.dm
> +/obj/effect/landmark/start/marine/leader/uscm_ground/two
It's generally how it's handled. I'll change this one.

2024-04-05 18:11 UTC, FslashN commented on code/modules/gear_presets/uscm_ground.dm
> +	assignment = initial(assignment) + "- [spec]"
Dang, wish I saw this before pushing changes. Definitely, thanks.

2024-04-06 04:46 UTC, TopHatPenguin commented
The colony synthetic sets off the motion detectors.

2024-04-06 20:23 UTC, FslashN commented
> The colony synthetic sets off the motion detectors.

Fixed it, thanks.

2024-04-13 04:53 UTC, DexterDude commented
Soldiers don't appear in the ambush menu.

2024-05-01 06:22 UTC, Drulikar requested changes
In the future I recommend atomizing as much as possible, this is just a behemoth of a PR to review.

Also next time before doing a massive refactor, please read https://github.com/PvE-CMSS13/PvE-CMSS13/tree/master/.github/guides

Once this is at a point its not drafted I can see about reviewing the functionality.

2024-05-01 06:22 UTC, Drulikar commented on code/modules/gear_presets/uscm_ship.dm
> +	skills = /datum/skills/AO
Whats the point of keeping the old skills for `datum/skills/auxiliary_officer` around then?

2024-05-01 06:22 UTC, Drulikar commented on code/modules/mob/living/carbon/human/human.dm
> +	/// Modify them in the datacore, if they are on it. Rip.
`///` is for autodoc

2024-05-01 06:22 UTC, Drulikar commented on code/modules/mob/living/carbon/human/human.dm
> +	/// Some information should only be available to those who are added to the manifest.
`///` is for autodoc

2024-05-01 06:22 UTC, Drulikar commented on code/modules/mob/living/carbon/human/human.dm
> +	if(job in GET_MANIFEST_ROLES) ///This will prevent mobs that are not part of round start/added manually from viewing the manifest.
`///` is for autodoc

2024-05-01 06:22 UTC, Drulikar commented on code/modules/mob/living/living.dm
> +		if((mob_size * L.mob_size) - abs(mob_size - L.mob_size) < 0) /// One of the mobs is small, but not both.
`///` is for autodoc

2024-05-01 06:22 UTC, Drulikar commented on code/modules/mob/living/living.dm
> +		else /// Our mobs are both small or both are not small.
`///` is for autodoc

2024-05-01 06:22 UTC, Drulikar commented on code/modules/mob/living/living_defense.dm
> +		/// MOB_COVERED_FROM_WEATHER also stops physical effects. This could be remedied by having the tent/cover object take damage from harmful weather effects.
`///` is for autodoc

2024-05-01 06:22 UTC, Drulikar commented on code/modules/mob/living/living_health_procs.dm
> +		GLOB.data_core.manifest_modify(H.real_name, WEAKREF(H), null, null, H.species.manifest_alive) ///To properly bring people back from death on the manifest.
`///` is for autodoc

2024-05-01 06:22 UTC, Drulikar commented on code/modules/mob/new_player/new_player.dm
> +	if(character.job in GET_MANIFEST_ROLES) ///Inject them into the manifest if they are spawning as a role that should be on the manifest/have access to it.
`///` is for autodoc

2024-05-01 06:22 UTC, Drulikar commented on code/modules/mob/new_player/new_player.dm
> +	var/len = 0 /// To autosize the latejoin window.
`///` is for autodoc

2024-05-01 06:22 UTC, Drulikar commented on code/modules/mob/new_player/new_player.dm
> +		if(!(J.category in categories_shown)) ///If it is not found in the list of categories already displayed, display it.
`///` is for autodoc

2024-05-01 06:22 UTC, Drulikar commented on code/modules/movement/launching/launching.dm
> +	if(layer < FLY_LAYER) /// Only swap layers if the atom is on a lower layer.
`///` is for autodoc

2024-05-01 06:22 UTC, Drulikar commented on code/modules/movement/launching/launching.dm
> +		layer = old_layer || layer /// If old_layer isn't null, we will use it, or stick with whatever layer is set.
`///` is for autodoc

2024-05-01 06:22 UTC, Drulikar commented on code/modules/nightmare/nmnodes/scenario.dm
> +		///We want to add to a list of all potential values here.
`///` is for autodoc

2024-05-01 06:22 UTC, Drulikar commented on code/modules/tents/deployed_tents.dm
> +/// Only a single flag for now, so no reason to global define.
This is not a comment worth autodocing

2024-05-01 06:22 UTC, Drulikar commented on code/modules/tents/deployed_tents.dm
> +	if(!entrance_offset) return FALSE
https://github.com/PvE-CMSS13/PvE-CMSS13/blob/master/.github/guides/STYLES.md#control-statements

2024-05-01 06:22 UTC, Drulikar commented on code/modules/tents/deployed_tents.dm
> +	var/L[0]
https://github.com/PvE-CMSS13/PvE-CMSS13/blob/master/.github/guides/STYLES.md#dont-use-abbreviations

2024-05-01 06:22 UTC, Drulikar commented on code/modules/tents/deployed_tents.dm
> +	/// This will prevent weather effects from influencing their screen (also stops physical effects, for the time being).
`///` is for autodoc

2024-05-01 06:22 UTC, Drulikar commented on code/modules/tents/deployed_tents.dm
> +	subject_mob.mob_flags &= ~MOB_COVERED_FROM_WEATHER /// Remove the flag.
`///` is for autodoc

2024-05-01 06:22 UTC, Drulikar commented on code/modules/tents/deployed_tents.dm
> +	if(QDELETED(subject_mob) || (get_turf(subject_mob) in bound_turfs)) return FALSE
https://github.com/PvE-CMSS13/PvE-CMSS13/blob/master/.github/guides/STYLES.md#control-statements

2024-05-01 06:22 UTC, Drulikar commented on code/modules/vehicles/van/van.dm
> +	var/obj/vehicle/multitile/van/V = new (loc)
https://github.com/PvE-CMSS13/PvE-CMSS13/blob/master/.github/guides/STYLES.md#dont-use-abbreviations

2024-05-01 06:22 UTC, Drulikar commented on maps/map_files/golden_arrow/golden_arrow.dmm
See mapdiffbot for the layering issue created.

2024-05-01 14:18 UTC, FslashN commented on maps/map_files/golden_arrow/golden_arrow.dmm
Not seeing it with mapdiff. The only change should be the console replacement. Can you be more specific?

2024-05-01 14:19 UTC, FslashN commented on code/modules/vehicles/van/van.dm
> +	var/obj/vehicle/multitile/van/V = new (loc)
Fixed.

2024-05-01 14:21 UTC, FslashN commented on code/modules/tents/deployed_tents.dm
> +	if(QDELETED(subject_mob) || (get_turf(subject_mob) in bound_turfs)) return FALSE
Fixed.

2024-05-01 14:24 UTC, FslashN commented on code/modules/tents/deployed_tents.dm
> +	var/L[0]
Resolved.

2024-05-01 14:25 UTC, FslashN commented on code/modules/tents/deployed_tents.dm
> +/// Only a single flag for now, so no reason to global define.
Resolved.

2024-05-01 14:25 UTC, FslashN commented on code/modules/tents/deployed_tents.dm
> +	/// This will prevent weather effects from influencing their screen (also stops physical effects, for the time being).
I think this is worth audodocing.

2024-05-01 14:26 UTC, FslashN commented on code/modules/tents/deployed_tents.dm
> +	subject_mob.mob_flags &= ~MOB_COVERED_FROM_WEATHER /// Remove the flag.
Resolved.

2024-05-01 14:31 UTC, FslashN commented on code/__HELPERS/mobs.dm
> +	return new_name && (voice = new_name)
It's faster and is proper syntax. I do not see an isse with this.

2024-05-01 14:31 UTC, FslashN commented on code/__HELPERS/mobs.dm
> +	return mind && new_name && (mind.name = new_name)
It is faster and is proper syntax. I do not see an issue here.

2024-05-01 14:32 UTC, FslashN commented on code/__HELPERS/mobs.dm
> +	if(!new_name) return FALSE
Fixed.

2024-05-01 14:34 UTC, FslashN commented on code/controllers/subsystem/minimap.dm
> +		else return UI_CLOSE
Resolved.

2024-05-01 14:36 UTC, FslashN commented on code/controllers/subsystem/minimap.dm
> +			//I had to refactor some other code to make this less atrocious. Spawning in a map item to reference one compile-time variable is very silly. Behold!
More could definitely be done here, but I'm probably not going to mess with it more unless I absolutely have to.

2024-05-01 14:37 UTC, FslashN commented on code/controllers/subsystem/minimap.dm
> +	var/use_live_map = is_xeno || skillcheck(user, SKILL_LEADERSHIP, SKILL_LEAD_EXPERT) /// Either a xenomorph or skilled to view the live map.
Resolved.

2024-05-01 14:38 UTC, FslashN commented on code/controllers/subsystem/minimap.dm
> +	var/faction = faction_default || (is_xeno ? xeno.hivenumber : user.faction) /// Fallback is user.faction.
Resolved.

2024-05-01 14:39 UTC, FslashN commented on code/controllers/subsystem/nightmare.dm
> +		if(NIGHTMARE_STATUS_RUNNING) return FALSE
Resolved.

2024-05-01 14:49 UTC, FslashN commented on code/controllers/subsystem/ticker.dm
> +		mode = null
That is a good catch. I probably overlooked it as it should not be qdeled here.

2024-05-01 14:50 UTC, FslashN commented on code/datums/datacore.dm
> +			if(!manifest_out[category]) manifest_out[category] = list()
Resolved.

2024-05-01 14:52 UTC, FslashN commented on code/datums/datacore.dm
> +	var/mob/M //Iterator.
Not sure what this is pointing to. Unless it's for the iterator, which is fine.

2024-05-01 14:58 UTC, FslashN commented on code/datums/datacore.dm
> +				S = i
Didn't know this was an option. Resolved.

2024-05-01 15:00 UTC, FslashN commented on code/datums/datacore.dm
> +		else category = J.category /// If we know their datum, grab the category.
Resolved.

2024-05-01 15:01 UTC, FslashN commented on code/datums/datacore.dm
> +			if(!squad_name) continue ///If they are a combat role but have no squad, we skip them.
Resolved.

2024-05-01 15:03 UTC, FslashN commented on code/datums/datacore.dm
> +		if(!length(category_list)) continue ///Should not have empty lists, but it is possible for squads.
Resolved.

2024-05-01 15:04 UTC, FslashN commented on code/datums/datacore.dm
> +					if(category == general) . = TRUE /// So long as we got rid of the general record, we're good.
Resolved.

2024-05-01 16:11 UTC, FslashN commented on code/game/objects/structures/coathanger.dm
> +		overlay_image.filters += filter(type="alpha", icon=src.icon) /// This applies a basic mask to fake a hanging coat. Kind of crude, may need replacement if the icons change.
Resolved.

2024-05-01 16:11 UTC, FslashN commented on code/game/objects/structures/coathanger.dm
> +	if(!current_suit && istype(movable_atom, /obj/item/clothing/suit/storage)) /// A little safety before we go into a loop of typechecking a bunch of stuff.
Resolved.

2024-05-01 16:11 UTC, FslashN commented on code/game/objects/structures/coathanger.dm
> +/// I don't want to go through CPU cycles in order to typecheck against everything in a tile, so we're just hard-spawning them in.
Resolved.

2024-05-01 16:11 UTC, FslashN commented on code/game/objects/structures/coathanger.dm
> +			if(istype(attacking_object, path)) /// A little expensive, but it's such a niche object.
Resolved.

2024-05-01 16:13 UTC, FslashN commented on code/modules/admin/game_master/extra_buttons/map_manipulation_menu.dm
> +	var/data[0]
It is a shorthand initialization of a list. http://www.byond.com/docs/ref/#/list

2024-05-01 16:13 UTC, FslashN commented on code/modules/admin/game_master/extra_buttons/map_manipulation_menu.dm
> +			if(!isnum(new_percentage)) return FALSE
Resolved.

2024-05-01 16:14 UTC, FslashN commented on code/modules/admin/game_master/extra_buttons/map_manipulation_menu.dm
> +				if(tgui_alert(ui.user, "Are you sure you want to start the Nightmare system before round start? This cannot be undone.", "Confirmation", list("Yes", "No")) != "Yes") return FALSE
Resolved.

2024-05-01 16:14 UTC, FslashN commented on code/modules/admin/game_master/extra_buttons/map_manipulation_menu.dm
> +		else dest_actions = list(action, percentage_to_break) //Everything else falls into here.
Resolved.

2024-05-01 16:15 UTC, FslashN commented on code/modules/admin/game_master/extra_buttons/map_manipulation_menu.dm
> +			if(tgui_alert(ui.user, "Are you sure you want to break stuff? This cannot be undone.", "Confirmation", list("Yes", "No")) != "Yes") return FALSE
Resolved.

2024-05-01 16:18 UTC, FslashN commented on code/modules/admin/game_master/extra_buttons/map_manipulation_menu.dm
> +						qdel(I) //This will remove it from landmarks.
Not sure I agree. In this instance the single letter variable can definitely be redefined, but more generally defining variables before the loop makes it clear which variables are in play.

2024-05-01 16:21 UTC, FslashN commented on code/modules/admin/game_master/extra_buttons/map_manipulation_menu.dm
> +							qdel(I)
Noted.

2024-05-01 16:43 UTC, FslashN commented on code/game/turfs/open.dm
> +				else new /obj/structure/flora/jungle/vines/heavy(src)
Resolved.

2024-05-01 16:45 UTC, FslashN commented on code/modules/cm_marines/equipment/maps.dm
>  		MAP_NEW_VARADERO_REPAIRED = new /obj/item/map/new_varadero(),
You should check who added that line.

2024-05-01 16:46 UTC, FslashN commented on code/modules/cm_marines/equipment/maps.dm
> +	if(!ground_map) return FALSE //If it doesn't find anything in the referenced list, nothing else to do here. Cya.
I don't know if it was intentional or not, but it was not well implemented before.

2024-05-01 16:47 UTC, FslashN commented on code/modules/client/preferences.dm
> +#undef PREF_HEIGHT
I'll look into this. Leaving this open for now.

2024-05-01 16:49 UTC, FslashN commented on code/modules/client/preferences.dm
> +#define PREF_HEIGHT_MIN 290 /// Minimum height, otherwise things look goofy.
This one is actually correct. That is a macro definition.

2024-05-01 16:49 UTC, FslashN commented on code/modules/admin/topic/topic.dm
> +		if(!check_rights(R_ADMIN|R_SERVER)) return FALSE
Resolved.

2024-05-01 16:53 UTC, FslashN commented on code/modules/cm_marines/marines_consoles.dm
> +				if(squad_number >= 130) break //Only the Almayer squads, 70 - 130
Resolved.

2024-05-01 16:59 UTC, FslashN commented on code/modules/cm_marines/marines_consoles.dm
> +			log_idmod(target_id_card, "<font color='green'> [key_name_admin(usr)] granted the ID all access and [faction] IFF. </font>")
Resolved.

2024-05-01 16:59 UTC, FslashN commented on code/modules/cm_marines/marines_consoles.dm
> +			log_idmod(target_id_card, "<font color='red'> [key_name_admin(usr)] removed all accesses and [faction] IFF. </font>")
Resolved.

2024-05-01 16:59 UTC, FslashN commented on code/modules/cm_marines/marines_consoles.dm
> +			if(!region)	return
Resolved.

2024-05-01 17:00 UTC, FslashN commented on code/modules/cm_marines/marines_consoles.dm
> +			if(!region)	return
Resolved.

2024-05-01 17:02 UTC, FslashN commented on code/modules/cm_marines/marines_consoles.dm
> +		var/accesses[0]
Not meant to be an improvement. It's a shorthand way to initialize lists. http://www.byond.com/docs/ref/#/list

2024-05-01 17:02 UTC, FslashN commented on code/modules/cm_marines/marines_consoles.dm
> +	var/localfactions[0]
Not meant to be an improvement. This is a shorthand way to initialize lists. http://www.byond.com/docs/ref/#/list

2024-05-01 17:04 UTC, FslashN commented on code/modules/cm_marines/marines_consoles.dm
Should be resolved.

2024-05-01 17:09 UTC, FslashN commented on code/modules/cm_marines/marines_consoles.dm
> +	var/datum/faction/F = get_faction(faction)
Resolved.

2024-05-01 17:10 UTC, FslashN commented on code/modules/cm_marines/overwatch.dm
> +	var/true_rank /// What we use to determine what their true job rank is.
Resolved.

2024-05-01 17:11 UTC, FslashN commented on code/modules/gear_presets/_select_equipment.dm
> +		closet = i //We don't need to type check.
Resolved.

2024-05-01 17:11 UTC, FslashN commented on code/modules/gear_presets/_select_equipment.dm
> +		if(closet.squad && ( !new_human.assigned_squad || new_human.assigned_squad.name != closet.squad ) ) continue //Expected a specific squad but didn't match.
Resolved.

2024-05-01 17:14 UTC, FslashN commented on code/modules/gear_presets/uscm_ship.dm
> +	skills = /datum/skills/AO
This is a mistake on my part, and a good catch. This should reference the ASO skillset as per normal.

2024-05-01 17:15 UTC, FslashN commented on code/modules/mob/living/carbon/human/human.dm
> +	if(job in GET_MANIFEST_ROLES) ///This will prevent mobs that are not part of round start/added manually from viewing the manifest.
Resolved.

2024-05-01 17:16 UTC, FslashN commented on code/modules/mob/living/carbon/human/human.dm
> +	/// Some information should only be available to those who are added to the manifest.
Resolved.

2024-05-01 17:16 UTC, FslashN commented on code/modules/mob/living/carbon/human/human.dm
> +	/// Modify them in the datacore, if they are on it. Rip.
Resolved.

2024-05-01 17:17 UTC, FslashN commented on code/modules/mob/living/living.dm
> +		if((mob_size * L.mob_size) - abs(mob_size - L.mob_size) < 0) /// One of the mobs is small, but not both.
Resolved.

2024-05-01 17:17 UTC, FslashN commented on code/modules/mob/living/living.dm
> +		else /// Our mobs are both small or both are not small.
Resolved.

2024-05-01 17:19 UTC, FslashN commented on code/modules/mob/living/living_defense.dm
> +		/// MOB_COVERED_FROM_WEATHER also stops physical effects. This could be remedied by having the tent/cover object take damage from harmful weather effects.
Resolved.

2024-05-01 17:19 UTC, FslashN commented on code/modules/mob/living/living_health_procs.dm
> +		GLOB.data_core.manifest_modify(H.real_name, WEAKREF(H), null, null, H.species.manifest_alive) ///To properly bring people back from death on the manifest.
Resolved.

2024-05-01 17:19 UTC, FslashN commented on code/modules/mob/new_player/new_player.dm
> +	var/len = 0 /// To autosize the latejoin window.
Resolved.

2024-05-01 17:19 UTC, FslashN commented on code/modules/mob/new_player/new_player.dm
> +		if(!(J.category in categories_shown)) ///If it is not found in the list of categories already displayed, display it.
Resolved.

2024-05-01 17:20 UTC, FslashN commented on code/modules/mob/new_player/new_player.dm
> +	if(character.job in GET_MANIFEST_ROLES) ///Inject them into the manifest if they are spawning as a role that should be on the manifest/have access to it.
Resolved.

2024-05-01 17:20 UTC, FslashN commented on code/modules/movement/launching/launching.dm
> +		layer = old_layer || layer /// If old_layer isn't null, we will use it, or stick with whatever layer is set.
Resolved.

2024-05-01 17:20 UTC, FslashN commented on code/modules/movement/launching/launching.dm
> +	if(layer < FLY_LAYER) /// Only swap layers if the atom is on a lower layer.
Resolved.

2024-05-01 17:21 UTC, FslashN commented on code/modules/nightmare/nmnodes/scenario.dm
> +		///We want to add to a list of all potential values here.
Resolved.

2024-05-01 17:35 UTC, FslashN commented on code/game/turfs/turf.dm
> +			return FALSE
Not the case. /obj/vehicle/multitile/Collide(atom/A) > /turf/open/gm/river/handle_vehicle_bump(obj/vehicle/multitile/V)
I specifically made this change to address moving through deep water turfs because Blackstone has a lot of water areas and a starting van. But this may be something I revert and develop more in its PR. For now I'd like to keep it here.

2024-05-01 17:38 UTC, FslashN commented on code/game/objects/structures/gun_rack.dm
> +	. = ..()
I don't necessarily disagree, but this seems inconsistent with how it is usually handled. Resolved.

2024-05-01 17:38 UTC, FslashN commented on code/game/objects/structures/gun_rack.dm
> +	if(indestructible || !health) return //If it has no health or isn't supposed to be destroyed.
Resolved.

2024-05-01 17:40 UTC, FslashN commented on code/game/objects/structures/gun_rack.dm
> +		if(!number_to_remove--) break
Resolved.

2024-05-01 17:46 UTC, FslashN commented on code/game/objects/structures/gun_rack.dm
> +		I.pixel_y = pixel_y
Good points. Changed to reflect the comments made. Resolved.

2024-05-01 17:53 UTC, FslashN commented on code/game/objects/structures/crates_lockers/closets/coffin.dm
> +	/// Our possible options.
Resolved.

2024-05-01 17:53 UTC, FslashN commented on code/game/objects/structures/crates_lockers/closets/coffin.dm
> +	/// Can only have one of these per crate, no more.
Resolved.

2024-05-01 17:53 UTC, FslashN commented on code/game/objects/structures/crates_lockers/closets/coffin.dm
> +				/// Slugs and flechette ammo. 100 rounds, for the B18 spec.
Resolved.

2024-05-01 17:55 UTC, FslashN commented on code/game/objects/structures/crates_lockers/closets.dm
> +		I.pixel_x = wall_mounted ? 0 : pixel_x ///No offset if it's dumping from a wall. Otherwise items become offset weirdly.
Resolved.

2024-05-01 17:55 UTC, FslashN commented on code/game/objects/structures/ladders.dm
> +	if(!unlock_hatch(trigger_signal)) lock_hatch(trigger_signal) //If it doesn't match the first one, we will do the second.
Resolved.

2024-05-01 17:55 UTC, FslashN commented on code/game/objects/structures/ladders.dm
> +	if(state < LADDER_OPEN) return //Can't drop anything if it's closed. Maybe this will change if grate hatches are added.
Resolved.

2024-05-01 17:56 UTC, FslashN commented on code/game/objects/structures/ladders.dm
> +	if(state < LADDER_OPEN) return //Can't look through a closed hatch.
Resolved.

2024-05-01 17:56 UTC, FslashN commented on code/game/objects/structures/ladders.dm
> +	if(open_hatch(user)) return //If it's closed and unlocked, we need to first pop it open, then we can climb in.
Resolved.

2024-05-01 18:00 UTC, FslashN commented on code/game/objects/structures/ladders.dm
> +	icon_state = "ladder[up? TRUE : FALSE][down? TRUE : FALSE]" //TRUE and FALSE are just 1 and 0.
This doesn't actually matter. The correct way to write it is: "ladder[up][down]". Resolved.

2024-05-01 18:02 UTC, FslashN commented on code/game/objects/structures/ladders.dm
> +							I.update_icon()
Resolved.

2024-05-01 18:16 UTC, FslashN commented on code/game/objects/structures/blocker.dm
> +//Makes it block movement or hides it instead.
Resolved.

2024-05-01 18:17 UTC, FslashN commented on code/game/objects/structures/barricade/sandbags.dm
> +	. = ..(loc, user)
Don't disagree. But isn't this inconsistent with how it is usually handled? Resolved.

2024-05-01 18:18 UTC, FslashN commented on code/game/objects/structures/barricade/misc.dm
> +	. = ..(loc, user)
I don't disagree, but this seems inconsistent with how it is usually handled.

2024-05-01 18:20 UTC, FslashN commented on code/game/objects/effects/spiders.dm
> +	desc = "A dead spiderling, still gooey." /// They previously turned into cacoons when killed, for some reason.
Resolved.

2024-05-01 18:21 UTC, FslashN commented on code/game/machinery/doors/airlock.dm
> +		if(prob(55)) cut(AIRLOCK_WIRE_DOOR_BOLTS)
Resolved.

2024-05-01 20:15 UTC, FslashN commented on code/game/objects/structures/ladders.dm
> +	icon_state = "ladder[up? TRUE : FALSE][down? TRUE : FALSE]" //TRUE and FALSE are just 1 and 0.
Probably correct to go with actual numbers then. Resolved.

2024-05-01 20:20 UTC, FslashN commented on code/modules/admin/player_panel/actions/physical.dm
> +			if(H.job == JOB_SQUAD_SPECIALIST) /// Don't care about the squad map here, as this only applies to USCM specialists.
Resolved.

2024-05-01 20:21 UTC, FslashN commented on code/game/objects/structures/tables_racks.dm
> +		layer = ABOVE_MOB_LAYER /// Now consistent with barricades.
Resolved.

2024-05-01 20:22 UTC, FslashN commented on code/game/objects/structures/tables_racks.dm
> +		layer = ABOVE_MOB_LAYER /// Now consistent with barricades.
Resolved.

2024-05-01 20:22 UTC, FslashN commented on code/game/objects/structures/stool_bed_chair_nest/chairs.dm
>  	if(src.dir == NORTH)
Resolved.

2024-05-01 20:23 UTC, FslashN commented on code/game/objects/structures/platforms.dm
> +			layer = PLATFORM_LAYER /// Fixed the climbing animation problem to some degree, but still looks very strange under some circumstances.
Resolved.

2024-05-01 20:24 UTC, FslashN commented on code/game/objects/structures/platforms.dm
> +
Need to come back to this at some point, leaving this open.

2024-05-01 20:25 UTC, FslashN commented on code/game/jobs/role_authority.dm
> +					if(!lowest || current_squad.num_riflemen < lowest.num_riflemen) lowest = current_squad
Resolved.

2024-05-01 20:25 UTC, FslashN commented on code/game/jobs/role_authority.dm
> +					if(!skip_limit && current_job.total_positions >= 0 && current_squad.max_riflemen >= 0 && current_squad.num_riflemen >= current_squad.max_riflemen) continue
Resolved.

2024-05-01 20:26 UTC, FslashN commented on code/game/jobs/role_authority.dm
> +					if(!lowest) lowest = current_squad
Resolved.

2024-05-01 20:26 UTC, FslashN commented on code/game/jobs/role_authority.dm
> +					if(!lowest || current_squad.num_smartgun < lowest.num_smartgun) lowest = current_squad
Resolved.

2024-05-01 20:26 UTC, FslashN commented on code/game/jobs/role_authority.dm
> +					if(!skip_limit && current_squad.num_smartgun >= current_squad.max_smartgun) continue
Resolved.

2024-05-01 20:26 UTC, FslashN commented on code/game/jobs/role_authority.dm
> +					if(!skip_limit && current_squad.num_tl >= current_squad.max_tl) continue
Resolved.

2024-05-01 20:27 UTC, FslashN commented on code/game/jobs/role_authority.dm
> +					if(!skip_limit && current_squad.num_specialists >= current_squad.max_specialists) continue
Resolved.

2024-05-01 20:27 UTC, FslashN commented on code/game/jobs/role_authority.dm
> +					if(!lowest || current_squad.num_leaders < lowest.num_leaders) lowest = current_squad
Resolved.

2024-05-01 20:27 UTC, FslashN commented on code/game/jobs/role_authority.dm
> +					if(!skip_limit && current_squad.num_leaders >= current_squad.max_leaders) continue
Resolved.

2024-05-01 20:27 UTC, FslashN commented on code/game/jobs/role_authority.dm
> +					if(!lowest || current_squad.num_medics < lowest.num_medics) lowest = current_squad
Resolved.

2024-05-01 20:27 UTC, FslashN commented on code/game/jobs/role_authority.dm
> +					if(!skip_limit && current_squad.num_medics >= current_squad.max_medics) continue
Resolved.

2024-05-01 20:28 UTC, FslashN commented on code/game/jobs/role_authority.dm
> +					if(!lowest || current_squad.num_engineers < lowest.num_engineers) lowest = current_squad
Resolved.

2024-05-01 20:28 UTC, FslashN commented on code/game/jobs/role_authority.dm
> +					if(!skip_limit && current_squad.num_engineers >= current_squad.max_engineers) continue
Resolved.

2024-05-01 20:29 UTC, FslashN commented on code/game/gamemodes/colonialmarines/ai/colonialmarines_ai.dm
> +		else return ROLES_AI /// The default option, in case we need to reference it.
Resolved.

2024-05-01 20:30 UTC, FslashN commented on code/datums/mob_hud.dm
> +	if(F.faction_tag == faction_to_check || isobserver(user) || isyautja(user)) //The faction should match the one we referenced.
Resolved.

2024-05-01 20:31 UTC, FslashN commented on code/datums/factions/uscm.dm
> +		if(FACTION_USCM_GROUND) return DEPARTMENT_USCM_GROUND_ALL
Resolved.

2024-05-01 20:32 UTC, FslashN commented on code/datums/factions/pmc.dm
> +		if(FACTION_WY) return DEPARTMENT_WY_PMC_ALL
Resolved.

2024-05-01 20:32 UTC, FslashN commented on code/datums/factions/helpers.dm
>  	for(var/T in typesof(/datum/faction))
Resolved.

2024-05-01 20:34 UTC, FslashN commented on code/datums/factions/faction.dm
> +/*
Resolved.

2024-05-01 20:35 UTC, FslashN commented on code/datums/emergency_calls/whiskey_outpost.dm
> +	if(J) RoleAuthority.randomize_squad(mob, J)
Resolved.

2024-05-01 20:36 UTC, FslashN commented on code/datums/datacore.dm
> +		if(existing_record.fields["ref"] == weak_ref) return FALSE //Already have a record for this human. Abort.
Resolved.

2024-05-01 20:37 UTC, FslashN commented on code/datums/datacore.dm
> +		existing_record = i
Resolved.

2024-05-01 20:38 UTC, FslashN commented on code/datums/datacore.dm
> +				if(faction) current_record.fields["mob_faction"] = faction
Resolved.

2024-05-01 20:39 UTC, FslashN commented on code/datums/datacore.dm
> +			current_record = i
Resolved.

2024-05-01 20:39 UTC, FslashN commented on code/datums/datacore.dm
> +				if(faction) current_record.fields["mob_faction"] = faction
Resolved.

2024-05-01 20:39 UTC, FslashN commented on code/datums/datacore.dm
> +			current_record = i
Resolved.

2024-05-01 21:24 UTC, FslashN commented on code/__DEFINES/mode.dm
> +var/global/list/ROLES_USCM_GROUND = list(JOB_USCM_GROUND_CO, JOB_USCM_GROUND_AO, JOB_USCM_GROUND_SYNTH, JOB_USCM_GROUND_SQUAD_LEADER, JOB_USCM_GROUND_SQUAD_TEAM_LEADER, JOB_USCM_GROUND_SQUAD_MEDIC, J
Not sure what you mean. That is not a list of lists. Leaving open to determine whether or not this list is necessary.

2024-05-01 21:29 UTC, FslashN commented on code/__DEFINES/__game.dm
> +#define PATH_TO_GROUND_MAP_OBJ GLOB.map_type_list[SSmapping.configs[GROUND_MAP].map_name]
It is used in three instances across three different files. It is easier to find and change this way.

2024-05-01 21:32 UTC, FslashN commented on code/__DEFINES/math_physics.dm
> +#define MELTPOINT_DAMAGE_CONVERT(x) ((x*21)+(rand(-150,150))) //Trying to convert some flat numbers into a temperature limit; loosey goosey.
I prefer macro defines to be in all caps since it makes it easier to search for them knowing they are not a regular proc.

2024-05-01 21:33 UTC, FslashN commented on code/controllers/subsystem/minimap.dm
> +			data["canDraw"] = skillcheck(user, SKILL_LEADERSHIP, SKILL_LEAD_EXPERT) /// Should not be able to draw without leadership.
Resolved.

2024-05-01 21:34 UTC, FslashN commented on code/datums/datacore.dm
> +			if(!name || !rank) continue
Resolved.

2024-05-01 21:34 UTC, FslashN commented on code/datums/datacore.dm
> +	var/datum/job/J ///Referenced through their mob job to pull up where their role is sorted.
Resolved.

2024-05-01 21:36 UTC, FslashN commented on code/datums/datacore.dm
> +		if(!name || !rank || !real_rank) ///If something is missing, we ignore them.
Resolved.

2024-05-01 21:37 UTC, FslashN commented on code/datums/datacore.dm
> +		if(OOC) ///This returns a more accurate estimate of whether or not they are active.
Resolved.

2024-05-01 22:46 UTC, FslashN commented on code/datums/factions/faction.dm
> +//Overwrite this if the check needs to account for something special, like sub-factions. uscm.dm for an example.
Let's not jump to assumptions.

2024-05-01 22:55 UTC, FslashN commented on code/datums/datacore.dm
> +			var/datum/squad_type/S
Resolved.

2024-05-01 23:02 UTC, FslashN commented on code/game/machinery/computer/medical.dm
> +						continue
Resolved.

2024-05-01 23:04 UTC, FslashN commented on code/game/machinery/computer/medical.dm
> +								qdel(E)
Resolved.

2024-05-01 23:06 UTC, FslashN commented on code/game/machinery/computer/skills.dm
> +					continue
Resolved.

2024-05-01 23:06 UTC, FslashN commented on code/game/machinery/computer/skills.dm
> +					qdel(R)
Resolved.

2024-05-01 23:09 UTC, FslashN commented on code/game/machinery/computer/skills.dm
> +								qdel(E)
I really dislike touching these files. This one is resolved though.

2024-05-01 23:14 UTC, FslashN commented on code/game/machinery/computer/skills.dm
> +									dat += "<td>[R.fields["rank"]]</td>"
I only inserted the faction check, the other fields are exactly as they are in the previous version. 
https://github.com/cmss13-devs/cmss13/blob/daf426bc2d77ef846c9c761ac3d3d792a4c9fb1d/code/game/machinery/computer/skills.dm#L73

But I went ahead and changed it.

2024-05-01 23:18 UTC, FslashN commented on code/game/machinery/computer/security.dm
> +						continue
Resolved.

2024-05-01 23:19 UTC, FslashN commented on code/game/machinery/computer/security.dm
> +								qdel(E)
Not really my abbreviations, but I have changed it. Resolved.

2024-05-01 23:21 UTC, FslashN commented on code/game/machinery/computer/security.dm
> +									crimstat = E.fields["criminal"]
Resolved.

2024-05-01 23:26 UTC, FslashN commented on code/_globalvars/bitfields.dm
I'll look into this. Leaving it open.

2024-05-01 23:28 UTC, Drulikar commented on code/__DEFINES/mode.dm
> +var/global/list/ROLES_USCM_GROUND = list(JOB_USCM_GROUND_CO, JOB_USCM_GROUND_AO, JOB_USCM_GROUND_SYNTH, JOB_USCM_GROUND_SQUAD_LEADER, JOB_USCM_GROUND_SQUAD_TEAM_LEADER, JOB_USCM_GROUND_SQUAD_MEDIC, J
Its fine I was looking at the wrong define.

2024-05-01 23:30 UTC, Drulikar commented on code/__DEFINES/__game.dm
> +#define PATH_TO_GROUND_MAP_OBJ GLOB.map_type_list[SSmapping.configs[GROUND_MAP].map_name]
Once made into a global proc it'll likely only be used in one place. And as I said the more suitable one to become a define is `SSmapping.configs[GROUND_MAP].map_name` but that will touch a lot of files - though that hasn't stopped you.

2024-05-01 23:31 UTC, Drulikar commented on code/__DEFINES/math_physics.dm
> +#define MELTPOINT_DAMAGE_CONVERT(x) ((x*21)+(rand(-150,150))) //Trying to convert some flat numbers into a temperature limit; loosey goosey.
At a minimum then you need to autodoc this non-constant behavior then via using `///`

2024-05-01 23:33 UTC, Drulikar commented on code/datums/factions/faction.dm
> +//Overwrite this if the check needs to account for something special, like sub-factions. uscm.dm for an example.
There's no assumption to be made. You marked it resolved, just like you did again when I unresolved it. The fact is this is commented using `//` rather than as an autodoc `///`

2024-05-01 23:35 UTC, Drulikar commented on code/game/machinery/computer/skills.dm
> +									dat += "<td>[R.fields["rank"]]</td>"
Then its likely a bug that should be fixed.

2024-05-01 23:36 UTC, Drulikar commented on code/game/machinery/computer/security.dm
> +								qdel(E)
There's plenty of code that doesn't conform to style, which is exactly why PRs like this that do refactor the code, bring it up to snuff.

2024-05-01 23:38 UTC, Drulikar commented on maps/map_files/golden_arrow/golden_arrow.dmm
![image](https://github.com/PvE-CMSS13/PvE-CMSS13/assets/76988376/176ac5fb-dc0c-48a9-81a3-80c14e365c08)

2024-05-01 23:56 UTC, FslashN commented on maps/map_files/golden_arrow/golden_arrow.dmm
I think this was a case of copy-pasting original values that may have caused the error. Resolved.

2024-05-02 00:38 UTC, Drulikar commented on code/__HELPERS/mobs.dm
> +	return new_name && (voice = new_name)
Its a conditional with side effects though that is not typical.

Like doing `while(something-- > 0)` is a conditional with the side effect of decrementing the iterator, its pretty common and normal to expect. A loop almost always is changing some iterator on each iteration.

But doing assignment inside a conditional like this both is not typical, not intuitive, but it also just looks like a bug. By looking like a bug I mean it looks like you meant to have `return new_name && (voice == new_name)`.

I still recommend refactoring the assignment to be its own line.

2024-05-02 00:43 UTC, Drulikar commented on code/__HELPERS/mobs.dm
> +	return mind && new_name && (mind.name = new_name)
See other comment, but also this does change the behavior where it won't assign the name to Unknown too if the parameter is falsey.

2024-05-02 00:47 UTC, Drulikar commented on code/__HELPERS/mobs.dm
> +	return new_name && (voice = new_name)
See https://en.wikipedia.org/wiki/Side_effect_(computer_science) for more details.

2024-05-02 00:53 UTC, Drulikar commented on code/modules/admin/game_master/extra_buttons/map_manipulation_menu.dm
> +	var/data[0]
I am aware, but all other code does it as var/list If you were forming say a 2d array maybe it'd be clearer to use this syntax. Ultimately it doesn't matter but again just code style where some future coder will be confused by this and why its arbitrarily done differently.

2024-05-02 00:56 UTC, Drulikar commented on code/modules/admin/game_master/extra_buttons/map_manipulation_menu.dm
> +						qdel(I) //This will remove it from landmarks.
So a pitfall of doing it the way you're doing is that you can have variables get set in other sections of the code when they are *intended* to be local variables scoped to only where they are used. Not that they are variables that need to be data stored in a broader scope for something else to use. I do not recommend pre-defining variables with a larger scope for loops when they are intended to only be locally scoped. Keep variables defined before a loop to just variables that need the broader scope.

2024-05-02 01:01 UTC, Drulikar commented on code/modules/cm_marines/equipment/maps.dm
>  		MAP_NEW_VARADERO_REPAIRED = new /obj/item/map/new_varadero(),
??
It was correct at the time it was added: https://github.com/PvE-CMSS13/PvE-CMSS13/pull/201/files#diff-ffdebf8423d290b5e3d5321400c2940dea15e2bcc350d1a708c484ce62b99757R168
![image](https://github.com/PvE-CMSS13/PvE-CMSS13/assets/76988376/0682a100-7173-4e42-a9d5-ae9de88534fe)
But you refactored them to not be new, but missed it.

2024-05-02 01:02 UTC, Drulikar commented on code/modules/cm_marines/equipment/maps.dm
> +	if(!ground_map) return FALSE //If it doesn't find anything in the referenced list, nothing else to do here. Cya.
*I* implemented it, and I am telling you its intentional.

2024-05-02 01:09 UTC, Drulikar commented on code/game/objects/structures/barricade/sandbags.dm
> +	. = ..(loc, user)
Sorry I didn't see the other loop

2024-05-02 05:14 UTC, harryob requested changes

2024-05-02 05:14 UTC, harryob commented on tgui/packages/tgui/interfaces/MapManipulation.js
> +  const decl_name = data.map_name;
```suggestion
  const { map_name } = data;
```

2024-05-02 05:14 UTC, harryob commented on tgui/packages/tgui/interfaces/MapManipulation.js
> +        {decl_name === 'Blackstone Bridge' && <BlackstonePanel />}
```suggestion
      <Section title={map_name}>
        {map_name === 'Blackstone Bridge' && <BlackstonePanel />}
```

2024-05-02 05:14 UTC, harryob commented on tgui/packages/tgui/interfaces/MapManipulation.js
> +import { map } from 'common/collections';
typically you'd still always have these at the top of your file

2024-05-02 05:14 UTC, harryob commented on tgui/packages/tgui/interfaces/MapManipulation.js
> +  const NightmareGroundScenario = data.nightmare_ground_scenario || [];
uppercase in jsx is for components (hence why these variables are syntax highlighted orange here)

```suggestion
  const nightmareGround = data.nightmare_ground || {};
  const nightmareGroundScenario = data.nightmare_ground_scenario || [];
```

2024-05-02 05:14 UTC, harryob commented on tgui/packages/tgui/interfaces/MapManipulation.js
> +                    NightmareGroundScenario[scenario_name] === scenario_value
```suggestion
                    nightmareGroundScenario[scenario_name] === scenario_value
```

2024-05-02 05:14 UTC, harryob commented on tgui/packages/tgui/interfaces/MapManipulation.js
> +      ))(NightmareGround)}
```suggestion
      ))(nightmareGround)}
```

2024-05-02 05:14 UTC, harryob commented on tgui/packages/tgui/interfaces/MapManipulation.js
> +        <Section title={scenario_name} mt={ship_i === 0 ? 0 : -2.5}>
you don't seem to change this variable like you do above, is that intended?

2024-05-02 05:14 UTC, harryob commented on tgui/packages/tgui/interfaces/MapManipulation.js
> +  const NightmareShipScenario = data.nightmare_ship || [];
```suggestion
  const nightmareShip = data.nightmare_ship || {};
  const nightmareShipScenario = data.nightmare_ship || [];
```

2024-05-02 05:14 UTC, harryob commented on tgui/packages/tgui/interfaces/MapManipulation.js
> +                    NightmareShipScenario[scenario_name] === scenario_value
```suggestion
                    nightmareShipScenario[scenario_name] === scenario_value
```

2024-05-02 05:14 UTC, harryob commented on tgui/packages/tgui/interfaces/MapManipulation.js
> +      ))(NightmareShip)}
```suggestion
      ))(nightmareShip)}
```

2024-05-02 05:14 UTC, harryob commented on tgui/packages/tgui/interfaces/MapManipulation.js
> +  const [main_tab, setTab] = useLocalState(context, 'main_tab', data.main_tab);
typically variables within react that we're not importing from dm should be camelCase

2024-05-02 05:19 UTC, harryob requested changes

2024-05-02 05:19 UTC, harryob commented on code/modules/admin/game_master/extra_buttons/map_manipulation_menu.dm
> +			var/signal_area = locate(text2path(params["signal_area"])) // Faster than searching through world. Full pathing.
identical to searching in world, fwiw

https://www.byond.com/docs/ref/#/atom/var/contents

2024-05-02 05:20 UTC, harryob commented on code/modules/admin/game_master/extra_buttons/map_manipulation_menu.dm
> +			var/signal_area = locate(text2path(params["signal_area"])) // Faster than searching through world. Full pathing.
didn't mean to mark this one as requested changes, because it's not necessary that you do. just so you know

2024-05-02 06:08 UTC, Drulikar commented on code/__DEFINES/math_physics.dm
> +#define MELTPOINT_DAMAGE_CONVERT(x) ((x*21)+(rand(-150,150))) //Trying to convert some flat numbers into a temperature limit; loosey goosey.
Its autodoc'd now, just as I said mention that its going to be a value with randomness each time you call it.

The pitfall of this define to me is if you ever do `some_thing > MELTPOINT_DAMAGE_CONVERT(some_value)` for example every time you run this its going to behave different. Sometimes it may be true, sometimes it may be false, its not constant.

Otherwise just the comment as it is right now does not really convey to me what I provide it, and what it gives me back.

2024-05-02 06:15 UTC, Drulikar commented on code/modules/cm_marines/marines_consoles.dm
> +			if(!region)	return
This appears to still be unresolved.

2024-05-02 06:16 UTC, Drulikar commented on code/modules/tents/deployed_tents.dm
> +	var/L[0]
This appears to still be unresolved.

2024-05-02 06:50 UTC, Drulikar requested changes
Don't forget you can do this too rather than manually making changes if the reviewers make suggestions: 
![image](https://github.com/PvE-CMSS13/PvE-CMSS13/assets/76988376/9be3c87d-196a-4a8e-832f-947b4002aaee)

2024-05-02 06:50 UTC, Drulikar commented on code/datums/datacore.dm
> +	var/datum/squad/current_squad
```suggestion
```

2024-05-02 06:50 UTC, Drulikar commented on code/datums/datacore.dm
> +			for(current_squad as anything in RoleAuthority.squads)
```suggestion
			for(var/datum/squad/current_squad as anything in RoleAuthority.squads)
```

2024-05-02 06:50 UTC, Drulikar commented on code/modules/admin/game_master/extra_buttons/map_manipulation_menu.dm
> +						if(prob(70)) area_light_bulb.flicker(rand(5,10))
```suggestion
						if(prob(70))
							area_light_bulb.flicker(rand(5,10))
```

2024-05-02 06:50 UTC, Drulikar commented on code/modules/admin/game_master/extra_buttons/map_manipulation_menu.dm
> +							if(prob(25)) gear_vendor.tip_over()
```suggestion
							if(prob(25))
								gear_vendor.tip_over()
```

2024-05-02 06:50 UTC, Drulikar commented on code/modules/admin/game_master/extra_buttons/map_manipulation_menu.dm
> +							if(prob(25)) regular_vendor.tip_over() //This calls malfunction()
```suggestion
							if(prob(25))
								regular_vendor.tip_over() //This calls malfunction()
```

2024-05-02 06:50 UTC, Drulikar commented on code/modules/admin/game_master/extra_buttons/map_manipulation_menu.dm
> +									if(prob(20)) closed_wall.current_bulletholes = TRUE
```suggestion
									if(prob(20))
										closed_wall.current_bulletholes = TRUE
```

2024-05-02 06:50 UTC, Drulikar commented on code/modules/admin/game_master/extra_buttons/map_manipulation_menu.dm
> +									if(prob(40)) closed_wall.current_bulletholes = TRUE
```suggestion
									if(prob(40))
										closed_wall.current_bulletholes = TRUE
```

2024-05-02 06:50 UTC, Drulikar commented on code/modules/admin/game_master/extra_buttons/map_manipulation_menu.dm
> +									if(enable_bullet_holes) closed_wall.current_bulletholes = TRUE
```suggestion
									if(enable_bullet_holes)
										closed_wall.current_bulletholes = TRUE
```

2024-05-02 06:50 UTC, Drulikar commented on code/modules/admin/game_master/extra_buttons/map_manipulation_menu.dm
> +									if(prob(55)) new /obj/item/pipe(open_floor, null, null, pipe)
```suggestion
									if(prob(55))
										new /obj/item/pipe(open_floor, null, null, pipe)
```

2024-05-02 06:50 UTC, Drulikar commented on code/modules/admin/game_master/extra_buttons/map_manipulation_menu.dm
> +									if(break_pipes) enable_pipe_break = TRUE
```suggestion
									if(break_pipes)
										enable_pipe_break = TRUE
```

2024-05-02 06:50 UTC, Drulikar commented on code/modules/admin/game_master/extra_buttons/map_manipulation_menu.dm
> +									if(prob(50)) enable_pipe_break = TRUE
```suggestion
									if(prob(50))
										enable_pipe_break = TRUE
```

2024-05-02 06:50 UTC, Drulikar commented on code/modules/admin/game_master/extra_buttons/map_manipulation_menu.dm
> +									if(prob(20)) enable_pipe_break = TRUE
```suggestion
									if(prob(20))
										enable_pipe_break = TRUE
```

2024-05-02 06:50 UTC, Drulikar commented on code/modules/admin/game_master/extra_buttons/map_manipulation_menu.dm
> +									if(prob(65)) new /obj/effect/decal/cleanable/dirt(open_floor)
```suggestion
									if(prob(65))
										new /obj/effect/decal/cleanable/dirt(open_floor)
```

2024-05-02 06:50 UTC, Drulikar commented on code/modules/admin/game_master/extra_buttons/map_manipulation_menu.dm
> +									if(prob(35)) new /obj/effect/decal/cleanable/dirt(open_floor)
```suggestion
									if(prob(35))
										new /obj/effect/decal/cleanable/dirt(open_floor)
```

2024-05-02 06:50 UTC, Drulikar commented on code/modules/admin/game_master/extra_buttons/map_manipulation_menu.dm
> +							regular_rack.deconstruct(prob(30) ? TRUE : FALSE) //Smaller chance to have them deconstructed into parts.
```suggestion
							regular_rack.deconstruct(prob(30)) //Smaller chance to have them deconstructed into parts.
```

2024-05-02 06:50 UTC, Drulikar commented on code/modules/admin/game_master/extra_buttons/map_manipulation_menu.dm
> +							if(prob(35) && table.flip(pick(1,2,4,8), FALSE, TRUE))
```suggestion
							if(prob(35) && table.flip(pick(1,2,4,8), skip_straight_check=FALSE, batch_flip=TRUE))
```

2024-05-02 06:50 UTC, Drulikar commented on code/modules/admin/game_master/extra_buttons/map_manipulation_menu.dm
> +									disposal_junction.deconstruct(prob(40) ? TRUE : FALSE)
```suggestion
									disposal_junction.deconstruct(prob(40))
```

2024-05-02 06:50 UTC, Drulikar commented on code/modules/cm_marines/equipment/maps.dm
> +		MAP_NEW_VARADERO_REPAIRED = new /obj/item/map/new_varadero,
```suggestion
		MAP_NEW_VARADERO_REPAIRED = /obj/item/map/new_varadero,
```

2024-05-02 06:50 UTC, Drulikar commented on code/modules/vehicles/van/van.dm
> +	if(vehicle_status == VAN_SPAWN_DAMAGED) load_damage(spawned_van)
```suggestion
	if(vehicle_status == VAN_SPAWN_DAMAGED)
		load_damage(spawned_van)
```

2024-05-02 06:50 UTC, Drulikar commented on code/modules/vehicles/van/van.dm
> +	if(vehicle_name) spawned_van.name = vehicle_name
```suggestion
	if(vehicle_name)
		spawned_van.name = vehicle_name
```

2024-05-02 06:50 UTC, Drulikar commented on code/modules/vehicles/van/van.dm
> +	if(vehicle_status > VAN_SPAWN_NON_FUNCTIONAL) V.add_hardpoint(new /obj/item/hardpoint/locomotion/van_wheels)
```suggestion
	if(vehicle_status > VAN_SPAWN_NON_FUNCTIONAL)
		V.add_hardpoint(new /obj/item/hardpoint/locomotion/van_wheels)
```

2024-05-02 06:59 UTC, FslashN commented on code/__DEFINES/math_physics.dm
> +#define MELTPOINT_DAMAGE_CONVERT(x) ((x*21)+(rand(-150,150))) //Trying to convert some flat numbers into a temperature limit; loosey goosey.
I think I see your point. It behaves more like a regular proc than a generic macro with static return value, since there is variance built in. I can definitely document the behavior more it more if that's what I think you are suggesting.

2024-05-02 07:02 UTC, FslashN commented on code/modules/admin/game_master/extra_buttons/map_manipulation_menu.dm
> +						qdel(I) //This will remove it from landmarks.
That's generally how I view it too, so no argument there; variables shouldn't be defined unless they are needed for that scope. Anything defined in a larger context should be applicable to the larger context, and that's how I generally approach it. Though it is entirely possible there are places where I was inconsistent with this.

2024-05-02 07:05 UTC, FslashN commented on code/modules/cm_marines/equipment/maps.dm
> +	if(!ground_map) return FALSE //If it doesn't find anything in the referenced list, nothing else to do here. Cya.
I am not against notifying that a map is missing, but I am not a fan of causing runtimes to do it. Crash or a message is fine. I'm open to ideas.

2024-05-02 07:07 UTC, FslashN commented on code/modules/admin/game_master/extra_buttons/map_manipulation_menu.dm
> +							if(prob(35) && table.flip(pick(1,2,4,8), FALSE, TRUE))
I'm actually pretty bad about breaking this, but I think this is a good conversation to have. Named arguments have a processing cost, and though they make things more readable, I don't know if it justifies using them everwhere. I think we can discuss this in dev.

2024-05-02 07:16 UTC, FslashN commented on code/__HELPERS/mobs.dm
> +	return new_name && (voice = new_name)
I can change it for clarity, but the assignment is entirely conditional on the first variable being TRUE, which is intentional. I don't know, I think it's elegant and is clearly not a bug if you know what you are looking at.

2024-05-02 07:16 UTC, Drulikar commented on code/modules/cm_marines/equipment/maps.dm
> +	if(!ground_map) return FALSE //If it doesn't find anything in the referenced list, nothing else to do here. Cya.
So when you open a PR or push a commit to it, it runs https://github.com/PvE-CMSS13/PvE-CMSS13/blob/master/.github/workflows/ci_suite.yml
Namely `run_all_tests` which runs: https://github.com/PvE-CMSS13/PvE-CMSS13/blob/master/.github/workflows/run_unit_tests.yml

One of these unit tests is this: https://github.com/PvE-CMSS13/PvE-CMSS13/blob/master/code/modules/unit_tests/check_runtimes.dm

That combined with this unit test: https://github.com/PvE-CMSS13/PvE-CMSS13/blob/master/code/modules/unit_tests/create_and_destroy.dm

Means that for every map, every map object is spawned for create_and_destroy test. When something spawns it calls Initialize. If it runtimes during Initialize, that will throw a runtime. When a runtime is thrown, that will be a failed unit test that check_runtimes will report as a failed check.

For example: https://github.com/PvE-CMSS13/PvE-CMSS13/actions/runs/8841434928/job/24278692291?pr=247#step:7:248

2024-05-02 07:18 UTC, FslashN commented on code/__HELPERS/mobs.dm
> +	return mind && new_name && (mind.name = new_name)
The logic gate is that two things have to be true for assignment to take place, which is intentional, and will return FALSE in case something fails. Is there a condition where this assignment wouldn't work as intended?

2024-05-02 07:22 UTC, Drulikar commented on code/modules/admin/game_master/extra_buttons/map_manipulation_menu.dm
> +							if(prob(35) && table.flip(pick(1,2,4,8), FALSE, TRUE))
Readability trumps what microscopic cost this has. Regardless it is outlined here: https://github.com/PvE-CMSS13/PvE-CMSS13/blob/master/.github/guides/STYLES.md#prefer-named-arguments-when-the-meaning-is-not-obvious

Calling a proc in byond is a giant lookup of strings to even *find* the proc because they're just a giant list of strings that lummox searches through to figure out what code to execute.

2024-05-02 07:26 UTC, FslashN commented on code/modules/cm_marines/equipment/maps.dm
> +	if(!ground_map) return FALSE //If it doesn't find anything in the referenced list, nothing else to do here. Cya.
I remember fixing a missing map issue some months back that was causing runtimes; it either didn't trigger this or was merged regardless.

2024-05-02 07:28 UTC, Drulikar commented on code/__HELPERS/mobs.dm
> +	return mind && new_name && (mind.name = new_name)
The logic is correct. This is a style correction.

2024-05-02 07:30 UTC, Drulikar commented on code/modules/cm_marines/equipment/maps.dm
> +	if(!ground_map) return FALSE //If it doesn't find anything in the referenced list, nothing else to do here. Cya.
You're welcome to explicitly test what the runtime would previously occur for and have that be CRASH("Hey coder, a new map needs a map!") or something; but one way or another I want you to retain the logic that this causes checks to fail. (A CRASH throws a runtime and ends the proc btw w/ call stack).

2024-05-02 07:31 UTC, FslashN commented on code/modules/cm_marines/equipment/maps.dm
> +	if(!ground_map) return FALSE //If it doesn't find anything in the referenced list, nothing else to do here. Cya.
I think git ate my comment. I remember fixing a runtime map issue with a missing map for Ice (v2 I think), that either did not trigger this or was merged regardless. I'll need to look back on what changes I've made for this. I'm really not a fan of instancing objects at runtime to look up a variable.

2024-05-02 07:35 UTC, FslashN commented on code/modules/admin/game_master/extra_buttons/map_manipulation_menu.dm
> +							if(prob(35) && table.flip(pick(1,2,4,8), FALSE, TRUE))
Good points. I think that's compelling enough.

2024-05-02 07:39 UTC, FslashN commented on code/modules/admin/game_master/extra_buttons/map_manipulation_menu.dm
> +			var/signal_area = locate(text2path(params["signal_area"])) // Faster than searching through world. Full pathing.
I did not know that. Welp.

2024-05-02 07:42 UTC, FslashN commented on code/modules/admin/game_master/extra_buttons/map_manipulation_menu.dm
> +			var/signal_area = locate(text2path(params["signal_area"])) // Faster than searching through world. Full pathing.
"Therefore in a large world, it's advisable not to loop through area contents at all." I really need to change it then, since this actually is kind of counter to the intent of doing it this way. Generic world search? I'm not really sure.

2024-05-02 07:48 UTC, harryob commented on code/modules/admin/game_master/extra_buttons/map_manipulation_menu.dm
> +			var/signal_area = locate(text2path(params["signal_area"])) // Faster than searching through world. Full pathing.
> "Therefore in a large world, it's advisable not to loop through area contents at all." I really need to change it then, since this actually is kind of counter to the intent of doing it this way. Generic world search? I'm not really sure.

its not a solved problem on cm, but tg has a subsystem for area contents managed by signals for atoms entering/leaving, iirc. but that does feel like it would add additional overhead regardless

2024-05-02 14:46 UTC, FslashN commented on code/modules/admin/game_master/extra_buttons/map_manipulation_menu.dm
> +									disposal_junction.deconstruct(prob(40) ? TRUE : FALSE)
This is a good catch.

2024-05-02 17:23 UTC, FslashN commented on code/__HELPERS/mobs.dm
> +	return mind && new_name && (mind.name = new_name)
Fair enough. I would like to get a second opinion on this in terms of style.

2024-05-02 18:32 UTC, FslashN commented on code/modules/cm_marines/marines_consoles.dm
> +			if(!region)	return
I think this should be resolved. Inline removed.

2024-05-02 18:34 UTC, FslashN commented on code/__DEFINES/__game.dm
> +#define PATH_TO_GROUND_MAP_OBJ GLOB.map_type_list[SSmapping.configs[GROUND_MAP].map_name]
Based on a convo with harryob, I'm starting to think it may be better to revert my changes and create better integration for map items via json files. Something to come back to.

2024-05-03 00:33 UTC, FslashN commented on code/__DEFINES/job.dm
> +#define DEPARTMENT_WY_PMC_ALL DEPARTMENT_WY_ALL + DEPARTMENT_PMC_ALL
I think sacrificing CPU time here is acceptable, as it runs very infrequently.

2024-05-03 01:59 UTC, FslashN commented on code/__DEFINES/job.dm
> +#define DEPARTMENT_UPP_NONCOMBAT "UPP Diplomatic" = list(JOB_UPP_REPRESENTATIVE)
Re-examining this, these defines do seem unncessary.

2024-05-03 02:00 UTC, FslashN commented on code/__DEFINES/math_physics.dm
> +#define MELTPOINT_DAMAGE_CONVERT(x) ((x*21)+(rand(-150,150))) //Trying to convert some flat numbers into a temperature limit; loosey goosey.
I think there is actually no point in keeping this as a define right now. I am going to integrate it into the only proc that uses it.

2024-05-03 03:21 UTC, FslashN commented on code/__DEFINES/mode.dm
> +#define ROLES_SQUAD_USCM_GROUND list(SQUAD_USCM_GROUND_1, SQUAD_USCM_GROUND_2) ///Referenced in marines_consoles.dm for crew tracking individual squads+members.
I'm of the mind that most of these lists don't need to be global as it appears they only really matter in the job ban system. Which is to say, they sit around in memory and are referenced very infrequently. But yeah, I can make this into a gobal list for consistency.

2024-05-03 04:39 UTC, FslashN commented on code/game/turfs/walls/wall_types.dm
> -
It's standardized object behavior based on flag defines rather than arbitrary return statement. I think this is an improvement.

2024-05-03 05:21 UTC, FslashN commented on code/game/jobs/job/command/cic/executive.dm
> +		if(JOB_USCM_GROUND_AO)
That is not a bad idea.

2024-05-03 05:31 UTC, FslashN commented on tgui/packages/tgui/interfaces/MapManipulation.js
> +        <Section title={scenario_name} mt={ship_i === 0 ? 0 : -2.5}>
I don't think this is intentional. It may be left over from when I was experimenting with getting proper line behavior, and I forgot to remove it.

2024-05-03 06:22 UTC, Drulikar requested changes

2024-05-03 06:22 UTC, Drulikar commented on code/__DEFINES/mode.dm
> +#define MODE_XENO_AI (1<<17) ///Allows for alien AI to be used in the game mode.
All these comments for these flags can be done as autodoc `///` on the line before the define so you can see the comment when hovering over the define anywhere in VSC.

2024-05-03 06:22 UTC, Drulikar commented on code/__DEFINES/mode.dm
> +var/global/list/ROLES_SQUAD_USCM_GROUND = list(SQUAD_USCM_GROUND_1, SQUAD_USCM_GROUND_2) ///Referenced in marines_consoles.dm for crew tracking individual squads+members in the Remote Outpost mode.
Should add the autodoc to the line above this, or make it a normal comment.

2024-05-03 06:22 UTC, Drulikar commented on code/game/turfs/walls/wall_types.dm
> -
So you intend for there to be inorganic resin walls that do form girders? The logic at the moment is indifferent to having it return because its organic (because we aren't just explicitly returning); its just I don't currently see a case where `/turf/closed/wall/resin` should ever be attempting to form a girder.

2024-05-03 06:22 UTC, Drulikar commented on code/__DEFINES/job.dm
> +#define DEPARTMENT_USCM_GROUND_MARINE
Did you mean to keep the defines as nothing?

2024-05-03 16:44 UTC, FslashN commented on code/game/turfs/walls/wall_types.dm
> -
It's not specifically whether or not resin walls should form girders (they likely never should, but what if you had resin walls mixed with metal of some kind?), but that there was no internal logic governing why resin walls should never form girders. Common sense would dictate that living things shouldn't form girders, but common sense is sometimes not enough when it comes to defining object attributes. I want someone five years from now to read the flag defines and go, "yeah, that's why resin walls don't make girders, because they are tagged as organic and organic things obviously wouldn't make them." It makes the behavior more uniform by introducing internal logic that governs it, and instead of checking several different places for overrides, that behavior is centralized into a single proc. Which makes it far easier to find and change if needed, something I found kind of hard to do previously. There's also the point that I made this change specifically with jungle walls in mind, which are also tagged as organic and do not form girders. Half of the Blackstone map is covered in jungle, and those walls are destructible, hence the need for a more centralized behavior governing which walls will form girders.

2024-05-03 16:46 UTC, FslashN commented on code/__DEFINES/job.dm
> +#define DEPARTMENT_USCM_GROUND_MARINE
Oversight and good catch.

2024-05-03 23:29 UTC, Drulikar commented on code/game/turfs/walls/wall_types.dm
> -
You will find most code implements changes via overrides to their member variables, or via overrides to their procs. When a behavior should behave differently, you change the behavior (proc). When you want some value to some a different amount, you change it value.

All this does is suggest organic walls have the parent behavior of forming girders, but then are doing bit match in a boolean conditional to determine that no they shouldn't actually form a girder. But again the logic is really no different. You can argue not doing this change is worse performantly, but I also argue its worse for readability.

2024-05-03 23:50 UTC, Drulikar requested changes

2024-05-03 23:50 UTC, Drulikar commented on code/game/objects/items/storage/wallets.dm
Why out of 173 assignments of `/obj/item/storage`'s `can_hold` list is it done in the definition, and this is the only exception now that does so in Initialize?

2024-05-04 02:11 UTC, FslashN commented on code/game/objects/items/storage/wallets.dm
https://discord.com/channels/725444629172060262/1063155296052191373/1075485560409428111
https://discord.com/channels/725444629172060262/1063155296052191373/1075485675551473674
https://discord.com/channels/725444629172060262/1063155296052191373/1075486117450764328
https://discord.com/channels/725444629172060262/1063155296052191373/1063159589509529700

As I understand it, lists should only be initialized as needed.

2024-05-04 02:21 UTC, FslashN commented on code/game/turfs/walls/wall_types.dm
> -
The default, expected behavior is that walls should form girders, but sometimes they don't. The bitmath determines the condition for when they shouldn't form girders. I don't believe the changes are audodoc'd, though, I do believe there is a comment explaining just that. If an autodoc line will make it more understandable, I can certainly add it.

2024-05-04 09:11 UTC, Drulikar commented on code/game/objects/items/storage/wallets.dm
Your change will make it create that list every single time any wallet is created. Whereas following the norm will mean its simply part of its definition and on byond to handle. This is just an error prone change that is unnecessary.

Revert your change, and try to keep on scope for your PR.

2024-05-04 09:13 UTC, Drulikar commented on code/game/turfs/walls/wall_types.dm
> -
Then specify this information in the autodoc comments at a minimum.

2024-05-04 09:21 UTC, Drulikar commented on code/game/objects/items/storage/wallets.dm
You also may want to re-read the information you linked. Lummox is explaining how its preferable to do it as part of the definition. In other words its re-used data until you modify it for all other instances of that type.

2024-05-04 15:40 UTC, fira commented on code/__DEFINES/mode.dm
> +#define MODE_XENO_AI (1<<17) ///Allows for alien AI to be used in the game mode.
AFAIK `///` applies to the following item - if you want to document the same line as is done here you need an Inner Doc comment which is `//!`

2024-05-04 15:40 UTC, fira commented on code/_onclick/hud/rendering/plane_master.dm
> +	if(. && isobserver(mymob)) /// Simple check for observers here, as that cuts down on a lot of logic that needs to be done otherwise.
Only use autodoc comments (`///`) to document procs and variables before their declaration. Any code comment should be regular ones

2024-05-04 15:40 UTC, fira commented on code/_onclick/hud/rendering/plane_master_controller.dm
> +/atom/movable/plane_master_controller/game/Initialize(mapload, datum/hud/hud)
Is there a specific reason for moving all of these to Initialize() ? /tg/ still uses regular static initialization. As far as I can see it's the same thing with added potential edge case of New-vs-Initialize

2024-05-04 18:22 UTC, FslashN commented on code/game/objects/items/storage/wallets.dm
"If your var has an init proc, e.g. var/mylist[] which will initialize a list before New() is called, or mylist = list(1,2,3), then those vars will take up more memory because they're being filled with a non-default value (in these examples, a new list unique to that object). The init proc will also take up time, and as I've mentioned elsewhere it's better to avoid init procs if you can."

"Avoid init procs wherever possible. This means something like mob/var/items[0], which not only defines items as a list but also instantiates that list whether it's needed or not. Same with mob/shopkeeper/var/wares=list(...). Init procs are time wasters and usually the same thing can be done elsewhere: either in New() or only as needed. Also any vars like this that belong to a turf will eat your memory and make the map take longer to load."

The first quote is from Lummox. Can you point out where Lummox is suggesting to do list initiation as part of the definition? I am not sure I follow what you are talking about.

2024-05-04 18:28 UTC, FslashN commented on code/_onclick/hud/rendering/plane_master.dm
> +	if(. && isobserver(mymob)) /// Simple check for observers here, as that cuts down on a lot of logic that needs to be done otherwise.
It was a a frequent mistake I made. I am trying to eliminate all incorrect usage, so do note if you find more.

2024-05-04 20:52 UTC, FslashN commented on code/_onclick/hud/rendering/plane_master_controller.dm
> +/atom/movable/plane_master_controller/game/Initialize(mapload, datum/hud/hud)
I would figure /tg/ might refactor it already, but maybe there's something else in play. This is the conversation about why it may matter: https://github.com/PvE-CMSS13/PvE-CMSS13/pull/180#discussion_r1589813965

2024-05-04 23:59 UTC, Drulikar commented on code/game/objects/items/storage/wallets.dm
They are conveying that in the case of lists which need to create a new instance in memory, doing so under the definition e.g.

```js
/datum/some_thing
    var/list/some_list = list("something")
 ```
 
 Will internally have to run code that executes the list creation.
 
 So your solution is to do:
 
 ```js
 /datum/some_thing
    var/list/some_list
    
 /datum/some_thing/Initialize()
     some_list = list("something")
```

Which is then is running code to create some list. You have not avoided the fact that code is being executed to create said list. You have simply pushed it off to somewhere else. We do not know *when* this code is executed either. But if you're doing it at runtime and if this normally is done at startup, you're just introducing additional work to run at runtime during a round.

This advice speaks more to how if you want a type to have an empty list it would be ideal to only create the list if its even needed. LAZYLIST serves this purpose because it ensures the list is created if it is null.

 ```js
 /datum/some_thing
    var/list/some_list // We normally want this empty, so lets not bother doing list() right now
    
 /datum/some_thing/proc/add_something()
     LAZYADD(some_list, "something") // This will ensure the list gets created if it hasn't been already
```

What this means is instead of making an empty list that byond has to internally initialize to some data, now the list is only created ever its needed. In the case of the wallets though, we do always want the information of what it can hold to be set up. In general though I think you will find LAZYLIST will be more conservative memory wise at the cost of cpu time.

I'm not saying there isn't some merit to this though; but there is no reason to do it in this PR, nor any reason to *only* do it for wallets. Make a PR where you do this change, and do it for everything. Its far easier for the maintainers reviewing your code to actually review the code because all the changes are related to one thing. It also makes testing the change far easier. For example you could compare master's init time & memory usage vs said PR's changes and see what changes. Whereas in this PR, this PR is supposed to make a new game mode, map, and GM tools. This PR is not aimed at focusing on micro optimizations despite you some reason hyperfixating on this.

So I will reiterate again, leave this as is. If you really somereason want to microoptimize this, do it in another PR where you can focus on that aspect, is easier for other maintainers to review, and easier to test and assert your change even is an improvement.

2024-05-05 00:23 UTC, FslashN commented on code/game/objects/items/storage/wallets.dm
If it's beyond the scope and everything, that's fine. I don't actually have a problem reverting it if it makes it easier to review. The point I am trying to clear up is this:

"Your change will make it create that list every single time any wallet is created. Whereas following the norm will mean its simply part of its definition and on byond to handle. This is just an error prone change that is unnecessary."

And this:

"You also may want to re-read the information you linked. Lummox is explaining how its preferable to do it as part of the definition.'

And also this:

"I see the exception you are likely trying to point out, but I don't see how what you are proposing would be any better than what already is happening."

As I am reading the information linked, Lummox states that there is a right way to do list initialization, and there is a tangible benefit in doing it this way, which should not happen during variable assignment. You appear to be stating that there is, in fact, no benefit in doing so, and it not the proper way to do it. 

Are you saying Lummox is wrong? And if so, can you explain why Lummox is wrong, and why doing this in the way he describes is bad for the game?

This isn't only related to lists, it affects anything that is initialized in variable assignment, like new(). I think it's pretty important to examine this in more detail. To be clear here, I am not asking you to explain to me how list initialization works, or how LAZYADD functions, I am asking you to refute Lummox's assertion.

2024-05-05 00:43 UTC, Drulikar commented on code/game/objects/items/storage/wallets.dm
What I have said does not contradict what Lummox has said, nor am I anywhere saying he is wrong. Please resist your urges to just add one more thing, stay on scope, and if you really want to microoptimize, do that in a separate PR where you are only changing on said aspect so you can get empirical data on whether it even is an improvement.

2024-05-05 00:53 UTC, FslashN commented on code/game/objects/items/storage/wallets.dm
"Your change will make it create that list every single time any wallet is created. Whereas following the norm will mean its simply part of its definition and on byond to handle. This is just an error prone change that is unnecessary."

directly contradicts:

"If your var has an init proc, e.g. var/mylist[] which will initialize a list before New() is called, or mylist = list(1,2,3), then those vars will take up more memory because they're being filled with a non-default value (in these examples, a new list unique to that object). The init proc will also take up time, and as I've mentioned elsewhere it's better to avoid init procs if you can."

I am simply asking you to be clear in what you are asserting, because you are stating several conflicting things. Is Lummox's statement that the correct way to do is outside of variable definition, and that his overall assertion is correct, is your point of view?

2024-05-05 01:45 UTC, Drulikar commented on code/game/objects/items/storage/wallets.dm
Me: 
> Your change will make it create that list every single time any wallet is created. Whereas following the norm will mean its simply part of its definition and on byond to handle. This is just an error prone change that is unnecessary.

- Do you disagree that Initialize is called whenever that type is new'd because SSatoms will call Initialize on it?
- Do you not see that out of 173 assignments of /obj/item/storage's `can_hold` list it is done in the definition?

Lummox:
> "If your var has an init proc, e.g. var/mylist[] which will initialize a list before New() is called, or mylist = list(1,2,3), then those vars will take up more memory because they're being filled with a non-default value (in these examples, a new list unique to that object). The init proc will also take up time, and as I've mentioned elsewhere it's better to avoid init procs if you can."

- This states that performing list() in a definition will make byond execute code to create the list. This is conveyed in my message with `Whereas following the norm will mean its simply part of its definition and on byond to handle`

It is completely within byond's control to better handle this situation and it very well may in the future. I also have stated that we don't know *when* that byond list initialization because of list creation in definition occurs; we just know that it does happen. If its shown to occur at round start when the server is loading, then it is preferable for us for it to be done ahead of time instead of during a round when someone spawns a wallet (which we *do* know occurs because of the object being new'd and SSAtoms Initializing it).

2024-05-05 01:54 UTC, Drulikar commented on code/game/objects/items/storage/wallets.dm
> This is just an error prone change that is unnecessary.

- How is it error prone? Because out of 173 assignments, this one time you do it differently.
- How is it unnecessary? Because it is out of scope for this PR, and is a peanuts change that does not matter in the large scope of things - especially for something barely used like wallets.

Do it in a separate PR, where the scope of the PR is to optimize. This will allow you and other reviewers to get empirical data on how much of a difference this even makes, and possibly when. Why? Because this PR needs to just get outstanding reviews resolved and merged rather than you keeping it in limbo with minor unnecessary changes that then need additional review. I expect you to find that the benefits you reap from changes like this are too inconsequential to be worth your time, but we can find out then with actual data.

2024-05-05 02:47 UTC, FslashN commented on code/game/objects/items/storage/wallets.dm
*Do you disagree that Initialize is called whenever that type is new'd because SSatoms will call Initialize on it?
I do believe that is how it works, yes.

*Do you not see that out of 173 assignments of /obj/item/storage's can_hold list it is done in the definition?
I haven't checked, but I will take your word for it.

*This states that performing list() in a definition will make byond execute code to create the list. This is conveyed in my message with Whereas following the norm will mean its simply part of its definition and on byond to handle
From what I am reading it is better to avoid doing what you describe. Quote: "The init proc will also take up time, and as I've mentioned elsewhere it's better to avoid init procs if you can."

*It is completely within byond's control to better handle this situation and it very well may in the future.
It may be true in the future, but I can't really theorize on what will happen. Such things are hard to predict.

*I also have stated that we don't know when that byond list initialization because of list creation in definition occurs; we just know that it does happen.
This is something that can probably be tested; presumably it runs at run time on world creation. List creation on Initialize() or similar, on the other hand, takes place exactly when you specify it takes place. To me, that seems less ambiguous.

*How is it error prone? Because out of 173 assignments, this one time you do it differently.
Those 173 assignments could be done incorrectly, or in a format that is outdated. There are sections of code that are outdated. There are also examples in the code where list initializion takes places during Initialize() or procs linked to it. We also generally don't initialize new() objects in variable definitions since it leads to all sorts of strange behavior. Just because something is done one way doesn't mean it should stay as such. Also, what errors do you foresee this change causing?
*How is it unnecessary? Because it is out of scope for this PR, and is a peanuts change that does not matter in the large scope of things - especially for something barely used like wallets.
I've already spoke about scope.

I brought this up because I thought adding this change to code guidelines going forward may be beneficial. Would you be open to get Lummox's opinion on this convo?

2024-05-05 03:29 UTC, Drulikar commented on code/game/objects/items/storage/wallets.dm
You're welcome to poke Lummox about it, but Lummox is not familiar with SS13 subsystems and how we have worked around byondisms. You're better off asking in coderbus.

2024-05-05 03:37 UTC, Drulikar commented on code/game/objects/items/storage/wallets.dm
> Also, what errors do you foresee this change causing?

For starters, what Fira also pointed out: https://github.com/PvE-CMSS13/PvE-CMSS13/pull/180#discussion_r1590005686

Where normally this list is set up before New; but now its only set up when this proc finished Initialize.

A more concrete example just randomly searching through usages of the list:

On `Initialize` this calls create_plushie: https://github.com/PvE-CMSS13/PvE-CMSS13/blob/f5025c63f57e3adc770c99710194bf6a8ab19641/code/game/objects/items/toys/toys.dm#L589

`create_plushie` calls `can_be_inserted` which relies on `can_hold_type` having `can_hold`, `cant_hold` and `can_hold_skill` set up already.

Had this called `. = ..()` after the `create_plushie` call it would have had no types available in the to insert, so it would have refused the item insertion.

2024-05-05 12:56 UTC, fira commented on code/_onclick/hud/rendering/plane_master_controller.dm
> +/atom/movable/plane_master_controller/game/Initialize(mapload, datum/hud/hud)
I don't think it's a big deal normally but I was asking for the plane master controllers specifically

During world init, SSatoms defers Initialize on creation until its own SS init (to do it in bulk). Here this means that for a duration (game init so 20-50 seconds), the value of `controlled_planes` won't be what it's supposed to be

From what I can review of plane master code, this shouldn't cause issues here but it's something to be careful changing for backend code, there's more to it than micro-optimizing, and frankly i don't think it's warranted touching that stuff just because

2024-06-10 04:30 UTC, Drulikar requested changes
Maps have unresolved conflicts:
https://github.com/PvE-CMSS13/PvE-CMSS13/actions/runs/9440441060/job/25999760584?pr=180#step:7:150
https://github.com/PvE-CMSS13/PvE-CMSS13/actions/runs/9440441060/job/25999762098?pr=180#step:7:164

2024-08-05 05:49 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2026-08-21 18:53 UTC, closed without merging