RTS-like xeno control [WIP]
cmss13-devs/cmss13-pve pull request #204
Opened 2024-04-01 17:32 UTC by xDanilcusx

# About the pull request

Strongly WIP, meant to gather some suggestions and criticism before going live.
Afterall, this is QoL for our dear game masters, not for me

# Explain why it's good for the game

From what i've seen on actual OPs, GM panel lacks 2 main things that gamemasters sometimes forced to do through sheer improvisation:
1. Ability to command xenos to move somewhere, preferrably in controlled groups
2. Somehow automatically remove capture human orders, because if you just leave it be - in a situation where tagged marine might already be saved and patched up, the "STEAL THAT GUY" mark still remains, forcing some xenos to focus our poor guy.

While fooling around these, i did some other QoL changes that might be neat or useful 

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: Added something
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
spellcheck: fixed a few typos
ui: changed something relating to user interfaces
code: changed some code
refactor: refactored some code
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
mapadd: added a new map or section to a map
maptweak: tweaked a map
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2024-04-01 17:41 UTC, morrowwolf requested changes
random initial review

2024-04-01 17:41 UTC, morrowwolf commented on code/_onclick/drag_drop.dm
> +		if(over && usr.client)
"over" can't not exist here since it's checked for above

2024-04-01 17:41 UTC, morrowwolf commented on code/_onclick/drag_drop.dm
> +
random space

2024-04-01 17:41 UTC, morrowwolf commented on code/datums/components/_component.dm
> -		stack_trace("Incompatible [type] assigned to a [parent.type]! args: [json_encode(arguments)]")
We probably actually want this

2024-04-01 17:49 UTC, xDanilcusx commented on code/datums/components/_component.dm
> -		stack_trace("Incompatible [type] assigned to a [parent.type]! args: [json_encode(arguments)]")
If you say so, i thought of removing it because:
From what i've seen - It's showing up in runtimes tab all the time, and ~~scares the shit out of gms~~ floods it with "Incompatible type" messages, which isn't great when it comes to override orders being placed.
I'll revert in a second if it's needed

2024-04-08 00:06 UTC, morrowwolf commented
As a note, I've made a new component initialize() type that solves the error'ing issues in this PR: <https://github.com/PvE-CMSS13/PvE-CMSS13/pull/173/files#diff-d687de40fdbf308e9e238bf57103c8dde6adedfb700b05d758b01685504cc9aaR7>

We can change it elsewhere when it is done and merged.

2024-04-12 12:04 UTC, harryob requested changes

2024-04-12 12:04 UTC, harryob commented on code/modules/mob/living/carbon/xenomorph/ai/xeno_ai.dm
> +	INVOKE_ASYNC(src, TYPE_PROC_REF(/mob, start_pulling), target)
this will call the base /mob/proc/start_pulling() and not the overrides on the chain down to /xenomorph, is that intended?

2024-04-12 12:04 UTC, harryob commented on code/modules/mob/living/carbon/xenomorph/xeno_ai_interaction.dm
> +		return .
personally i don't think `return .` vs just `return` makes code clearer, but if you do prefer it for clarity that's fine

2024-04-13 01:32 UTC, Zonespace27 requested changes

2024-04-13 01:32 UTC, Zonespace27 commented on code/_onclick/drag_drop.dm
> +	spawn(0)
please PLEASE never use `spawn()`

What are lines 10-14 trying to do or fix, exactly?

2024-04-13 01:32 UTC, Zonespace27 commented on code/_onclick/drag_drop.dm
>  	spawn(0)
yes i know it's done here, but it shouldn't either :<

2024-04-13 01:32 UTC, Zonespace27 commented on code/datums/components/xeno/ai_behavior_overrides/base_override_behavior.dm
> +	var/delete_timer = args[1]
this is generally a bad way to do it. Instead, specify args that should be passed in on the Initialize() definition, line 23 and use that instead

2024-04-13 01:32 UTC, Zonespace27 commented on code/datums/components/xeno/ai_behavior_overrides/base_override_behavior.dm
> +	if(!search_assign && !LAZYLEN(currently_assigned))
`currently_assigned` isn't really a lazylist, you should just use regular remove and length() instead of this.

To that end, line 14 should be `var/list/currently_assigned = list()` and the code on line 38 should be removed

2024-04-13 01:32 UTC, Zonespace27 commented on code/datums/components/xeno/ai_behavior_overrides/hive_override_behavior.dm
> +	if(!LAZYLEN(GLOB.ai_hives))
GLOBs are inherently not lazylists.

2024-04-13 01:32 UTC, Zonespace27 commented on code/modules/admin/game_master/extra_buttons/toggle_capture_crit.dm
> +	if(!GLOB.ai_capture_crit && !LAZYLEN(GLOB.ai_hives))
not lazylist

2024-04-13 01:32 UTC, Zonespace27 commented on code/modules/admin/game_master/extra_buttons/toggle_capture_crit.dm
> +		to_chat(src, SPAN_NOTICE("Xeno Kidnapping requires at least one valid hive placed"))
```suggestion
		to_chat(src, SPAN_NOTICE("Xeno kidnapping requires at least one valid hive placed to be enabled."))
```

2024-04-13 01:32 UTC, Zonespace27 commented on code/modules/admin/game_master/extra_buttons/toggle_capture_crit.dm
> +GLOBAL_VAR(ai_capture_crit)
global declarations should be at the top of a file

2024-04-13 01:32 UTC, Zonespace27 commented on code/modules/admin/game_master/extra_buttons/toggle_capture_crit.dm
> +	message_admins("[src] has [GLOB.ai_capture_crit ? "enabled" : "disabled"] AI kidnapping feature.")
there's a key_name proc or smth like that that's meant to be used for admin logging

2024-04-13 01:32 UTC, Zonespace27 commented on code/modules/admin/game_master/game_master.dm
> +#define DEFAULT_BEHAVIOR_LIFE_SPAN 0
this never seems to be undefined. If it's only used in this file, undef it at the end. If it's used in multiple, put it in the __DEFINES directory.

2024-04-13 01:32 UTC, Zonespace27 commented on code/modules/admin/game_master/game_master.dm
> +	for(var/controlled_xeno in controlled_xenos)
should probably typecast the `controlled_xeno` var and add `as anything`

2024-04-13 01:32 UTC, Zonespace27 commented on code/modules/admin/game_master/game_master.dm
> +			game_master_client.show_popup_menus = FALSE
what's the purpose of this?

2024-04-13 01:32 UTC, Zonespace27 commented on code/modules/admin/game_master/game_master.dm
> +	for(var/controlled_xeno in controlled_xenos)
see my other review

2024-04-13 01:32 UTC, Zonespace27 commented on code/modules/admin/game_master/game_master.dm
> +				for(var/atom/selected_xeno in GLOB.xeno_mob_list)
add `as anything`

2024-04-13 01:32 UTC, Zonespace27 commented on code/modules/admin/game_master/game_master.dm
> +					object.AddComponent(behavior_type, behavior_lifespan SECONDS)
`behavior_lifespan` should have the SECONDS macro, not the call here.

2024-04-13 01:32 UTC, Zonespace27 commented on code/modules/admin/game_master/game_master.dm
> +						if(LAZYLEN(currently_assigned) >= behavior.max_assigned)
is `currently_assigned` a lazylist?

2024-04-13 01:32 UTC, Zonespace27 commented on code/modules/admin/game_master/game_master.dm
> +				for(var/deselected_xeno in controlled_xenos)
see my other for loop comments

2024-04-13 01:32 UTC, Zonespace27 commented on code/modules/admin/game_master/game_master.dm
> +	if(controlled_xenos?[selected_xeno])
why the `?`? on the line above, you treat it like it's guaranteed to be a list already

2024-04-13 01:32 UTC, Zonespace27 commented on code/modules/mob/living/carbon/xenomorph/ai/movement/base_define.dm
> +		var/patrol_lenght = length(patrol_points)
length is misspelled

2024-04-13 01:32 UTC, Zonespace27 commented on code/modules/mob/living/carbon/xenomorph/ai/movement/base_define.dm
> +	if(get_dist(move_target, moving_xeno) <= 1)
might want to make the `1` a var? I could see a variable distance being useful in some cases

2024-04-13 01:32 UTC, Zonespace27 commented on code/modules/mob/living/carbon/xenomorph/ai/xeno_ai.dm
> +	INVOKE_ASYNC(src, TYPE_PROC_REF(/mob, start_pulling), target)
What harry said pretty much. TYPE_PROC_REF is only needed when you need a proc ref to something other than the type the code is being executed in.

2024-04-13 23:04 UTC, xDanilcusx commented on code/modules/mob/living/carbon/xenomorph/ai/movement/base_define.dm
> +	if(get_dist(move_target, moving_xeno) <= 1)
i'll make it an arg

2024-04-17 11:11 UTC, xDanilcusx commented on code/_onclick/drag_drop.dm
> +	spawn(0)
It's basically a wrapper for selection box thing, that needs to be executed on MouseDrop no matter if we Adjacent() to it or not

2024-04-17 11:21 UTC, xDanilcusx commented on code/modules/admin/game_master/game_master.dm
> +	for(var/controlled_xeno in controlled_xenos)
Dunno if we really need this if whole select/deselect thing just operates with lists, no typecasting whatsoever

2024-04-17 11:25 UTC, xDanilcusx commented on code/modules/admin/game_master/game_master.dm
> +			game_master_client.show_popup_menus = FALSE
To be able to intercept RMB clicks, just as buildmode does

2024-08-07 21:56 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-08-09 05:36 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-08-15 16:58 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-08-15 17:00 UTC, xDanilcusx commented
oh uh, why did it rebase WHY DID IT REBASE

2024-08-15 17:17 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-08-15 17:18 UTC, xDanilcusx commented
Phew, i unfucked it

2024-08-15 17:19 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-08-23 12:14 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-10-03 17:30 UTC, mesnomer commented
Two notes here from some local server playtesting:

1. The AI's strict adherence to hitting the exact tile for the move order can lead to some goofy arrangements when you have multiple selected. Starts becoming more noticeable once you reach 10+ selected xenos and the stragglers start pushing the others in front of them.

2. Would be nice to have a "stop" keybind that just removes any move orders from selected xenos to free them up so they can act on their own. This would serve as a workaround for the previous note -- as-is you have to place a move order under the group and wait for the shuffling to stop. Or maybe I'm missing something.

But yeah. This _rules._ Thank you so much!

2025-01-31 01:36 UTC, closed without merging