Poncho fix - hides belts beneath poncho
cmss13-devs/cmss13-pve pull request #223
Opened 2024-04-08 00:19 UTC by AmoryBlaine

Ponchos no longer layer below belts. They go above them. Backpacks and suitslot not affected. Thanks to Rock/ForwardNSlash for this fix.

# About the pull request

# Explain why it's good for the game

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: Added something
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
spellcheck: fixed a few typos
ui: changed something relating to user interfaces
code: changed some code
refactor: refactored some code
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
mapadd: added a new map or section to a map
maptweak: tweaked a map
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2024-04-08 19:10 UTC, FslashN commented
I remember that this worked as intended, but the code was more of a workaround since accessories aren't designed with that implementation in mind.

2024-04-15 04:30 UTC, Zonespace27 requested changes

2024-04-15 04:30 UTC, Zonespace27 commented on code/modules/clothing/under/ties.dm
> +	if(!has_suit) return
Split this across 2 lines please

2024-04-15 04:30 UTC, Zonespace27 commented on code/modules/clothing/under/ties.dm
> +	var/obj/item/clothing/suit/storage/marine/S = has_suit
One letter var

2024-04-15 04:30 UTC, Zonespace27 commented on code/modules/mob/living/carbon/human/update_icons.dm
> +								var/obj/item/clothing/accessory/A = K
Ditto

2024-04-15 04:30 UTC, Zonespace27 commented on code/modules/mob/living/carbon/human/update_icons.dm
> +								var/obj/item/clothing/accessory/A = K
Ditto

2024-06-29 06:08 UTC, AmoryBlaine commented on code/modules/clothing/under/ties.dm
> +	if(!has_suit) return
I have no idea how to condense this into 2 lines, I copypasted Rock's suggestion and made this PR

2024-07-19 23:43 UTC, Doubleumc commented on code/modules/clothing/under/ties.dm
> +	if(!has_suit) return
By "Split this across 2 lines" Zonespace means the `if(!has_suit) return` part. It is more readable and easier to understand by having the statement on a new indented line after the condition, like so:
```suggestion
	if(!has_suit)
		return
```

2024-07-19 23:50 UTC, Doubleumc commented on code/modules/clothing/under/ties.dm
> +	var/obj/item/clothing/suit/storage/marine/S = has_suit
Where possible expand single letter variables into a longer, more descriptive name. This makes it easier to understand what that variable is at a glance. Like so:
```suggestion
	var/obj/item/clothing/suit/storage/marine/suit = has_suit
```
Can read more here:
https://github.com/cmss13-devs/cmss13-pve/blob/8cec823238dac450a9b4cd7b7da94e18d341ae1f/.github/guides/STYLES.md#dont-use-abbreviations

2024-07-19 23:53 UTC, AmoryBlaine commented on code/modules/clothing/under/ties.dm
> +	if(!has_suit) return
Oh lol, I thought they meant the whole thing 427 and 428.

2024-08-30 16:36 UTC, closed without merging