Garrow Modifications 2
cmss13-devs/cmss13-pve pull request #266
Opened 2024-05-20 05:28 UTC by DexterDude

Fixes some issues, namely some layering stuff and some missing pipes, as well as the platco phone category (thanks andro for reminding me)

Also adds some QOL for GMs by giving them some mostly empty cargo bays and more accessible and clear buttons.

Also adds support:tm: for Andro to add elevators. I looked at it and it seemed a little more complicated than normal shuttles, so I figured I'd leave it to the experts. Don't merge before then, please!

2024-05-20 13:41 UTC, DexterDude commented
fail...oh my science...

2024-07-27 04:42 UTC, AmoryBlaine commented
![image](https://github.com/user-attachments/assets/982cf8a4-a3ae-477a-a6a6-73abdd326e9c)
Gotta fix the layering here

2024-07-27 14:07 UTC, Steelpoint commented
Rogue blast door tile at south-west end of the main hanger deck. 

Might be a missile pipe at the far, far, north end of hanger.

2024-08-21 00:14 UTC, Doubleumc requested changes

2024-08-21 00:14 UTC, Doubleumc commented on code/datums/shuttles.dm
> +
```suggestion
/datum/map_template/shuttle/golden_arrow
	shuttle_id = "unused"

```
Need a dummy parent type here to avoid annoying the unit tests. `shuttle_id` doesn't matter besides it not being `"SHOULD NEVER EXIST"`.

A subtype implies the existence of its parent type. So a `/datum/map_template/shuttle/golden_arrow/vehicleone` implies that a `/datum/map_template/shuttle/golden_arrow` exists. Since its not explicitly defined, it inherits all its values directly from `/datum/map_template/shuttle`, including `shuttle_id = "SHOULD NEVER EXIST"`.

One of the unit tests checkss all the subtypes of `/datum/map_template/shuttle` to ensure that `shuttle_id` is set to something other than `"SHOULD NEVER EXIST"`. It was triggering on this implied type.

2024-08-21 19:10 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-08-22 01:34 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-08-22 09:52 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-08-23 12:01 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-08-24 00:45 UTC, Doubleumc requested changes
My main hangup with this PR is that its modifying internals in how docking ports and shuttles work. I'd like to find a way to avoid that if possible.

First thought was to repath the new elevators to be subtypes of `trijent_elevator`. That would make all the internal changes unnecessary. Issue there is trijent elevators expect doors to control, and the vehicle elevators have none. Could change *that* bit of code instead, which is a lesser change but still a change.

Second thought is that the vehicle elevators in particular are trying to combine some function of trijent-style elevators and ASRS-style elevators, which work differently. That's where the "falls into the depths" message comes from, trijent doesn't use those fall-through turfs like the ASRS does, and the open/empty space is still set to throw you into the ASRS pit. Perhaps the vehicle elevators would work better as ASRS-like effects than full shuttles.

Once conflicts and the other issues below are resolved, this is fine for TMing. Still thinking on how to handle the above before merging -- just not familiar enough with shuttles or the ASRS.

2024-08-24 00:45 UTC, Doubleumc commented on code/game/machinery/doors/poddoor.dm
> +	relativewall_neighbours()
What is the purpose of this change? I'm unable to see the difference it makes.

2024-08-24 00:45 UTC, Doubleumc commented on code/modules/shuttle/shuttle.dm
> +		playsound(dropzone.return_center_turf(), landing_sound, 60, 0)
Sounds start playing immediately on landing instead of during the windup to landing. Perhaps `on_ignition()` would be better, or check how the dropships handle it:
https://github.com/cmss13-devs/cmss13-pve/blob/6c5ba9ac4b19f8597978ad5b4399213a3f07ac94/code/modules/shuttle/shuttles/dropship.dm#L212-L227

2024-08-24 00:45 UTC, Doubleumc commented on code/modules/shuttle/shuttles/shipmap_elevator.dm
> +
A leaving elevator's docking port creates a message of it falling into the shaft:
![image](https://github.com/user-attachments/assets/57994be0-6064-43fc-ae31-212e93f095c1)
![image](https://github.com/user-attachments/assets/7a1515c1-6dc7-4b23-89bd-7a85540ebaf5)

Suggest adding something like this, which is how the ASRS elevator prevents that issue:
```suggestion
/obj/docking_port/mobile/shipmap_elevator/visible_message() //Prevents message spam with empty elevator shaft - "The empty space falls into the depths!"
	return

```

2024-08-24 00:45 UTC, Doubleumc commented on maps/shuttles/garrow_vehicle_elevator_two.dmm
> +	},
There's a controller in the middle of elevator two, but not elevator one.

2024-08-24 00:45 UTC, Doubleumc commented on maps/map_files/golden_arrow/golden_arrow.dmm
Lower level of the elevators shouldn't have the open/empty turf you can fall in to, since they are the bottom.

Upper open/empty turf should fall into its lower counterpart, instead of into the ASRS pit.

2024-08-24 00:45 UTC, Doubleumc commented on code/modules/shuttle/shuttles/shipmap_elevator.dm
> +			INVOKE_ASYNC(R, TYPE_PROC_REF(/obj/structure/machinery/door, close))
Currently railings don't raise until several seconds after the elevator has left. Perhaps in `on_ignition()` instead?

2024-08-24 20:30 UTC, DexterDude commented
> Second thought is that the vehicle elevators in particular are trying to combine some function of trijent-style elevators and ASRS-style elevators, which work differently. That's where the "falls into the depths" message comes from, trijent doesn't use those fall-through turfs like the ASRS does, and the open/empty space is still set to throw you into the ASRS pit. Perhaps the vehicle elevators would work better as ASRS-like effects than full shuttles.

My reasoning for having them be elevators is because its much more interesting for the players to bring them onto the elevators themselves and lift them up on their own versus it being a magic vehicle lifting system. That, and it means we dont have to code in extra things like GMs having to enable or disable certain vehicles being able to come up or down. It adds more depth to the map itself without requiring additional code. I agree with mostly everything else however. Eventually when Andro gets around to it the elevators will have little remote controls people can pick up, but for now they can use the call buttons.

2024-08-24 20:31 UTC, DexterDude commented on maps/map_files/golden_arrow/golden_arrow.dmm
True.

2024-08-24 20:31 UTC, DexterDude commented on maps/shuttles/garrow_vehicle_elevator_two.dmm
> +	},
Woops! Forgot to delete that after testing.

2024-08-27 18:38 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-08-27 19:48 UTC, AndroBetel commented on code/modules/shuttle/shuttle.dm
> +		playsound(dropzone.return_center_turf(), landing_sound, 60, 0)
changed it to play on ignition, now sounds as intended

2024-08-27 19:58 UTC, AndroBetel commented on code/modules/shuttle/shuttles/shipmap_elevator.dm
> +			INVOKE_ASYNC(R, TYPE_PROC_REF(/obj/structure/machinery/door, close))
fixed

2024-08-27 20:03 UTC, AndroBetel commented on code/game/machinery/doors/poddoor.dm
> +	relativewall_neighbours()
looks like it just removes weird timered proc with nicer LateInitialize

2024-08-27 21:52 UTC, Doubleumc commented on code/game/machinery/doors/poddoor.dm
> +	relativewall_neighbours()
Cleaner looking code to be sure, but would prefer this be done on PvP then pulled here to keep compatibility.

2024-08-28 18:44 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-09-04 07:28 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-09-04 22:02 UTC, Doubleumc requested changes
Just a few things to tidy up. Besides that, code good.

2024-09-04 22:02 UTC, Doubleumc commented on maps/map_files/golden_arrow/golden_arrow.dmm
What's the purpose of the railing control button for the cargo elevator? The railings are working correctly so they're raised when its unsafe and lowered when its safe.

2024-09-05 00:26 UTC, DexterDude commented on maps/map_files/golden_arrow/golden_arrow.dmm
Didnt know they automatically changed.

2024-09-05 03:21 UTC, Doubleumc approved these changes

2024-09-05 04:16 UTC, Doubleumc submitted a review, later dismissed

2024-09-05 22:32 UTC, merged