ATTACHMENT FLAVOR TEXT GO
cmss13-devs/cmss13-pve pull request #276
Opened 2024-06-02 06:48 UTC by KoishiVibe

# Summary

new year new flavor text
also includes UPP variants for most of the attachments (cosmetic)

# Explain why it's good for the game

muh immersion

2024-06-03 23:47 UTC, KoishiVibe commented
it should be ready technically.

2024-06-05 12:30 UTC, AndroBetel requested changes

2024-06-05 12:30 UTC, AndroBetel commented on code/modules/projectiles/gun_attachables.dm
> +	name = "RK-9 Vertical Grip"
vertical?

2024-06-05 12:30 UTC, AndroBetel commented on code/modules/projectiles/gun_attachables.dm
> +	desc = "Visible band 512nm green laser, compatible with NVG and IR. Bears striking resemblance to an old Weyland Yutani offering... Decreases scatter, especially onehanded, slightly boosts accuracy.
green?

2024-06-05 12:31 UTC, AndroBetel commented
upp attachies could also use some custom sprites ig... to fit the theme better... but mostly whatever...

2024-06-07 21:05 UTC, KoishiVibe commented on code/modules/projectiles/gun_attachables.dm
> +	desc = "Visible band 512nm green laser, compatible with NVG and IR. Bears striking resemblance to an old Weyland Yutani offering... Decreases scatter, especially onehanded, slightly boosts accuracy.
aw piffle. I knew I forgor'd something. ....
I'll sprite something. Soon.

2024-06-16 17:49 UTC, KoishiVibe commented on code/modules/projectiles/gun_attachables.dm
> +	desc = "Visible band 512nm green laser, compatible with NVG and IR. Bears striking resemblance to an old Weyland Yutani offering... Decreases scatter, especially onehanded, slightly boosts accuracy.
sprited lol

2024-07-24 23:05 UTC, Doubleumc requested changes
Subtype them as `upp` instead of `union`, for example: `/obj/item/attachable/angledgrip/upp` instead of `/obj/item/attachable/angledgrip/union`

Everything else UPP is typed `upp`, these should be as well.

2024-07-31 06:27 UTC, Doubleumc commented on code/modules/projectiles/gun_attachables.dm
> +	attach_icon = "lasersight_union_a"
```suggestion
	icon_state = "lasersight_upp"
	attach_icon = "lasersight_upp_a"
```
Will want to change the icon name here and in `under.dmi` as well.

Other than that, code looks good to me.

2024-08-11 07:24 UTC, KoishiVibe commented on code/modules/projectiles/gun_attachables.dm
> +	attach_icon = "lasersight_union_a"
thx for the catch yo

2024-08-11 08:01 UTC, Doubleumc commented on code/modules/projectiles/gun_attachables.dm
> +	attach_icon = "lasersight_union_a"
You still need to change the icon names in `under.dmi` to match.

2024-08-13 06:24 UTC, KoishiVibe commented on code/modules/projectiles/gun_attachables.dm
> +	attach_icon = "lasersight_union_a"
goddamnit-
dmc
>:(

2024-08-13 07:03 UTC, Doubleumc approved these changes

2024-08-17 06:16 UTC, merged