More Fluff Things
cmss13-devs/cmss13-pve pull request #283
Opened 2024-06-06 20:13 UTC by KoishiVibe

# Summary
- M240A1 is now M240. This has been bothering me for a while how can you tell?
- M240-T is now M240E1. 
- XM88 is now the XM88A. Should be nominally more in line with other armat weapons?
- ammo for it has been modified to be something more in line with other inuniverse calibers, such as .458 socom now becoming a 10mm variety.

2024-06-07 00:03 UTC, DexterDude commented
can you provide lore reasoning

2024-06-07 00:04 UTC, DexterDude commented
also, undocumented changes (random bullet name changes)

2024-06-07 15:44 UTC, KoishiVibe commented
> also, undocumented changes (random bullet name changes)

oh right i was gonna update after I added those but forgor.

2024-08-08 23:22 UTC, Doubleumc requested changes
Revert the undocumented changes to the M42A.

Otherwise, looks good to me.

2024-08-15 05:31 UTC, Doubleumc commented
Feel free to reopen when the issues have been addressed.

2024-08-17 06:20 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-01-29 01:18 UTC, closed without merging