Sentry Laptops In vendors
cmss13-devs/cmss13-pve pull request #295
Opened 2024-06-13 19:45 UTC by KoishiVibe

# Summary
- sentry laptops now in vendors. 
- some of the computer alert text has been changed to seem more mechanical and 'efficient'.
- lieutenant's headset now has sentry integration by default, since he doesn't have them on cameras... yet.

2024-06-15 08:43 UTC, DexterDude commented
I do like Platoon Commander's getting sentry radio though, makes them more useful in a base defense situation and giving the PlatCo more things to do and more ways to assist their platoon is neat.

2024-06-15 08:49 UTC, KoishiVibe commented
> I do like Platoon Commander's getting sentry radio though, makes them more useful in a base defense situation and giving the PlatCo more things to do and more ways to assist their platoon is neat.

tbh it sa lazyfix for not having overwatch access to sentry cameras linked up or not having a common marine sentry band for overwatch, but...
c'est la vie.

2024-06-16 17:59 UTC, DexterDude requested changes

2024-06-16 18:02 UTC, KoishiVibe commented on code/datums/fluff_emails.dm
> -
yeah idk whats up with that I fucked up my master somehow.

2024-06-16 18:04 UTC, KoishiVibe commented on code/modules/defenses/sentry_computer.dm
> +	var/message = "[displayname]:[areaname] NO SIGNAL."
hmmm
funni time.

2024-06-22 03:26 UTC, KoishiVibe commented on code/modules/defenses/sentry_computer.dm
> +	var/message = "[displayname]:[get_area(sentrygun)] ENGAGED"
bleh, fine. I'll make a sentry flavor text pass one day.

2024-07-22 07:33 UTC, Doubleumc approved these changes
Looks good to me.

2024-07-22 21:09 UTC, merged