Heavy Pulse RIfle Rework
cmss13-devs/cmss13-pve pull request #298
Opened 2024-06-16 17:56 UTC by KoishiVibe

# summary
- removes Funny Bipod Full Auto Bug. kinda.
- adds inte grated bipod, adds collapsible stock. 
- makes the weapon more of a workable sidegrade even if not bipodded

2024-06-22 06:17 UTC, KoishiVibe reviewed
Testing is complete. Standing by for review. I kind of want to nerf the moving scatter a little though...

2024-06-22 06:30 UTC, KoishiVibe commented
todo:
- art pass to make the stock and bipod seem more integral
- balancing pass, I suspect the basic nonextended mode needs to be scatter nerfed to make it less accurate?

2024-06-25 04:29 UTC, KoishiVibe reviewed
Feature complete, more or less. Ready to rock!

2024-06-29 09:09 UTC, AndroBetel commented
will be testmerged on red

2024-07-08 08:04 UTC, KoishiVibe commented
Nerf consists of a reduction in general scatter and accuracy, especially onehanded. Hopefully it should remain great in bipod with stock out and acceptable with stock open on the go.

I'll code a custom section for it tomorrow and also have the bipod reduce scatter while active.

2024-07-09 04:58 UTC, KoishiVibe commented
hokay. ammo path fixed and damage should be corrected.

2024-08-17 06:20 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-11-27 22:04 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-12-02 08:17 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-12-27 08:39 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-12-27 23:56 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-01-16 05:40 UTC, The32bitguy commented
The HPR spawned on LV 624 looked like this.
![Screenshot 2025-01-16 053847](https://github.com/user-attachments/assets/490b8199-a0f0-4de6-b755-5ca339f2309e)
![image](https://github.com/user-attachments/assets/da835825-ff8c-41cf-8c4a-5d941585e896)

2025-01-16 09:25 UTC, KoishiVibe commented
> The HPR spawned on LV 624 looked like this. ![Screenshot 2025-01-16 053847](https://private-user-images.githubusercontent.com/35638613/403702417-490b8199-a0f0-4de6-b755-5ca339f2309e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzcwMTk4MDgsIm5iZiI6MTczNzAxOTUwOCwicGF0aCI6Ii8zNTYzODYxMy80MDM3MDI0MTctNDkwYjgxOTktYTBmMC00ZGU2LWI3NTUtNWNhMzM5ZjIzMDllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTE2VDA5MjUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkMThiZjg0MDBlNWNmOWZlMGE1MTA5ZTU1ZWE4ZjU0Y2FiYzIyYzhhMWE5ZDc2NDgxNjQ5YzkzMGVkZjE1ZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EkYhcon9e3EybVgyBHtDbeznuhcm0eVL0kMFPAfU5qQ) ![image](https://private-user-images.githubusercontent.com/35638613/403702472-da835825-ff8c-41cf-8c4a-5d941585e896.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzcwMTk4MDgsIm5iZiI6MTczNzAxOTUwOCwicGF0aCI6Ii8zNTYzODYxMy80MDM3MDI0NzItZGE4MzU4MjUtZmY4Yy00MWNmLThjNGEtNWQ5NDE1ODVlODk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTE2VDA5MjUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5NmVkNjI2MDJiYzgwMDIwZGIwOTE4YzE0NDc0OTVmZGRlNTQzZjdkNGI5NTBjNGJkZGEwMDQ4NGMxMjUyOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TW73cK9-CH7rIF9RO-yIQZKfvjOXyuJruFfkMfdYwD8) ![image](https://private-user-images.githubusercontent.com/35638613/403704748-978ba4e2-7a7a-465f-8550-f02ab6360db9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzcwMTk4MDgsIm5iZiI6MTczNzAxOTUwOCwicGF0aCI6Ii8zNTYzODYxMy80MDM3MDQ3NDgtOTc4YmE0ZTItN2E3YS00NjVmLTg1NTAtZjAyYWI2MzYwZGI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTE2VDA5MjUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkZmUxNDYzYmQ3ZjlmNTEyMDkxNWI4ZmIxYTY2NDNiOWIxZTYyNjUyODc4ZTllNDhlOGE5NTdhYjliYWUxZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hUcq7mze0eQ3oIpU7i77-CrHB-sspYR2YSHdiWgzZLg)

Fixed.

2025-01-24 02:44 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-01-25 12:36 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-01-26 06:31 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-01-29 19:59 UTC, AndroBetel requested changes

2025-01-29 19:59 UTC, AndroBetel commented on code/modules/projectiles/magazines/misc.dm
> +	name = "\improper M41AE2 APHE ammo box (10x24mm)"
its heap not aphe

2025-01-29 19:59 UTC, AndroBetel commented on code/modules/projectiles/magazines/misc.dm
> +	default_ammo = /datum/ammo/bullet/rifle/heap
shouldnt this be AP

2025-01-29 19:59 UTC, AndroBetel commented on code/modules/projectiles/guns/rifles.dm
> +	starting_attachment_types = list(/obj/item/attachable/magnetic_harness, /obj/item/attachable/extended_barrel)
is the army hpr intended to not have bipod/stock

2025-01-29 20:01 UTC, BonniePandora commented on code/modules/projectiles/guns/rifles.dm
> +	starting_attachment_types = list(/obj/item/attachable/magnetic_harness, /obj/item/attachable/extended_barrel)
Base HPR seems to come with integrated bipod now, so the added one for the army one isn't needed

2025-01-29 20:06 UTC, AndroBetel commented
also burst fire is too good without the bipod

2025-01-29 20:28 UTC, KoishiVibe commented on code/modules/projectiles/magazines/misc.dm
> +	default_ammo = /datum/ammo/bullet/rifle/heap
...honestly not sure how I made that mistake. Very good catch. Fixed.

2025-01-29 20:28 UTC, KoishiVibe commented on code/modules/projectiles/magazines/misc.dm
> +	name = "\improper M41AE2 APHE ammo box (10x24mm)"
Yeah, I should atomize that change... Fixed.

2025-01-29 20:29 UTC, KoishiVibe commented on code/modules/projectiles/guns/rifles.dm
> +	starting_attachment_types = list(/obj/item/attachable/magnetic_harness, /obj/item/attachable/extended_barrel)
doublechecking that DMjank wont make me a liar...

2025-01-29 20:32 UTC, KoishiVibe commented on code/modules/projectiles/guns/rifles.dm
> +	starting_attachment_types = list(/obj/item/attachable/magnetic_harness, /obj/item/attachable/extended_barrel)
yeeees, apparently DMJank strikes again. Standby.

2025-01-29 20:35 UTC, KoishiVibe commented on code/modules/projectiles/guns/rifles.dm
> +	starting_attachment_types = list(/obj/item/attachable/magnetic_harness, /obj/item/attachable/extended_barrel)
Fixed.

2025-01-29 20:43 UTC, AndroBetel approved these changes

2025-01-29 20:44 UTC, merged