Shotgun Overhaul
cmss13-devs/cmss13-pve pull request #304
Opened 2024-06-22 06:35 UTC by AmoryBlaine

The intent of this PR is to repurpose the various shotguns into a role of their own as primarily functioning to focus knockback and stun damage to xenomorphs, rather than as outright killers. The intended goal of this is to fit shotguns better into the gameplay of PvE. Where hordes can easily overwhelm you even with heavy firepower, the shotgun will be able to buy you a moment of relief by knocking back advancing xenomorphs allowing your teammates to sustain accurate fire and maintain position.

- The Mk221 will be made faster firing and may have its own subtype of shotgun shells that will be refered to lorewise as 20ga in order to reflect the lower damage output they give when compared to the standard ithaca 12 gauge. The primary ammo type will be knockback focused buckshot.
- The M37 will lose super buck in favour of supplying the user a collection of slugs, buck and other ammo types in order to give total variety to its application. Buck will be handled like a more powerful version of the Mk221's buck, slugs will focus penetration and higher damage on top of the knockback and stuns. Undecided for incendiary and flechette ammo
- UPP shotgun will be made not crap (buffed additional pellets, buffed rate of fire)
- To be determined in regards to other shotguns

2024-06-29 20:05 UTC, bearrrrrrrr commented
uhhh this kinda directly conflicts w/ the use of the M4RA. not a huge fan :T

2024-08-05 19:06 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-08-18 19:38 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-08-23 01:25 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-08-24 19:59 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-08-26 20:32 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-08-27 23:49 UTC, Doubleumc requested changes
Either make the indicated slowdowns long enough to matter or remove them. Otherwise looks good.

2024-08-27 23:49 UTC, Doubleumc commented on code/datums/ammo/bullet/shotgun.dm
> +			living_mob.Slow(2)
```suggestion
			living_mob.KnockDown(2)
			living_mob.Stun(2)
```
Slowed for the same duration you can't move, therefore slowing never matters.

2024-08-27 23:49 UTC, Doubleumc commented on code/datums/ammo/bullet/shotgun.dm
> +			living_mob.Slow(2)
```suggestion
			living_mob.KnockDown(2)
			living_mob.Stun(2)
```
Slowed for the same duration you can't move, therefore slowing never matters.

2024-08-28 00:01 UTC, AmoryBlaine commented on code/datums/ammo/bullet/shotgun.dm
> +			living_mob.Slow(2)
Yeah forgot to fill in () when I copypasted it

2024-08-28 00:37 UTC, Doubleumc approved these changes

2024-08-28 18:39 UTC, merged