Kills weather site overlays
cmss13-devs/cmss13-pve pull request #320
Opened 2024-07-03 17:56 UTC by AmoryBlaine

I hate the welder/damaged eyes effects on the screen when there's rain or sandstorms. This effectively kills that and replaces it with nothing so you can properly see the screen even during rain and dust storms. Much more visually appealing and I don't have to worry about the downpour gimping the platoon and making a game reliant on sight even harder.

2024-07-23 14:21 UTC, AndroBetel requested changes

2024-07-23 14:21 UTC, AndroBetel commented on code/_onclick/hud/fullscreen.dm
> +///atom/movable/screen/fullscreen/weather
im not sure how tf is this still compiling but don't remove this altogether, just remove the fullscreen defines from weather types (NOT comment them out), because the behaviour itself can still be useful

2024-07-23 14:21 UTC, AndroBetel commented on code/_onclick/hud/fullscreen.dm
> +///atom/movable/screen/fullscreen/weather
oh yeah its compiling because now all these things are defined for vulture scope thingy lol

2024-08-28 05:41 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-09-14 03:25 UTC, AmoryBlaine commented on code/_onclick/hud/fullscreen.dm
> +///atom/movable/screen/fullscreen/weather
Okay

2024-09-21 23:50 UTC, Doubleumc requested changes
Should also remove the code defining the weather overlays in the first place, as they no longer have a purpose:
https://github.com/cmss13-devs/cmss13-pve/blob/cfcf8435a8b7b357993012e98247adfd5f3165ea/code/_onclick/hud/fullscreen.dm#L194-L210

2024-09-21 23:50 UTC, Doubleumc commented on code/datums/weather/weather_event.dm
> +	//var///fullscreen_type = null  // If this is set, display a fullscreen type to mobs
```suggestion
```
No need to comment it out. If someone wants to revert it they'll do it through version control, not by uncommenting it.

2024-09-21 23:50 UTC, Doubleumc commented on code/datums/weather/weather_events/sorokyne.dm
> +	//fullscreen_type = /atom/movable/screen/fullscreen/weather/high
```suggestion
```

2024-09-21 23:50 UTC, Doubleumc commented on code/datums/weather/weather_events/sorokyne.dm
> +	//fullscreen_type = /atom/movable/screen/fullscreen/weather/medium
```suggestion
```

2024-09-21 23:50 UTC, Doubleumc commented on code/datums/weather/weather_events/sorokyne.dm
> +	//fullscreen_type = /atom/movable/screen/fullscreen/weather/low
```suggestion
```

2024-09-21 23:50 UTC, Doubleumc commented on code/datums/weather/weather_events/new_varadero.dm
> +	//fullscreen_type = /atom/movable/screen/fullscreen/weather/high
```suggestion
```

2024-09-21 23:50 UTC, Doubleumc commented on code/datums/weather/weather_events/lv624.dm
> +	//fullscreen_type = /atom/movable/screen/fullscreen/weather/medium
```suggestion
```

2024-09-21 23:50 UTC, Doubleumc commented on code/datums/weather/weather_events/lv624.dm
> +	//fullscreen_type = /atom/movable/screen/fullscreen/weather/low
```suggestion
```

2024-09-21 23:50 UTC, Doubleumc commented on code/datums/weather/weather_events/faction_clash.dm
> +	//fullscreen_type = /atom/movable/screen/fullscreen/weather/low
```suggestion
```

2024-09-21 23:50 UTC, Doubleumc commented on code/modules/mob/living/living_defense.dm
>  	if(current_weather_effect_type != starting_weather_type)
```suggestion
```
This whole section can be removed.

2024-09-21 23:50 UTC, Doubleumc commented on code/modules/mob/living/living_defense.dm
> +		clear_fullscreen("weather")
```suggestion
```
No need to clear something that will never be applied.

2024-09-23 20:22 UTC, Doubleumc approved these changes

2024-10-07 08:12 UTC, AndroBetel approved these changes

2024-10-07 08:19 UTC, merged