Fire Support Menu for GM's
cmss13-devs/cmss13-pve pull request #321
Opened 2024-07-03 20:43 UTC by sunofang

# About the pull request
Adds a fire support menu to allow game masters to call in various types of ordnance, and make it have the same noises/effects as a normal shot for extra soul.

Mention if you have tested your changes. If you changed a map, make sure you used the mapmerge tool.
If this is an Issue Correction, you can type "Fixes Issue #169420" to link the PR to the corresponding Issue number #169420.

Remember: something that is self-evident to you might not be to others. Explain your rationale fully, even if you feel it goes without saying. -->

# Explain why it's good for the game
uhh- good for GM's to be able to explode stuff at will.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Will do this later.

</details>

# Changelog

:cl:
add: Due to budget increases, Close Air Support now has ammo.
admin: Added a fire support menu for GM's to use.
/:cl:

2024-07-08 00:56 UTC, bearrrrrrrr commented
i love this so much it's unreal

will give feedback after dis op

2024-07-08 02:50 UTC, bearrrrrrrr commented
no complaints

seems as if one gm swapping on the panel changes it for all gm's, though? not a big deal if it's not fixable

2024-07-08 09:30 UTC, sunofang commented
Would need to make the vars client specific so it'd need alot of work for little to no gain.

2024-07-18 07:39 UTC, harryob commented
address ci failure here https://github.com/cmss13-devs/cmss13-pve/actions/runs/9814119437/job/27101290362?pr=321#step:7:28

2024-07-18 07:46 UTC, harryob requested changes

2024-07-18 07:46 UTC, harryob commented on code/modules/admin/game_master/extra_buttons/fire_support_menu.dm
> +/datum/fire_support_menu/proc/HandleOrbitalOrdnance(turf/target_turf, obj/structure/ob_ammo/warhead/ammo)
procs should be snake case

2024-07-18 07:46 UTC, harryob commented on code/modules/admin/game_master/extra_buttons/fire_support_menu.dm
> +client/proc/toggle_fire_support_menu()
```suggestion
/client/proc/toggle_fire_support_menu()
```

2024-07-18 10:52 UTC, sunofang commented on code/modules/admin/game_master/extra_buttons/fire_support_menu.dm
> +/datum/fire_support_menu/proc/HandleOrbitalOrdnance(turf/target_turf, obj/structure/ob_ammo/warhead/ammo)
Good catch.

2024-07-18 10:53 UTC, Zonespace27 requested changes

2024-07-18 10:53 UTC, Zonespace27 commented on code/modules/admin/game_master/extra_buttons/fire_support_menu.dm
> +	var/obj/structure/mortar/abstract_mortar = new()
QDEL_NULL it on destroy

2024-07-18 10:53 UTC, Zonespace27 commented on code/modules/admin/game_master/extra_buttons/fire_support_menu.dm
> +	var/soundCooldown = FALSE
snake case

2024-07-18 10:53 UTC, Zonespace27 commented on code/modules/admin/game_master/extra_buttons/fire_support_menu.dm
> +	data["misc_ordnance_options"] = MISC_ORDNANCE
these can be static ui data

2024-07-18 10:53 UTC, Zonespace27 commented on code/modules/admin/game_master/extra_buttons/fire_support_menu.dm
> +/datum/fire_support_menu/proc/InterceptClickOn(mob/user, params, atom/object)
code doc these procs please

2024-07-18 10:53 UTC, Zonespace27 commented on code/modules/admin/game_master/extra_buttons/fire_support_menu.dm
> +	var/obj/structure/mortar/abstract_mortar = new()
code doc

2024-07-22 18:57 UTC, Zonespace27 submitted a review, later dismissed

2024-07-22 18:57 UTC, Zonespace27 commented on code/modules/admin/game_master/extra_buttons/fire_support_menu.dm
> +/datum/fire_support_menu/Destroy(force, ...)
stylistic nit: Destroy() overrides should be directly below Initialize() or the declaration of the type itself

2024-07-22 18:57 UTC, Zonespace27 commented on code/modules/admin/game_master/extra_buttons/fire_support_menu.dm
> +	. = ..()
```suggestion
	return ..()
```

2024-07-25 00:19 UTC, Doubleumc commented on code/modules/admin/game_master/extra_buttons/fire_support_menu.dm
> +		data["ordnance_options"] = ORDNANCE_OPTIONS
indentation

2024-07-25 00:20 UTC, Doubleumc commented on code/modules/admin/game_master/extra_buttons/fire_support_menu.dm
> +		data["misc_ordnance_options"] = MISC_ORDNANCE
```suggestion
	data["ordnance_options"] = ORDNANCE_OPTIONS

	data["missile_ordnance_options"] = MISSILE_ORDNANCE
	data["orbital_ordnance_options"] = ORBITAL_ORDNANCE
	data["mortar_ordnance_options"] = MORTAR_ORDNANCE
	data["misc_ordnance_options"] = MISC_ORDNANCE
```

2024-07-28 00:20 UTC, Doubleumc requested changes
These changes will allow each GM to use the panel independently of what other GMs are doing.

Beyond that, looks good to me.

2024-07-28 00:20 UTC, Doubleumc commented on code/modules/admin/game_master/extra_buttons/fire_support_menu.dm
> +	fire_support_click_intercept = FALSE
```suggestion
	fire_support_click_intercept = FALSE
	qdel(src)
```

2024-07-28 00:20 UTC, Doubleumc commented on code/modules/admin/game_master/extra_buttons/fire_support_menu.dm
> +	user.client?.click_intercept = src
```suggestion
```

2024-07-30 13:13 UTC, sunofang commented
One little thing. The fire support menu verb doesnt disappear when you de-admin. Any idea how to fix that? I'd appreciate if someone told me over discord.

2024-07-30 19:53 UTC, Doubleumc commented
> One little thing. The fire support menu verb doesnt disappear when you de-admin. Any idea how to fix that? I'd appreciate if someone told me over discord.

The reason it appears in the first place is you've added the verb to `/client/proc/add_admin_verbs()`.

To have it disappear, you'll want to also add it to `/client/proc/remove_admin_verbs()`.

2024-08-03 23:11 UTC, Doubleumc submitted a review, later dismissed

2024-08-09 05:34 UTC, merged