Smoke Code Fuckery
cmss13-devs/cmss13-pve pull request #322
Opened 2024-07-03 23:26 UTC by Ediblebomb

~~Smoke no longer makes you cough or drop things if you're wearing a gasmask.
That's it.
I'm certain nobody but me will notice this change.~~

~~okay so actually it also moves around every part of the checks for whether or not a gas affects you.~~

**kill me**

2024-07-08 09:33 UTC, AndroBetel requested changes
copied from discord

do you think you'd be able to make a blocked_by_gasmask var and move all that behavior to parent smoke class?

2024-09-13 08:21 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-09-13 23:07 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-10-28 07:01 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-11-01 18:42 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-12-07 18:07 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-12-13 02:38 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-01-21 11:49 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-01-21 22:06 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-02-20 16:40 UTC, AndroBetel requested changes

2025-02-20 16:40 UTC, AndroBetel commented on code/game/objects/effects/effect_system/smoke.dm
> +		return TRUE
does it have to return TRUE? just return should work fine shouldnt it?

2025-03-05 01:15 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-07-05 10:32 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-07-05 22:42 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-07-22 15:44 UTC, BonniePandora commented on code/game/objects/effects/effect_system/smoke.dm
> +	applied_fire_stacks = 6
Duplicated entry for /phosphorus/strong

2025-07-22 15:45 UTC, BonniePandora commented on code/game/objects/items/explosives/grenades/marines.dm
> +	LSD_gas.set_up(LSD_gas_radius, 0, get_turf(src), null)
You've removed the duration off of these

2025-07-27 18:20 UTC, BonniePandora approved these changes

2025-08-02 21:46 UTC, BonniePandora approved these changes
Messy, but tolerable.

2025-08-03 01:51 UTC, merged