Special Buck Icon
cmss13-devs/cmss13-pve pull request #324
Opened 2024-07-05 17:47 UTC by Meatstuff882

# About the pull request

Adds an icon for special buckshot shells. Thanks to Suno for helping me figure out where to define handful_state.

# Explain why it's good for the game

It allows special buckshot to be immediately distinguished from normal buckshot, in the event that both are present. It also looks pretty cool I think.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

![image](https://github.com/PvE-CMSS13/PvE-CMSS13/assets/65227917/a0fdf240-93cf-49f9-b7d0-ddbbfed1f4e7)

</details>

# Changelog

:cl:
add: Added an icon for special buckshot.
/:cl:

2024-07-05 22:24 UTC, sunofang commented on code/modules/projectiles/magazines/shotguns.dm
> +	item_state = "special"
Why define both icon and item state? Shouldnt they do the same thing?

2024-07-08 09:18 UTC, AndroBetel commented on code/modules/projectiles/magazines/shotguns.dm
> +	item_state = "special"
afaik item_state in most cases defines inhands sprites, anddd theres no changes to inhands dmi file, might have to add them or change item_state to that of buckshot box

2024-07-08 09:18 UTC, AndroBetel requested changes
see above

2024-07-18 18:57 UTC, AndroBetel approved these changes

2024-07-18 18:58 UTC, merged