Port TGUI react migration and fixes, Part 1
cmss13-devs/cmss13-pve pull request #342
Opened 2024-07-24 04:49 UTC by Doubleumc

# About the pull request

Ports various commits related to main CM's upgrade of TGUI:
https://github.com/cmss13-devs/cmss13/pull/5307
https://github.com/cmss13-devs/cmss13/pull/5435
https://github.com/cmss13-devs/cmss13/pull/5493
https://github.com/cmss13-devs/cmss13/pull/5562
https://github.com/cmss13-devs/cmss13/pull/5581
https://github.com/cmss13-devs/cmss13/pull/5649
https://github.com/cmss13-devs/cmss13/pull/5651
https://github.com/cmss13-devs/cmss13/pull/5764
https://github.com/cmss13-devs/cmss13/pull/5775
https://github.com/cmss13-devs/cmss13/pull/6196

Leaving this one for Part 2, as it is a doozy:
https://github.com/cmss13-devs/cmss13/pull/6244

After that would check for any differences in TGUI files for anything I missed.

# Explain why it's good for the game

React is a much better supported framework than Inferno. Modern TGUI has performance and functionality improvements.

# Testing Photographs and Procedure

Its too big. Gonna have to be testmerged.

# Changelog

No player facing changes.

2024-07-27 02:43 UTC, Doubleumc commented on code/modules/shuttle/shuttles/trijent_elevator.dm
> +			if(isnum(door.id)) //poddoor filler was sneaking in
Sure thing. My thinking was the real issue is it uses the `door.id` as the index for an assoc list, and a number index really throws a wrench in that. Regardless, it fixes the problem.

2024-07-27 05:38 UTC, Drulikar approved these changes
Of note, a bulk of this is my own code so take my approval with a grain of salt. Feel free to let me know if you find anything that needs tweaking though. I will port most other tgui changes I think will be useful here once this is merged so don't be scared with a big PR influx.

2024-08-01 19:52 UTC, Drulikar requested changes
Dropship equipment is not rendering correctly and as such is not interactable. Paradrop equipment for example would need to be accessed here to be used, but it cannot because the mount point is null.

![image](https://github.com/user-attachments/assets/79909dc5-7193-4967-a6e0-a7edda45ea28)
![image](https://github.com/user-attachments/assets/519db016-222b-4aad-8cd1-07b0e75d58b4)
![image](https://github.com/user-attachments/assets/387f3a5f-d0df-48d1-80bb-527ec7353e9c)

2024-08-01 23:12 UTC, Doubleumc commented
Good catch. Tested and fixed for all PvE dropships.

2024-08-03 10:16 UTC, Drulikar requested changes
All hardpoints look fixed and cas firing is fine.

Paradropping does not transition the person to the map however. It seems `/turf/open/space/transit/proc/handle_crosser(atom/movable/crosser)` is triggered but not `/turf/open/space/transit/dropship/handle_crosser(atom/movable/crosser)` so maybe the shuttles need further mapping changes to be more like pvp?

![para](https://github.com/user-attachments/assets/c8d443cd-55b1-4bc0-88eb-e7a50af9c902)

2024-08-03 18:42 UTC, Doubleumc commented
Good catch, and fixed!
![image](https://github.com/user-attachments/assets/fc981c7c-267a-484b-a79b-7bd0cb204fd3)

2024-08-04 04:08 UTC, Drulikar approved these changes
Let me know if anything else comes up and or you feel its been tested enough.

2024-08-04 05:44 UTC, Doubleumc commented
One full mission without any issues being noticed and I'll be satisfied.

2024-08-04 19:55 UTC, Doubleumc commented
I'm satisfied.

2024-08-05 05:43 UTC, merged