Round Start delayed by default
cmss13-devs/cmss13-pve pull request #351
Opened 2024-07-29 04:18 UTC by Doubleumc

# About the pull request

Round start delayed by default.

# Explain why it's good for the game

Every round is hosted by a GM and they choose when to start, not a timer.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
admin: round start delayed by default
/:cl:

2024-07-29 15:36 UTC, Drulikar requested changes

2024-07-29 15:36 UTC, Drulikar commented on code/controllers/subsystem/ticker.dm
> +	var/delay_start = TRUE
This needs to account for `#ifdef UNIT_TESTS` or something.

2024-07-29 22:47 UTC, Doubleumc commented on code/controllers/subsystem/ticker.dm
> +	var/delay_start = TRUE
Oops! That explains why the tests seemed so slow. Fixed.

2024-07-30 02:29 UTC, Drulikar approved these changes

2024-07-30 02:29 UTC, merged