Pistol changes
cmss13-devs/cmss13-pve pull request #370
Opened 2024-08-11 04:34 UTC by AmoryBlaine

- Marine vendors loses pistol ammo
- Marine vendors loses non-standard pistols
- Marine service pistol magazines added to gear lockup
- VP78 removed until redesigned/rebalance
- Various desc changes
- Various pistol audio changes
- Marine vendor no longer carries ammo
- Marine prep zone has service pistol magazines
- HG-45 Super is added to loadout

2024-08-13 18:39 UTC, mesnomer commented on code/modules/projectiles/guns/revolvers.dm
> +	desc = "A semi-automatic revolver chambered in .357 commonly issued to Colonial Marshals."
Honestly I'd change the name from "... Armoury autorevolver" to "... Armoury revolver."

Whether semi-automatic is accurate is debatable here, but "autorevolver" is just straight up inaccurate as it's a conflation with how the Mateba operates. While the Mateba did supposedly inspire the Spearhead and DOES have a reciprocating element (ie the whole dang gun from the grip up) to re-cock the hammer with every shot for full SA usage, the Spearhead lacks that element.

2024-08-13 19:33 UTC, AmoryBlaine commented on code/modules/projectiles/guns/revolvers.dm
> +	desc = "A semi-automatic revolver chambered in .357 commonly issued to Colonial Marshals."
Sure, why not

2024-08-18 19:27 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-08-27 19:23 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-08-27 23:23 UTC, Doubleumc approved these changes

2024-08-28 18:44 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-08-28 19:13 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-08-28 19:36 UTC, Doubleumc requested changes

2024-08-28 19:36 UTC, Doubleumc commented on code/modules/projectiles/guns/pistols.dm
> +	icon_state = "vp70"
There's no `vp70` in the `'icons/obj/items/weapons/guns/guns_by_faction/uscm.dmi'` file.

2024-08-28 19:36 UTC, Doubleumc commented on code/game/objects/items/storage/misc.dm
> +/obj/item/storage/box/loadout/co2_knife
Will need to repath `co2_knife` in all the maps as well:
![image](https://github.com/user-attachments/assets/855072d0-b82d-4234-a59a-4f06c8db9b09)

2024-08-28 19:38 UTC, AmoryBlaine commented on code/modules/projectiles/guns/pistols.dm
> +	icon_state = "vp70"
Was deleted in icon merge, fixed now

2024-08-28 19:40 UTC, AmoryBlaine commented on code/game/objects/items/storage/misc.dm
> +/obj/item/storage/box/loadout/co2_knife
Fixed

2024-08-28 19:51 UTC, Doubleumc approved these changes

2024-08-28 19:51 UTC, merged