Microwaved snacks
cmss13-devs/cmss13-pve pull request #371
Opened 2024-08-11 20:04 UTC by Meatstuff882

# About the pull request

Lets you microwave snacks. Updates the inspect text on these snacks to suggest microwaving them. Microwaving snacks adds 2 points of nutrition. Also adds cheese to cheeseburgers.

# Explain why it's good for the game

The food said that it didn't have a time to microwave them for. Marines should be allowed to microwave them anyways without ruining the microwave. Also adds cheese to packaged cheeseburgers because they didn't have it before.

# Testing Photographs and Procedure
![image](https://github.com/user-attachments/assets/93b432cd-6505-4b6a-8edf-e121dbef99a7)
This is what losing looks like.

</details>

# Changelog

:cl:
add: Added Microwaved Burritos, Cheeseburgers, and Hot Dogs, and recipes for these items.
balance: Packaged cheeseburger now has 2 additional nutrition from the addition of cheese.
:cl:

2024-08-21 05:49 UTC, Doubleumc submitted a review, later dismissed

2024-08-23 11:51 UTC, AndroBetel requested changes

2024-08-23 11:51 UTC, AndroBetel commented on code/datums/recipe.dm
> +/datum/recipe/packaged_burrito/proc/warm_up(obj/item/reagent_container/food/snacks/packaged_burrito/being_cooked)
copypasting this proc for 3 food types is really lazy, what you should do is create a subtype (/datum/recipe/**warmable**/burrito for example?) and make it have all the necessary procs

2024-08-23 11:51 UTC, AndroBetel commented on code/datums/recipe.dm
> +/datum/recipe/packaged_burrito/warm
why is it a subtype, exactly? parent type doesnt have any requirements for cooking too

2024-08-24 06:41 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-08-24 07:23 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-09-04 05:34 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-09-04 07:07 UTC, AndroBetel submitted a review, later dismissed

2024-09-08 02:48 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-09-10 19:39 UTC, merged