Misc PVP Flavor Text Removal
cmss13-devs/cmss13-pve pull request #374
Opened 2024-08-13 07:34 UTC by KoishiVibe

# Summary
- Sunscreen no longer contains cadmium because that's stupid. The service will take care of you because you are friggin expensive. Y'know, until you leave service. (YOUR INJURIES ARE NOT SERVICE RELATED.)
- Prepared meals are now no longer USCMC branded. Also takes a step in removing ColMarTech from existence and finding something a little better diegetically.

2024-08-13 20:42 UTC, Doubleumc commented on code/modules/client/preferences_gear.dm
>  	display_name = "USCM issue sunscreen"
```suggestion
	display_name = "Service issue sunscreen"
```
Should match the changed name in `cosmetics.dm`. Or alternatively just call it "sunscreen stick".

2024-08-13 20:45 UTC, Doubleumc commented on code/modules/client/preferences_gear.dm
> +
```suggestion
```
Note that `/obj/item/reagent_container/food/drinks/flask/canteen/empty` only exists in your canteen PR: https://github.com/cmss13-devs/cmss13-pve/pull/373
By itself, this change will cause errors.

2024-08-14 17:09 UTC, KoishiVibe commented on code/modules/client/preferences_gear.dm
> +
goddamnit why did that still-
i hate new vsc i hate new vsc i hate new vsc

2024-08-15 01:06 UTC, Doubleumc approved these changes

2024-08-15 09:10 UTC, AndroBetel requested changes

2024-08-15 09:10 UTC, AndroBetel commented on code/modules/cm_marines/equipment/gear.dm
> +	desc = "A tray of machine prepared food. Consists of weirdly grainy tofu, some spicy beans, and a sour, once-zingy sauce."
it still has the funny white flag sprite though

2024-08-15 20:43 UTC, KoishiVibe commented on code/modules/cm_marines/equipment/gear.dm
> +	desc = "A tray of machine prepared food. Consists of weirdly grainy tofu, some spicy beans, and a sour, once-zingy sauce."
true!
i should sprite an interim sprite which will be used for the next five years
:')

2025-01-03 20:46 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-01-30 01:15 UTC, closed without merging