XM43A Pulse Carbine
cmss13-devs/cmss13-pve pull request #375
Opened 2024-08-13 08:03 UTC by KoishiVibe

# Summary
- Compact cut down M41A. No underbarrels, fast handling, worse firing. Great for close defense. Less modular.

2024-08-17 06:20 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-08-29 04:33 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-09-05 14:39 UTC, KoishiVibe commented
soon...

2024-09-13 08:21 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-09-16 03:46 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-10-23 20:35 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-07-03 16:52 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-07-04 19:34 UTC, BonniePandora requested changes
Not personally a fan of the sprite, it looks like someone put an M41A into a hydraulic press. Gives off unbullpupped L22 carbine vibes, without the VFG that thing has to make wielding it remotely feasible & comfortable

2025-07-04 19:34 UTC, BonniePandora commented on code/modules/cm_marines/equipment/guncases.dm
> +	desc = "Contains an unloaded XM43 pulse carbine and three 99 round clips."
_**CLIPS**_

2025-07-04 19:34 UTC, BonniePandora commented on code/modules/cm_marines/equipment/guncases.dm
> +	new /obj/item/ammo_magazine/rifle/m41aMK1(src)
Says it holds 3 mags, has _space_ for four items total, yet only contains 2 spare mags

2025-07-04 19:34 UTC, BonniePandora commented on code/modules/projectiles/guns/rifles.dm
> +	)
Missing comma at the end of the list
Also there's **two** `starting_attachment_types` lists defined on the item?

2025-07-05 21:48 UTC, KoishiVibe commented on code/modules/cm_marines/equipment/guncases.dm
> +	desc = "Contains an unloaded XM43 pulse carbine and three 99 round clips."
clips
:D

2025-07-05 21:49 UTC, KoishiVibe commented on code/modules/cm_marines/equipment/guncases.dm
> +	new /obj/item/ammo_magazine/rifle/m41aMK1(src)
Ah, ten months ago work. Classic.
Got it.

2025-07-05 21:50 UTC, KoishiVibe commented on code/modules/projectiles/guns/rifles.dm
> +	)
Oh right. Was trying to match formats.... *sigh.

2025-07-06 01:44 UTC, KoishiVibe commented
> Not personally a fan of the sprite, it looks like someone put an M41A into a hydraulic press. Gives off unbullpupped L22 carbine vibes, without the VFG that thing has to make wielding it remotely feasible & comfortable

Unfortunately there isn't much I can do to express how chopped down this is compared to the concept art. The original sprite is pretty squimshed already rip
There's a little angled grip where the grenade launcher trigger group is fwiw.

2025-07-10 23:25 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-08-03 03:37 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-08-07 06:00 UTC, cm13-github commented
<!-- tgs_test_merge_comment -->
## Test merge deployment history:

<details><summary>Test Merge Deployed @ 08/07/2025 05:59:43 +00:00:</summary>

##### Server Instance
PVECM: Red

##### Merged By
MessageCypher

##### Revision
Origin: ff709d109d6117a4a42bc9541699d4827a947ad9
Pull Request: ba21ee1405cf93e957ec633212510782ecf5efcd
Server: 382e70a38666baf7842f51587a824bb02b581f1c
</details>
<details><summary>Test Merge Removed @ 08/07/2025 20:47:39 +00:00:</summary>

##### Server Instance
PVECM: Red
</details>

2025-08-18 18:11 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-08-19 22:13 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-08-23 19:11 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-09-02 02:00 UTC, Drulikar commented
If you wish to pursue this after modularization, you will need to reopen it and rework it to be a modular way after modularization is complete. It may also be something to explore on upstream instead.

2025-09-02 02:00 UTC, closed without merging