10x28 changes
cmss13-devs/cmss13-pve pull request #376
Opened 2024-08-14 23:54 UTC by AmoryBlaine

- Damage multipliers removed from most rifles
- M4RA, M56 Smartgun, Type 71, Type 71c, PKP all share the same ammo type, 10x28 with a higher base damage than standard ammo.
- UPP given unique 10x31 ammo that is the same stats wise as 10x28.
- Updates mapless M4RA variant icons to match M41A palette

2024-08-15 00:30 UTC, private-tristan commented on code/modules/projectiles/magazines/rifles.dm
> +	desc = "A magazine of armor-piercing 10x28mm rounds for use in the M4RA battle rifle. Holds an additional 10 rounds, up to 35."
```suggestion
	desc = "A magazine of armor-piercing 10x28mm rounds for use in the M4RA battle rifle. Holds an additional 10 rounds, up to 40."
```

2024-08-18 19:38 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-08-19 07:47 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-08-19 08:33 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-08-20 02:57 UTC, GriffinMan4455 commented
SG's feel fucking awesome, I'm loving this change, especially combined with the SG Belt PR, though I think it'd be nice if the locker had three drums in total, if only so that SG's have a choice of having an ammobearer for just-in-case, or forgoing it in order to have a more customizable loadout  
If this were to be merged alongside the sidearm overhaul I'd pog, because as it stands our sidearms are kinda like...eh? Revolver's fun for stun, and it helped me save the Corpsman, but otherwise they chew through a ton of ammo (which is a lot of loadout space) in exchange for not doing a lot, especially with how low SG's are on ammo now.
Sadly I can't speak for how this affects RFN, but from that op they looked fine, at least.

2024-08-24 22:03 UTC, private-tristan commented on code/datums/ammo/bullet/rifle.dm
> +	name = "armor-piercing 10x28 bullet"
```suggestion
	name = "high explosive armor-piercing 10x28 bullet"
```

2024-08-28 18:44 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-08-30 07:11 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-09-07 02:08 UTC, Doubleumc requested changes
> Missing icon_state for /obj/item/attachable/uppsmartbarrel in 'icons/obj/items/weapons/guns/attachments/barrel.dmi'.

![image](https://github.com/user-attachments/assets/813d0725-5da8-4e3b-83fc-f55f27303ac8)
https://github.com/cmss13-devs/cmss13-pve/actions/runs/10650509523/job/29521976191?pr=376

2024-09-08 01:16 UTC, Doubleumc commented on code/modules/projectiles/guns/smartgun.dm
> + */
```suggestion
```
Still need this commented out bit?

2024-09-08 01:17 UTC, AmoryBlaine commented on code/modules/projectiles/guns/smartgun.dm
> + */
Only until I copypaste it into a notepad in five seconds

2024-09-08 01:30 UTC, Doubleumc approved these changes

2024-09-10 19:37 UTC, merged