Cryo loadout changes + locker stuff
cmss13-devs/cmss13-pve pull request #378
Opened 2024-08-15 04:02 UTC by DexterDude

Makes it so the Platoon Commander does not start equipped anymore. I assume this was the case because rounds were much quicker in the olden days and they had to go to their office to get their fax quick. This change promotes platoon commanders eating with their marines.
Removes satchels on spawn for all cryo presets. Now that loadout items spawn in lockers, there's no need for satchels.
Removes un-needed weapons from platoon sergeant lockers. Considering they gear up with their marines, they don't need it. UPP platsarge guns stay because they don't gear up with everyone else.
Kills squad sergeant snowflake helmets. They kinda look ugly and aren't needed, I've kept the platoon sergeant helmet so he remains distinct.

2024-08-15 08:37 UTC, AndroBetel requested changes

2024-08-15 08:37 UTC, AndroBetel commented on code/modules/gear_presets/uscm_ship.dm
> +/datum/equipment_preset/uscm_ship/so/load_status(mob/living/carbon/human/new_human)
these two proc definitions can be easily put as one

2024-08-15 08:37 UTC, AndroBetel commented on code/modules/gear_presets/uscm_ship.dm
> +/datum/equipment_preset/uscm_ship/so/upp/load_status(mob/living/carbon/human/new_human)
unneeded, inherits the behavior from parent class

2024-08-20 17:35 UTC, AndroBetel approved these changes

2024-08-23 12:13 UTC, AndroBetel requested changes
i got ahead of myself actually...

2024-08-23 12:13 UTC, AndroBetel commented on code/modules/gear_presets/uscm_ship.dm
> +/datum/equipment_preset/uscm_ship/so/equipped
lt is now naked in lobby... fail. 
![image](https://github.com/user-attachments/assets/66357760-888f-4c04-a99a-f96f113f2b9d)

2024-08-23 12:13 UTC, AndroBetel commented on code/modules/gear_presets/uscm.dm
> -/datum/equipment_preset/uscm/sg/full
why is this being removed....

2024-08-23 15:06 UTC, DexterDude commented on code/modules/gear_presets/uscm.dm
> -/datum/equipment_preset/uscm/sg/full
it doesnt do anything for the most part, all it did was make it so when you spawned a naked sg it wojld sometimes spawn an equipped marine anyway

2024-08-28 19:53 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-08-29 18:58 UTC, DexterDude commented on code/modules/gear_presets/uscm_ship.dm
> +/datum/equipment_preset/uscm_ship/so/equipped
fail

2024-09-03 22:19 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-09-03 22:30 UTC, AndroBetel approved these changes

2024-09-03 22:30 UTC, merged