LSD Returns
cmss13-devs/cmss13-pve pull request #379
Opened 2024-08-15 07:22 UTC by KoishiVibe

# Summary
- Mindbreaker is removed. 
- LSD comes back for REAL roleplayers.
- LSD is now under name diethylamide.

2024-08-15 08:33 UTC, AndroBetel requested changes

2024-08-15 08:33 UTC, AndroBetel commented on code/modules/reagents/chemistry_reagents/toxin.dm
> +	name = "lysergic acid diethylamide"
name should be formatted as any other reagent

2024-08-15 20:41 UTC, KoishiVibe commented on code/modules/reagents/chemistry_reagents/toxin.dm
> +	name = "lysergic acid diethylamide"
i saw most of the things were set up as just one word and such and i thought lysergic acid wasnt super necessary to include

2024-08-16 19:33 UTC, Doubleumc commented on code/game/objects/items/reagent_containers/food/drinks.dm
> +
```suggestion
```

2024-08-17 06:20 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-08-21 01:49 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-08-24 01:58 UTC, Doubleumc commented on code/modules/reagents/chemistry_reagents/toxin.dm
> +	name = "lysergic acid diethylamide"
Prefer for this to be typed as `/datum/reagent/toxin/lsd` or similar. People understand what LSD means. Diethylamide is much less clear what it does.

2024-09-04 01:26 UTC, Doubleumc requested changes
Please rename the reagent as per the previous review:
> Prefer for this to be typed as `/datum/reagent/toxin/lsd` or similar. People understand what LSD means. Diethylamide is much less clear what it does.

2024-09-05 14:30 UTC, KoishiVibe commented on code/modules/reagents/chemistry_reagents/toxin.dm
> +	name = "lysergic acid diethylamide"
oh i see

2024-09-06 16:18 UTC, Doubleumc requested changes
This is more what I had in mind by changing its identifier to `lsd`.

Otherwise, code good.

2024-09-06 16:18 UTC, Doubleumc commented on code/game/objects/items/reagent_containers/syringes.dm
> +	reagents.add_reagent("diethylamide",  5)
```suggestion
	reagents.add_reagent("lsd",  5)
```

2024-09-06 16:18 UTC, Doubleumc commented on code/modules/hydroponics/seed_datums.dm
> +			"diethylamide",
```suggestion
			"lsd",
```

2024-09-06 16:18 UTC, Doubleumc commented on code/modules/reagents/chemistry_properties/prop_neutral.dm
> +	M.reagents.remove_reagent("diethylamide", 5)
```suggestion
	M.reagents.remove_reagent("lsd", 5)
```

2024-09-06 16:18 UTC, Doubleumc commented on code/modules/reagents/chemistry_reactions/medical.dm
> +	required_reagents = list("diethylamide" = 1, "hydrogen" = 1)
```suggestion
	required_reagents = list("lsd" = 1, "hydrogen" = 1)
```

2024-09-06 16:18 UTC, Doubleumc commented on code/modules/reagents/chemistry_reactions/medical.dm
> +	required_reagents = list("diethylamide" = 1, "carbon" = 1)
```suggestion
	required_reagents = list("lsd" = 1, "carbon" = 1)
```

2024-09-06 16:18 UTC, Doubleumc commented on code/modules/reagents/chemistry_reactions/medical.dm
> +	required_reagents = list("diethylamide" = 1, "oxygen" = 1, "inaprovaline" = 1)
```suggestion
	required_reagents = list("lsd" = 1, "oxygen" = 1, "inaprovaline" = 1)
```

2024-09-06 16:18 UTC, Doubleumc commented on code/modules/reagents/chemistry_reactions/other.dm
> +	result = "diethylamide"
```suggestion
/datum/chemical_reaction/lsd
	name = "Lysergic Acid Diethylamide"
	id = "lsd"
	result = "lsd"
```

2024-09-06 16:18 UTC, Doubleumc commented on code/modules/reagents/chemistry_reagents/toxin.dm
> +	id = "diethylamide"
```suggestion
	id = "lsd"
```

2025-01-30 01:15 UTC, closed without merging