UPP Loadout overhaul
cmss13-devs/cmss13-pve pull request #385
Opened 2024-08-17 01:08 UTC by AmoryBlaine

- Replaces UPP "Conscript" with UPP "Colonial Militiamen"
- Equipped versions of all UPP Platoon roles
- Removes excess Commando variants, we don't deploy or use them like a functional PvP squad so why have DS variants and medics among them.
- Conscripts and lowest rank of UPP Platoon members is now "Ryadovoy".

2024-08-17 06:20 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-08-18 04:47 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-08-23 20:18 UTC, AndroBetel requested changes
please make sure all the special equipment is still available, upps still need some kind of flamer (give them underbarrel flamers?)

2024-08-23 20:18 UTC, AndroBetel commented on code/modules/clothing/head/helmet.dm
> +/* /obj/item/clothing/head/helmet/marine/veteran/UPP/heavy
why is this commented out?

2024-08-23 20:18 UTC, AndroBetel commented on code/modules/clothing/suits/marine_armor.dm
> -	flags_armor_protection = BODY_FLAG_CHEST|BODY_FLAG_GROIN|BODY_FLAG_ARMS|BODY_FLAG_LEGS
thats a massive change that is undocumented in pr body, how is it related to UPP overhaul even?

2024-08-23 20:18 UTC, AndroBetel commented on code/modules/gear_presets/upp.dm
> +	var/maybejacket = prob(100) ? pick(/obj/item/clothing/suit/storage/marine/faction/UPP/jacket, /obj/item/clothing/suit/storage/marine/veteran/lamp) : null
why prob 100

2024-08-23 20:18 UTC, AndroBetel commented on code/modules/gear_presets/upp.dm
> +/* 	var/datum/preferences/A = new()
remove dont comment

2024-08-23 20:24 UTC, AmoryBlaine commented on code/modules/clothing/head/helmet.dm
> +/* /obj/item/clothing/head/helmet/marine/veteran/UPP/heavy
WIP

2024-08-23 20:24 UTC, AmoryBlaine commented on code/modules/clothing/suits/marine_armor.dm
> -	flags_armor_protection = BODY_FLAG_CHEST|BODY_FLAG_GROIN|BODY_FLAG_ARMS|BODY_FLAG_LEGS
Again, WIP

2024-08-23 20:25 UTC, AmoryBlaine commented on code/modules/gear_presets/upp.dm
> +	var/maybejacket = prob(100) ? pick(/obj/item/clothing/suit/storage/marine/faction/UPP/jacket, /obj/item/clothing/suit/storage/marine/veteran/lamp) : null
Repurposed the existing code but made prob 100 instead of 70 so it always spawns a jacket. I'll change it to var/random_gear = rand(1,2) if that also works

2024-08-23 20:29 UTC, AmoryBlaine commented on code/modules/gear_presets/upp.dm
> +/* 	var/datum/preferences/A = new()
That was done during testing to see how I could put names on the USCM nested UPP roles. Will revert, thanks for pointing it out.

2024-08-23 20:43 UTC, AmoryBlaine commented
> please make sure all the special equipment is still available, upps still need some kind of flamer (give them underbarrel flamers?)

Work in progress. As you and I already discussed, the Type 23 will be getting Dragonsbreath- the Type 23 now has shotgun ammo boxes, and shotgun boxes have been updated to fit in bags since it's not easy to reload with them on the run anyways. Sadly, the buffs to the Type 23 are atomized inside the shotgun PR :') so you're fucked out of actually functioning properly ammo and a reasonable firerate until that gets added.

They need unique incinerators, so I am thinking of implementing Aden's old incinerator sprites from when you first added playable UPP. It will probably function like a less powerful MOPP squad incinerator. The grenades have been buffed already and are provided in 5 grenade packages. I didn't make a seperate HEFA/HEDP system, I just lowered total shrapnel while buffing power to the HEDP. Probably gonna lower shrap a bit. UGL I agree, but not a priority given their damage output with their rifles rn is incredibly high.

2024-08-24 19:59 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-08-28 20:18 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-09-03 22:32 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-09-06 01:13 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-09-07 01:52 UTC, Doubleumc requested changes
Only real obstacle is this (unintentionally) reverting changed sprites.

Other than that, code good.

2024-09-07 01:52 UTC, Doubleumc commented on code/game/machinery/vending/vendor_types/crew/commanding_officer.dm
> +		list("Commanding Officer's Gloves", 0, /obj/item/clothing/gloves/marine, MARINE_CAN_BUY_GLOVES, VENDOR_ITEM_MANDATORY),
```suggestion
		list("Combat Gloves", 0, /obj/item/clothing/gloves/marine, MARINE_CAN_BUY_GLOVES, VENDOR_ITEM_MANDATORY),
```
Since they're just normal gloves now, ought to label them as such.

2024-09-07 01:52 UTC, Doubleumc commented on code/game/objects/items/cards_ids.dm
> +	desc = "A fallen serviceman's information dog tag."
```suggestion
	desc = "A fallen servicemember's information dog tag."
```
Gender neutral to match the 50/50 M/F ratio.

2024-09-07 01:52 UTC, Doubleumc commented on icons/mob/humans/onmob/head_1.dmi
Reverts sprites from https://github.com/cmss13-devs/cmss13-pve/pull/426 likely missed when updating from master.

2024-09-07 01:52 UTC, Doubleumc commented on icons/obj/items/clothing/cm_hats.dmi
Reverts sprites from https://github.com/cmss13-devs/cmss13-pve/pull/426 likely missed when updating from master.

2024-09-07 01:52 UTC, Doubleumc commented on icons/mob/humans/onmob/suit_1.dmi
Reverts sprites from https://github.com/cmss13-devs/cmss13-pve/pull/414 likely missed when updating from master.

2024-09-07 01:52 UTC, Doubleumc commented on icons/mob/humans/onmob/uniform_0.dmi
Reverts sprites from https://github.com/cmss13-devs/cmss13-pve/pull/414 likely missed when updating from master.

2024-09-07 01:52 UTC, Doubleumc commented on icons/obj/items/clothing/uniforms.dmi
Reverts sprites from https://github.com/cmss13-devs/cmss13-pve/pull/414 likely missed when updating from master.

2024-09-08 19:55 UTC, Doubleumc submitted a review, later dismissed
Its still reverting headgear sprites from https://github.com/cmss13-devs/cmss13-pve/pull/426

Other than that, code good.

2024-09-08 19:55 UTC, Doubleumc commented on icons/obj/items/clothing/cm_hats.dmi
Reverts sprites from https://github.com/cmss13-devs/cmss13-pve/pull/426 likely missed when updating from master.

2024-09-08 19:55 UTC, Doubleumc commented on icons/mob/humans/onmob/head_1.dmi
Reverts sprites from https://github.com/cmss13-devs/cmss13-pve/pull/426 likely missed when updating from master.

2024-09-09 21:33 UTC, AndroBetel requested changes
if you were making this kind of pr on pvp maintainers there would probably close this one because of all the out-of-scope changes that dont directly affect what youre changing so please dont do that in the future as it makes it a lot harder to review

2024-09-09 21:33 UTC, AndroBetel commented on code/game/machinery/vending/vendor_types/squad_prep/squad_prep.dm
> +		list("6b82 Combat Helmet", round(scale * 15), /obj/item/clothing/head/helmet/marine/veteran/UPP/naval/alt, VENDOR_ITEM_REGULAR),
same name?

2024-09-09 21:33 UTC, AndroBetel commented on code/game/objects/items/storage/pouch.dm
> +	name = "etool pouch"
```suggestion
	name = "entrenching tool pouch"
```

2024-09-09 21:33 UTC, AndroBetel commented on code/game/objects/items/tools/shovel_tools.dm
> +/obj/item/tool/shovel/etoolupp
should be a subtype of the other etool

2024-09-09 21:33 UTC, AndroBetel commented on code/modules/clothing/head/helmet.dm
> +	name = "\improper 6b82 combat helmet"
```suggestion
	name = "\improper 6B82 helmet"
```
most helmets are combat arent they...

2024-09-09 21:33 UTC, AndroBetel commented on code/modules/clothing/head/helmet.dm
> +/obj/item/clothing/head/helmet/marine/veteran/UPP/naval/alt
maybe add this as helmet accessory? have it be like a different helmet cover or something

2024-09-09 21:33 UTC, AndroBetel commented on code/modules/clothing/head/helmet.dm
> +	desc = "Standard issue peaked cap of the People's Police."
militsiya?

2024-09-09 21:33 UTC, AndroBetel commented on code/modules/clothing/shoes/marine_shoes.dm
> +	icon_state = "marine"
inherits this from parent

2024-09-09 21:33 UTC, AndroBetel commented on code/modules/clothing/suits/marine_armor.dm
> -	flags_armor_protection = BODY_FLAG_CHEST|BODY_FLAG_GROIN|BODY_FLAG_ARMS|BODY_FLAG_LEGS
still wip?

2024-09-09 21:33 UTC, AndroBetel commented on code/modules/clothing/suits/marine_coat.dm
> +	desc = "A blue-grey bomber jacket worn by People's Police constables."
militsiya?

2024-09-10 05:13 UTC, AmoryBlaine commented on code/modules/clothing/suits/marine_armor.dm
> -	flags_armor_protection = BODY_FLAG_CHEST|BODY_FLAG_GROIN|BODY_FLAG_ARMS|BODY_FLAG_LEGS
I'm reverting it here, but it's intended to correlate with the UPP change that's the same. I'll just do it again in the USCM specific one since it's not resulted in increased deaths or something tmk

2024-09-10 05:54 UTC, AmoryBlaine commented on code/modules/clothing/head/helmet.dm
> +	name = "\improper 6b82 combat helmet"
I hate you...

2024-09-10 05:54 UTC, AmoryBlaine commented on code/modules/clothing/head/helmet.dm
> +/obj/item/clothing/head/helmet/marine/veteran/UPP/naval/alt
The way that helmet works is that's the helmet though, it's 3 pieces of metal in a liner system

2024-09-10 19:41 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-09-10 21:58 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-09-13 08:21 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-09-13 15:41 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-09-20 06:56 UTC, Doubleumc requested changes
Be sure to complete Andro's feedback as well: https://github.com/cmss13-devs/cmss13-pve/pull/385#pullrequestreview-2290960744

2024-09-20 06:56 UTC, Doubleumc commented on code/modules/gear_presets/upp.dm
> +			new_human.equip_to_slot_or_del(new /obj/item/clothing/accessory/red(new_human), WEAR_ACCESSORY)
No `if(5)` ?

2024-09-20 06:56 UTC, Doubleumc commented on code/modules/gear_presets/upp.dm
> +			new_human.equip_to_slot_or_del(new /obj/item/clothing/accessory/red(new_human), WEAR_ACCESSORY)
No `if(5)` ?

2024-09-20 06:56 UTC, Doubleumc commented on code/modules/projectiles/ammo_boxes/magazine_boxes.dm
> +	overlay_gun_type = "_m41"
What is the purpose of this change?

2024-09-20 06:56 UTC, Doubleumc commented on code/game/objects/items/tools/misc_tools.dm
What is the purpose of removing the names of WY pens?

2024-09-20 06:56 UTC, Doubleumc commented on code/game/machinery/vending/vendor_types/requisitions.dm
> -		list("Marine Black Combat Gloves", 40, /obj/item/clothing/gloves/marine/black, VENDOR_ITEM_REGULAR),
You're reverting massive changes in this file for no reason. Merge gone wrong perhaps? As far as I can tell removing the "Marine Black Combat Gloves" line was the only thing you meant to do.

2024-09-20 06:56 UTC, Doubleumc commented on code/game/machinery/vending/vendor_types/squad_prep/squad_medic.dm
> +		list("Sterile Gloves", 0, /obj/item/clothing/gloves/latex, MARINE_CAN_BUY_KIT, VENDOR_ITEM_REGULAR),
You're reverting changes in this file for no reason. Merge gone wrong perhaps? As far as I can tell replacing "Combat Sterile Gloves" with "Sterile Gloves" and renaming UPP armors were the only thing you meant to do.

2024-09-20 06:56 UTC, Doubleumc commented on code/game/machinery/vending/vendor_types/squad_prep/squad_prep.dm
> -		list("Marine Black Combat Gloves", floor(scale * 15), /obj/item/clothing/gloves/marine/black, VENDOR_ITEM_REGULAR),
You're reverting changes in this file for no reason. Merge gone wrong perhaps? ~~As far as I can tell removing "Marine Black Combat Gloves" was the only thing you meant to do.~~ There's several things that could be intentional, give it another pass and make sure you're only changing what you intended to change.

2024-09-20 06:56 UTC, Doubleumc commented on code/game/objects/items/storage/misc.dm
> +
You're reverting changes in this file for no reason. Merge gone wrong perhaps? As far as I can tell renaming the T73 and the Zhnk72 were the only things you meant to do.

2024-09-20 06:56 UTC, Doubleumc commented on code/game/objects/items/tools/shovel_tools.dm
> +	desc = "A serviceman's best friend. Dually useful for digging foxholes and bashing in heads. Folds in half for easier storage."
```suggestion
	desc = "A marine's best friend. Dually useful for digging foxholes and bashing in heads. Folds in half for easier storage."
```
Since its a USCM tool, can be more specific with "marine" instead of "serviceman". Alternatively, "servicemember".

2024-09-20 06:56 UTC, Doubleumc commented on icons/obj/items/weapons/guns/ammo_boxes/boxes_and_lids.dmi
File changed, but no changed icons.

2024-09-20 06:56 UTC, Doubleumc commented on icons/obj/items/weapons/grenade.dmi
File changed, but no changed icons.

2024-09-20 06:56 UTC, Doubleumc commented on icons/mob/humans/onmob/uniform_1.dmi
File changed, but no changed icons.

2024-09-20 06:59 UTC, AmoryBlaine commented on code/modules/gear_presets/upp.dm
> +			new_human.equip_to_slot_or_del(new /obj/item/clothing/accessory/red(new_human), WEAR_ACCESSORY)
Yeah I cut it out and forgot to change the count.

2024-09-20 07:00 UTC, AmoryBlaine commented on code/game/objects/items/tools/misc_tools.dm
I use them on the Chapaev and Ravdonika maps and in the MSS Agent's gear preset.

2024-09-20 07:00 UTC, AmoryBlaine commented on code/game/machinery/vending/vendor_types/requisitions.dm
> -		list("Marine Black Combat Gloves", 40, /obj/item/clothing/gloves/marine/black, VENDOR_ITEM_REGULAR),
Yeah, the merge thing fucked me up badly.

2024-09-20 07:02 UTC, AmoryBlaine commented on code/modules/projectiles/ammo_boxes/magazine_boxes.dm
> +	overlay_gun_type = "_m41"
Yeah, it's not the Mk1 here, it's THE M41. We removed most mentions and I was already touching the file for the t73 boxes.

2024-09-20 07:03 UTC, AmoryBlaine commented on icons/mob/humans/onmob/uniform_1.dmi
Are you sure? I ran it today and it definitely had all the changed sprites loaded

2024-09-20 07:23 UTC, AmoryBlaine commented
> Be sure to complete Andro's feedback as well: [#385 (review)](https://github.com/cmss13-devs/cmss13-pve/pull/385#pullrequestreview-2290960744)

Note and will ideally not have to change so much shit in the USCM overhaul anyways, since it's mostly just aesthetic stuff and a lot of it is here already.

2024-09-22 00:05 UTC, Doubleumc commented on code/game/machinery/vending/vendor_types/requisitions.dm
> -		list("Marine Black Combat Gloves", 40, /obj/item/clothing/gloves/marine/black, VENDOR_ITEM_REGULAR),
Still reverting a lot. I suggest separating your changes, replacing this file with current master, and then incorporating your changes again.

2024-09-22 00:06 UTC, Doubleumc commented on code/game/objects/items/storage/misc.dm
> +
Still reverting a lot. I suggest separating your changes, replacing this file with current master, and then incorporating your changes again.

2024-09-22 06:29 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-09-22 18:22 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-09-24 20:13 UTC, Doubleumc requested changes

2024-09-24 20:13 UTC, Doubleumc commented on code/modules/gear_presets/synths.dm
> +	joe_type = SYNTH_WORKING_JOE
```suggestion
	joe_type = SYNTH_HAZARD_JOE
```
Assuming the only thing you wanted to do was change their emote sounds, this is unnecessary since you already changed their `emote_panel_type`.

2024-09-24 20:13 UTC, Doubleumc commented on code/modules/mob/living/carbon/human/species/working_joe/_species.dm
> +	emote_panel_type = /datum/joe_emote_panel
Unrelated to UPP, really ought to be its own PR.

2024-09-24 20:13 UTC, Doubleumc commented on code/modules/clothing/shoes/marine_shoes.dm
> -/obj/item/clothing/shoes/marine/brown
Deleting `.../shoes/marine/brown` intentional?

2024-09-24 20:13 UTC, Doubleumc commented on code/modules/clothing/shoes/marine_shoes.dm
>  	spawn_item_type = /obj/item/attachable/bayonet/upp
The way this is defined, these are standard USCM boots that happen to have a UPP knife in them. Is that what you wanted?

2024-09-24 20:13 UTC, Doubleumc commented on code/modules/projectiles/ammo_boxes/magazine_boxes.dm
> +	overlay_gun_type = "_m41"
Unrelated to UPP, really ought to be its own PR.

2024-09-28 12:19 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-09-28 17:06 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-09-30 00:39 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-10-02 23:02 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-10-07 05:32 UTC, Doubleumc commented
Reminder you have unresolved reviews:
https://github.com/cmss13-devs/cmss13-pve/pull/385#pullrequestreview-2290960744
https://github.com/cmss13-devs/cmss13-pve/pull/385#pullrequestreview-2317346810

Otherwise looks good.

2024-10-07 05:40 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-10-08 00:53 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-10-13 01:21 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-10-13 01:23 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-10-23 10:11 UTC, Doubleumc approved these changes

2024-10-23 14:20 UTC, AndroBetel submitted a review, later dismissed

2024-10-23 20:06 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-10-23 23:08 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-10-24 00:03 UTC, Doubleumc approved these changes

2024-10-24 17:27 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-10-24 18:34 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-10-28 07:00 UTC, merged