Helmet Camo Covers
cmss13-devs/cmss13-pve pull request #413
Opened 2024-08-25 16:35 UTC by Max-023

# About the pull request
Adds a camouflage cover that can be put on helmets used by the USCM, camouflage based on that of the uniform of the Marine.

![image](https://github.com/user-attachments/assets/d4b3004a-e8af-441c-b612-cf8cb149299e)

# Explain why it's good for the game
Just an additional flair item based on the actual camouflage cover seen in the move on some Marines.

# Testing Photographs and Procedure
N/A

# Changelog

:cl:
add: Helmet cover item, added to the squad prep vendor
imageadd: Helmet cover sprites
/:cl:

2024-08-25 18:28 UTC, AndroBetel requested changes

2024-08-25 18:28 UTC, AndroBetel commented on code/game/machinery/vending/vendor_types/squad_prep/squad_prep.dm
> -		list("M5 Integrated Gas Mask", round(scale * 10), /obj/item/prop/helmetgarb/helmet_gasmask, VENDOR_ITEM_REGULAR),
?

2024-08-25 19:13 UTC, Max-023 commented on code/game/machinery/vending/vendor_types/squad_prep/squad_prep.dm
> -		list("M5 Integrated Gas Mask", round(scale * 10), /obj/item/prop/helmetgarb/helmet_gasmask, VENDOR_ITEM_REGULAR),
They are already in the mask section from my last PR, I just forgot to remove them from this section. Otherwise it's a duplicate entry.

2024-08-26 13:28 UTC, AndroBetel approved these changes

2024-08-26 20:42 UTC, merged