Muted Janitorial Carts and Cleaner bottles
cmss13-devs/cmss13-pve pull request #423
Opened 2024-08-30 01:04 UTC by AmoryBlaine

- Blue and tan cleaner bottle icons and onmobs
- Blue and brown janitorial carts

2024-09-02 22:42 UTC, Doubleumc requested changes

2024-09-02 22:42 UTC, Doubleumc commented on code/game/objects/structures/janicart.dm
> +	icon_state = "cart_brown"
`/obj/structure/janitorialcart` is already defined as the blue cart. You're redefining the same thing here which overwrites that original definition, so *all* janitorial carts would be brown. Instead make a subtype, like this:
```suggestion
/obj/structure/janitorialcart/brown
	desc = "A brown janitorial cart that has space for water, mops, signs, and trash bags."
	icon_state = "cart_brown"
```

2024-09-04 03:34 UTC, Doubleumc approved these changes

2024-09-10 19:41 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-09-10 19:58 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-09-10 20:58 UTC, merged