Adds the M579 Aerial-Defence System Carrier (AKA, the AA-APC, or LAV-AD of the future)
cmss13-devs/cmss13-pve pull request #429
Opened 2024-09-03 02:56 UTC by BonniePandora

# About the pull request

Adds a new variant of the APC to the game for GM's to utilise as they see fit, and also offers a flavourful way for marines to down airborne threats such as enemy CAS (via GM intervention and such)

Very much a 'glass cannon' kind of vehicle, capable of dealing a lot of hurt but can't take much punishment in return. Adjustments to damage/range for the weapons is more than doable

Still awaiting final sprites for the weapons and possibly chassis too, please don't merge until they're finished.

# Explain why it's good for the game

More things = gooder
Drew inspiration from the tech manual's listed variant of the basic APC, thought it would be neat to add, was a fun code project to work on.
Gives GM's more options for support assets to use as and when they want to too.

# Testing Photographs and Procedure
Tested each step of the way on a local server to ensure it worked, no issues besides placeholder sprites for much of the hardpoints.
<details>
<summary>Screenshots & Videos</summary>

![image 1](https://github.com/user-attachments/assets/7c46d275-d745-4165-87c1-9f3e9af9b382)

![image 1](https://github.com/user-attachments/assets/f4e144ca-9cc9-45b4-b6db-73be42c8c98d)

</details>

# Changelog

:cl:
add: added the M579 ADS-C vehicle
add: added the new weapons, ammo, ammo-storage and viewport console for the above
fix: fixed a typo in the vehicles.dm file whilst I was at it
imageadd: new turf icon added for ADS-C interior
mapadd: added new interior for the M579
/:cl:

2024-09-07 02:21 UTC, Doubleumc requested changes
Code good. Just want to see the hardpoint sprites moved to the appropriate file and for it to be tested in at least one operation.

2024-09-07 02:21 UTC, Doubleumc commented on icons/obj/vehicles/movieapc.dmi
Since this is a subtype of the apc, not the movie apc, it should be in `icons/obj/vehicles/apc.dmi` instead.

2024-09-13 10:49 UTC, BonniePandora commented
Swapping to a draft until I can get the finished sprites, will address the merge-conflicts & requested changes when that's happened.

2024-09-22 19:24 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-09-23 10:24 UTC, BonniePandora commented on icons/obj/vehicles/movieapc.dmi
This has been addressed, made the AA APC a sub-type of the movielike one instead

2024-09-23 21:46 UTC, BonniePandora commented on maps/interiors/apc_aa.dmm
Provided the remaining checks pass, these changes should be in now.

2024-09-24 01:30 UTC, Doubleumc approved these changes

2024-09-27 15:03 UTC, BonniePandora commented
Sprites are finished at last, ready for a possible TM & review.

2024-09-27 22:20 UTC, AndroBetel requested changes

2024-09-27 22:20 UTC, AndroBetel commented on code/game/objects/structures/gun_rack.dm
> +	desc = "A small compartment that stores ammunition for the vehicle's VLS-array ."
```suggestion
	desc = "A small compartment that stores ammunition for the vehicle's VLS-array."
```

2024-09-27 22:20 UTC, AndroBetel commented on code/modules/vehicles/apc/apc_aa.dm
> +/obj/vehicle/multitile/apc/movie/aa/add_seated_verbs(mob/living/M, seat)
inherited from movie apc, not needed

2024-09-27 22:20 UTC, AndroBetel commented on code/modules/vehicles/apc/apc_aa.dm
> +/obj/vehicle/multitile/apc/movie/aa/remove_seated_verbs(mob/living/M, seat)
ditto

2024-09-27 22:20 UTC, AndroBetel commented on code/modules/vehicles/apc/apc_aa.dm
> +/obj/vehicle/multitile/apc/movie/aa/set_muzzle_offsets(obj/item/hardpoint/HP)
ditto? should check if these are correct

2024-09-27 23:29 UTC, BonniePandora commented on code/game/objects/structures/gun_rack.dm
> +	desc = "A small compartment that stores ammunition for the vehicle's VLS-array ."
Fixed

2024-09-27 23:30 UTC, BonniePandora commented on code/modules/vehicles/apc/apc_aa.dm
> +/obj/vehicle/multitile/apc/movie/aa/add_seated_verbs(mob/living/M, seat)
Removed from the file

2024-09-27 23:30 UTC, BonniePandora commented on code/modules/vehicles/apc/apc_aa.dm
> +/obj/vehicle/multitile/apc/movie/aa/remove_seated_verbs(mob/living/M, seat)
As above

2024-09-27 23:55 UTC, BonniePandora commented on code/modules/vehicles/apc/apc_aa.dm
> +/obj/vehicle/multitile/apc/movie/aa/set_muzzle_offsets(obj/item/hardpoint/HP)
Checked as of latest commit, values adjusted where needed

2024-09-28 14:54 UTC, AndroBetel submitted a review, later dismissed

2024-09-28 14:54 UTC, AndroBetel commented on code/modules/vehicles/hardpoints/primary/aa_cannon.dm
> +	icon_state = "quad_cannon"
![image](https://github.com/user-attachments/assets/cdd38b87-f9d1-4c94-b688-ebd796f0cc3b)
fucked up shadow

2024-09-28 14:54 UTC, AndroBetel commented on code/modules/vehicles/apc/apc_aa.dm
> +	return ..()
remove this return, fucks up muzzle_flash_pos

2024-09-28 14:54 UTC, AndroBetel commented on code/modules/vehicles/hardpoints/secondary/aa_launcher.dm
> +	fire_delay = 7.0 SECONDS
feels anemic i think, maybe make it almost instant and also up max_clips a little? just a suggestion

2024-09-28 14:54 UTC, AndroBetel commented on code/modules/vehicles/interior/interactable/viewports.dm
> +/obj/structure/interior_viewport/terminal
doesnt work

2024-09-28 14:54 UTC, AndroBetel commented on maps/interiors/apc_aa.dmm
> +/obj/structure/prop/vehicle/sensor_equipment{
should have density = 1

2024-09-28 15:31 UTC, BonniePandora commented on code/modules/vehicles/hardpoints/primary/aa_cannon.dm
> +	icon_state = "quad_cannon"
Ah, alpha/transparency didn't transfer nicely across from the files Boom sent me.
I'll get that sorted

2024-09-28 16:31 UTC, BonniePandora commented on maps/interiors/apc_aa.dmm
> +/obj/structure/prop/vehicle/sensor_equipment{
All requested changes addressed.

2024-09-28 16:32 UTC, BonniePandora commented on code/modules/vehicles/hardpoints/secondary/aa_launcher.dm
> +	fire_delay = 7.0 SECONDS
Upped the actual impact damage (given the ammo type is meant to be a hypersonic kinetic-kill kind of missile) and speed of the projectile massively, keeping the low mag-count to offset the fact this thing is meant to hit like a truck

2024-09-30 00:34 UTC, merged