Customizable Armor
cmss13-devs/cmss13-pve pull request #430
Opened 2024-09-03 03:35 UTC by Max-023

# About the pull request
Makes a new line of Marine combat armor that adds a new level of customization not previously seen, as well as recycles previous features that weren't able to be fully realized.

The first is that webbing is no longer available to attach to uniforms, and instead a new M3 compatible webbing line is provided to attach directly to the armor. The different types provide specific options for storage, coinciding with their name.

Next is that options previously not interactable now are. Marines will be able to decide if their armor will have the shoulder pads or not, as well as are able to paint a skull on their armor should they want one.

And lastly, Smartgunners are now able to paint their harness black. Huzzah.

# Explain why it's good for the game
It gives a level of customizability to the game not previously had and makes a new level of aesthetic customization that differentiates everyone's Marine in their own special ways.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: Added something
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
spellcheck: fixed a few typos
ui: changed something relating to user interfaces
code: changed some code
refactor: refactored some code
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
mapadd: added a new map or section to a map
maptweak: tweaked a map
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2024-09-04 01:04 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-09-04 14:36 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-09-13 08:21 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-09-13 16:12 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-09-13 23:09 UTC, AndroBetel requested changes
should also maybe check gear presets that store stuff in marine armor

2024-09-13 23:09 UTC, AndroBetel commented on code/game/machinery/vending/vendor_types/squad_prep/squad_prep.dm
> +		list("M3 Pattern Magazine Webbing", round(scale * 2), /obj/item/clothing/accessory/storage/webbing/m3, VENDOR_ITEM_REGULAR),
same path as above

2024-09-13 23:09 UTC, AndroBetel commented on code/game/machinery/vending/vendor_types/squad_prep/squad_prep.dm
> +		list("M3 Pattern Shotgun Shell Webbing", round(scale * 0.5), /obj/item/clothing/accessory/storage/webbing/m3/shotgun, VENDOR_ITEM_REGULAR),
iirc round() scales stuff down so its gonna be a 0

2024-09-13 23:09 UTC, AndroBetel commented on code/game/machinery/vending/vendor_types/squad_prep/squad_prep.dm
> +		list("M3 Pattern Magazine Webbing", round(scale * 2), /obj/item/clothing/accessory/storage/webbing/m3, VENDOR_ITEM_REGULAR),
same as above

2024-09-13 23:09 UTC, AndroBetel commented on code/game/machinery/vending/vendor_types/squad_prep/squad_prep.dm
> +		list("M3 Pattern Shotgun Shell Webbing", round(scale * 0.5), /obj/item/clothing/accessory/storage/webbing/m3/shotgun, VENDOR_ITEM_REGULAR),
here too

2024-09-13 23:09 UTC, AndroBetel commented on code/modules/clothing/under/ties.dm
> +/obj/item/storage/internal/accessory/webbing/m3/shotgun
3 shotgun handfuls feels undergwelming

2024-09-13 23:29 UTC, Max-023 commented on code/modules/clothing/under/ties.dm
> +/obj/item/storage/internal/accessory/webbing/m3/shotgun
For Marines who use shotguns as a secondary weapon, 15 in capacity should be more than enough. For those who dedicate their primary 'slot' to the shotgun, it's easy to get more slots to put more shells since boxes can be put in satchels now.

2024-09-16 08:33 UTC, AndroBetel requested changes

2024-09-16 08:33 UTC, AndroBetel commented on code/game/machinery/vending/vendor_types/squad_prep/squad_prep.dm
> +		list("M3 Pattern Webbing", 0.75, /obj/item/clothing/accessory/storage/webbing/m3, VENDOR_ITEM_REGULAR),
scaling is fucked, plus since marines no longer have armor pockets make sure theyre all able to pick any webbing they want

2024-09-16 08:33 UTC, AndroBetel commented on code/modules/clothing/suits/marine_armor/_marine_armor.dm
> +/obj/item/clothing/suit/marine/rto/forecon
forecon need their snowflakey 4 slot armor

2024-09-16 08:33 UTC, AndroBetel commented on code/modules/clothing/under/ties.dm
> +/obj/item/storage/internal/accessory/webbing/m3/shotgun
this is limiting and i can't see a reason for this. 15 shells is 1.5 mags, webbing vests/shotgun shell boxes were made with fitting slots in mind, so this pretty much becomes a noob trap because shotgun shell pouch has 5 slots

2024-09-16 08:38 UTC, AndroBetel requested changes

2024-09-16 08:38 UTC, AndroBetel commented on code/modules/client/preferences_savefile.dm
> +		if((!old_pref_armor) in GLOB.armor_style_list)
also
```suggestion
		if(!(old_pref_armor in GLOB.armor_style_list))
```

2024-09-16 20:35 UTC, AndroBetel requested changes

2024-09-16 20:35 UTC, AndroBetel commented on code/modules/clothing/under/ties.dm
> +		/obj/item/ammo_magazine/handful/shotgun,
ammo boxes work in mysterious ways - taking ammo from them produces parent type of handfuls
```suggestion
		/obj/item/ammo_magazine/handful,
```

2024-09-16 20:53 UTC, Max-023 commented on code/modules/clothing/suits/marine_armor/_marine_armor.dm
> +/obj/item/clothing/suit/marine/rto/forecon
I'll swap it back for now in the vendors, as I do want to make custom webbing options for them as well in the future.

2024-09-16 21:04 UTC, Max-023 commented on code/modules/clothing/under/ties.dm
> +/obj/item/storage/internal/accessory/webbing/m3/shotgun
I will concede this point for now and make it 5 slots.

2024-09-17 13:18 UTC, AndroBetel requested changes

2024-09-17 13:18 UTC, AndroBetel commented on code/modules/clothing/under/ties.dm
> +/obj/item/storage/internal/accessory/black_vest/m3
no need to declare this if there are no variables

2024-09-18 17:06 UTC, Max-023 commented on code/modules/clothing/under/ties.dm
> +/obj/item/storage/internal/accessory/black_vest/m3
Fair enough. When I get home I'll restructure it.

2024-09-21 17:24 UTC, AndroBetel commented
undraft it when you feel like its feature complete and ready for reviews

2024-09-21 20:56 UTC, Max-023 commented
> undraft it when you feel like its feature complete and ready for reviews

Alright, I think it's ready.

2024-09-22 20:53 UTC, Doubleumc requested changes

2024-09-22 20:53 UTC, Doubleumc commented on code/modules/projectiles/gun_helpers.dm
> +		if(!istype(suit, /obj/item/clothing/suit/marine||/obj/item/clothing/suit/storage/marine))
```suggestion
		if(!(istype(suit, /obj/item/clothing/suit/marine) || istype(suit, /obj/item/clothing/suit/storage/marine)))
```

2024-09-22 20:53 UTC, Doubleumc commented on code/game/objects/items/storage/belt.dm
> +	flags_equip_slot = SLOT_WAIST|SLOT_BACK
A belt that goes on the back? Also remember that SG armor limits what can go on the back in the first place.

2024-09-22 20:53 UTC, Doubleumc commented on code/modules/mob/living/carbon/human/update_icons.dm
> +
Just noting that I hate the duplication but can't think of a better way. :(

2024-09-22 20:53 UTC, Doubleumc commented on icons/mob/humans/onmob/belt.dmi
This file is modified but there are no changed icons.

2024-09-22 23:49 UTC, Max-023 commented on code/game/objects/items/storage/belt.dm
> +	flags_equip_slot = SLOT_WAIST|SLOT_BACK
I modified it to allow the belt, and yeah. The sprite reflects the back state, with the holster itself being put on a separate strap that wraps around like a bandolier. My next PR is going to be specifically for doing a light overhaul of the Smartgun itself and this is basically a preliminary step.

2024-09-22 23:50 UTC, Max-023 commented on code/modules/mob/living/carbon/human/update_icons.dm
> +
I do as well : (

2024-09-22 23:50 UTC, Max-023 commented on icons/mob/humans/onmob/belt.dmi
Weird. I will see why that is.

2024-09-24 19:52 UTC, Doubleumc submitted a review, later dismissed

2024-09-28 07:04 UTC, Doubleumc requested changes

2024-09-28 07:04 UTC, Doubleumc commented on code/modules/client/preferences_savefile.dm
> +	if(!old_pref_armor in GLOB.armor_style_list)
`in` is goofy as it is much later in the order of operations than you'd think. The `!` executes first so it becomes `FALSE in GLOB.armor_style_list`.
can read more here: https://www.byond.com/docs/ref/#/operator/in
```suggestion
	if(!(old_pref_armor in GLOB.armor_style_list))
```

2024-09-30 00:39 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-09-30 13:46 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-10-01 05:20 UTC, Doubleumc requested changes

2024-10-07 05:40 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-10-08 16:41 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-10-13 01:01 UTC, Doubleumc requested changes

2024-10-13 01:21 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-10-14 20:12 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-10-23 07:40 UTC, Doubleumc requested changes
Other than that, code good.

2024-10-23 07:40 UTC, Doubleumc commented on icons/mob/humans/onmob/ties.dmi
Should be no need to remove the `dogtag` icon state, it won't display regardless.

2024-10-23 20:35 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-10-23 22:17 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-10-23 22:38 UTC, Doubleumc approved these changes

2024-10-24 17:09 UTC, BonniePandora commented on code/modules/clothing/head/head.dm
> +	name = "uss golden arrow cap"
Lacking capitalization, given it references a named vessel it ought to be the below instead;
`name = "USS Golden Arrow cap"`

2024-10-24 17:10 UTC, BonniePandora commented on code/modules/clothing/head/head.dm
> +	name = "uss golden arrow cap"
Additionally, at least one person's reporting the on_mob sprite for this to not be working.
Unsure if it was an older version of the PR that had been TM'd at the time they found that, but figured it worth mentioning all the same

2024-10-28 07:01 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-11-04 01:31 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-11-04 04:33 UTC, Doubleumc requested changes
Other than that, code good.

2024-11-04 04:33 UTC, Doubleumc commented on code/modules/clothing/head/helmet.dm
> +					if(has_helmet_band)
```suggestion
					if(has_band)
```
I don't think you intended to change the base `...helmet/marine/update_icon()`

2024-11-04 04:33 UTC, Doubleumc commented on code/modules/clothing/head/helmet.dm
> +					if(has_helmet_band)
```suggestion
					if(has_band)
```
I don't think you intended to change the base `...helmet/marine/update_icon()`

2024-11-11 05:00 UTC, Doubleumc requested changes
There may be other hardcoded `...helmet/marine` checks to stumble over but as far as I can tell, code good.

On related note I see you're needing to duplicate a lot of marine helmet behavior for your UPP helmets. It could potentially be simpler if it was a subtype of marine helmets, like `...helmet/marine/upp`, so that it would inherit that behavior.

If there's some USCM stuff you don't want to inherit and can't override could alternatively have a generic "military" or "faction" type with the shared behavior for them both to inherit from. Resulting in something like `...helmet/military/marine` and `...helmet/military/upp`. This would be a lot more work upfront, though.

2024-11-11 14:42 UTC, Max-023 commented
> On related note I see you're needing to duplicate a lot of marine helmet behavior for your UPP helmets. It could potentially be simpler if it was a subtype of marine helmets, like `...helmet/marine/upp`, so that it would inherit that behavior.

That was how it was before and unfortunately I couldn't find a way to get helmet garb to show without separating the UPP helmets from the USCM helmets.

> If there's some USCM stuff you don't want to inherit and can't override could alternatively have a generic "military" or "faction" type with the shared behavior for them both to inherit from. Resulting in something like `...helmet/military/marine` and `...helmet/military/upp`. This would be a lot more work upfront, though.

I could try to make both under the parent of a generic helmet rather than have the USCM helmet be the default, but I would need assistance on that and I'd rather do a follow up PR to do something like that rather than continue to have UPP helmets bottleneck the entire thing.

2024-11-11 14:43 UTC, Max-023 commented on code/modules/mob/living/carbon/human/update_icons.dm
> +		if(istype(head, /obj/item/clothing/head/helmet/marine) || istype(head, /obj/item/clothing/head/helmet/upp))
Squad overlays aren't something I'm particularly looking for the UPP helmets to use, rather I just couldn't section out the code that handled the helmet garb from that which handled squad overlays. Since squad overlays are disabled anyway, I don't know if it would be important to try to bring them back.

2024-11-11 19:03 UTC, Doubleumc commented on code/modules/mob/living/carbon/human/update_icons.dm
> +		if(istype(head, /obj/item/clothing/head/helmet/marine) || istype(head, /obj/item/clothing/head/helmet/upp))
Sure, can do that. I had assumed you wanted squad overlays because you had both `...helmet/marine` and `...helmet/upp` run that code.

To have marine helmets with squad overlays and garb, and have UPP helmets with garb but no squad overlays, can cut that section out of the UPP branch. Like this:
```
		if(istype(head, /obj/item/clothing/head/helmet/marine))
			var/obj/item/clothing/head/helmet/marine/marine_helmet = head
			if(assigned_squad && marine_helmet.flags_marine_helmet & HELMET_SQUAD_OVERLAY)
				if(assigned_squad && assigned_squad.equipment_color && assigned_squad.use_stripe_overlay)
					var/leader = assigned_squad.squad_leader
					var/image/helmet_overlay = image(marine_helmet.helmet_overlay_icon, icon_state = "std-helmet")
					if(leader == src)
						helmet_overlay = image(marine_helmet.helmet_overlay_icon, icon_state = "sql-helmet")
					helmet_overlay.layer = -HEAD_SQUAD_LAYER
					helmet_overlay.alpha = assigned_squad.armor_alpha
					helmet_overlay.color = assigned_squad.equipment_color
					overlays_standing[HEAD_SQUAD_LAYER] = helmet_overlay
					apply_overlay(HEAD_SQUAD_LAYER)

			var/num_helmet_overlays = 0
			for(var/i in 1 to length(marine_helmet.helmet_overlays))
				// Add small numbers to the head garb layer so we don't have a layer conflict
				// the i-1 bit is to make it 0-based, not 1-based like BYOND wants
				overlays_standing[HEAD_GARB_LAYER + (i-1)] = image('icons/mob/humans/onmob/helmet_garb.dmi', src, marine_helmet.helmet_overlays[i])
				num_helmet_overlays++

			// null out the rest of the space allocated for helmet overlays
			// God I hate 1-based indexing
			for(var/i in num_helmet_overlays+1 to MAX_HEAD_GARB_ITEMS)
				overlays_standing[HEAD_GARB_LAYER + (i-1)] = null

			for(var/i in HEAD_GARB_LAYER to (HEAD_GARB_LAYER + MAX_HEAD_GARB_ITEMS - 1))
				apply_overlay(i)

		else if(istype(head, /obj/item/clothing/head/helmet/upp))
			var/obj/item/clothing/head/helmet/upp/upp_helmet = head
			var/num_helmet_overlays = 0
			for(var/i in 1 to length(upp_helmet.helmet_overlays))
				// Add small numbers to the head garb layer so we don't have a layer conflict
				// the i-1 bit is to make it 0-based, not 1-based like BYOND wants
				overlays_standing[HEAD_GARB_LAYER + (i-1)] = image('icons/mob/humans/onmob/helmet_garb.dmi', src, upp_helmet.helmet_overlays[i])
				num_helmet_overlays++

			// null out the rest of the space allocated for helmet overlays
			// God I hate 1-based indexing
			for(var/i in num_helmet_overlays+1 to MAX_HEAD_GARB_ITEMS)
				overlays_standing[HEAD_GARB_LAYER + (i-1)] = null

			for(var/i in HEAD_GARB_LAYER to (HEAD_GARB_LAYER + MAX_HEAD_GARB_ITEMS - 1))
				apply_overlay(i)
```

2024-11-11 19:07 UTC, Doubleumc commented
Certainly. Those were meant as suggestions, not requirements. The only requirement was the code review there, which we're working on addressing now.

2024-11-11 19:34 UTC, Max-023 commented on code/modules/mob/living/carbon/human/update_icons.dm
> +		if(istype(head, /obj/item/clothing/head/helmet/marine) || istype(head, /obj/item/clothing/head/helmet/upp))
Alright, that seemed to work! Went ahead and pushed the changes.

2024-11-11 19:48 UTC, Doubleumc approved these changes

2024-11-11 19:52 UTC, merged