Human AI
cmss13-devs/cmss13-pve pull request #442
Opened 2024-09-08 19:07 UTC by Zonespace27

# DO NOT USE OR PORT. THIS IS FAR FROM READY.

2024-09-08 19:07 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-09-08 19:08 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-09-13 08:21 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-09-14 17:29 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-12-08 03:19 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-12-08 03:20 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-01-03 20:46 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-01-15 02:57 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-01-21 11:50 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-01-22 03:11 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-01-23 09:57 UTC, harryob requested changes

2025-01-23 09:57 UTC, harryob commented on code/game/objects/structures/barricade/non_folding.dm
> +/obj/structure/barricade/metal/plasteel/wired/New()
ditto, why New?

2025-01-23 09:57 UTC, harryob commented on code/modules/mob/living/carbon/human/ai/action_datums/action_datums.dm
> +/datum/ai_action/proc/get_conflicts(datum/human_ai_brain/brain)
nit - this api isn't documented

2025-01-23 09:57 UTC, harryob commented on code/modules/mob/living/carbon/human/ai/ai_management_menu.dm
> +	if(mob.ckey && alert("This mob is being controlled by [mob.ckey]. Are you sure you wish to add AI to it?","Make AI","Yes","No") != "Yes")
tgui_alert

2025-01-23 09:57 UTC, harryob commented on code/modules/mob/living/carbon/human/ai/ai_spawner/ai_spawner.dm
> +//	return
?

2025-01-23 09:57 UTC, harryob commented on code/modules/mob/living/carbon/human/ai/ai_spawner/ai_spawner.dm
> +	var/path
though primarily self documenting ....

2025-01-23 09:57 UTC, harryob commented on code/modules/mob/living/carbon/human/ai/ai_spawner/ai_spawner.dm
> +			//ai_human.get_ai_brain().appraise_inventory(armor = TRUE)
wanted or unwanted?

2025-01-23 09:57 UTC, harryob commented on code/modules/mob/living/carbon/human/ai/brain/ai_brain.dm
> +		target_turf = get_turf(bullet.firer	)
whitespace

2025-01-23 09:57 UTC, harryob commented on code/modules/mob/living/carbon/human/ai/brain/ai_brain_health.dm
> +			goto bleed
cm, somehow, has not a single goto statement in it. is this the neatest way of doing this?

2025-01-23 09:57 UTC, harryob commented on code/modules/mob/living/carbon/human/ai/brain/ai_brain_items.dm
> +		goto back_statement
ditto

2025-01-23 09:57 UTC, harryob commented on code/modules/mob/living/carbon/human/ai/brain/ai_brain_items.dm
> +		//	set_primary_melee(inv_item)
gonna be used?

2025-01-23 09:57 UTC, harryob commented on code/modules/mob/living/carbon/human/ai/brain/ai_brain_items.dm
> +	set_primary_melee(null)*/
ditto

2025-01-23 09:57 UTC, harryob commented on code/modules/mob/living/carbon/human/ai/human_ai_interaction.dm
> +/*obj/structure/window_frame/human_ai_obstacle(mob/living/carbon/human/ai_human, datum/human_ai_brain/brain, direction, turf/target)
bip

2025-01-23 09:57 UTC, harryob commented on tgui/packages/tgui/interfaces/HumanAISpawner.tsx
> +                      <div style={{ paddingBottom: '12px' }} key={squad.path}>
you are found guilty of crimes against `<Box pb={12}>` how do you plead

2025-01-23 09:57 UTC, harryob commented on tgui/packages/tgui/interfaces/HumanSquadSpawner.tsx
> +                  <div />
just conditionally render instead of a ternary here

2025-01-23 09:57 UTC, harryob commented on code/modules/mob/living/carbon/human/human.dm
> +/mob/living/carbon/human/Initialize(mapload, new_species = null, ai = FALSE)
where's this arg used?

2025-01-23 09:57 UTC, harryob commented on code/modules/gear_presets/other.dm
> +		new_human.get_ai_brain().ignore_looting = TRUE
feels like this should be done by the brain by listening on the set_species signal

2025-01-23 09:57 UTC, harryob commented on code/modules/gear_presets/yautja.dm
> +		new_human.get_ai_brain().ignore_looting = TRUE
as above

2025-01-24 00:19 UTC, Zonespace27 commented on code/game/objects/structures/barricade/folding.dm
> +/obj/structure/barricade/plasteel/metal/wired/New()
copy-paste, fixed

2025-01-24 00:28 UTC, Zonespace27 commented on code/modules/mob/living/carbon/human/ai/brain/ai_brain_items.dm
> +		//	set_primary_melee(inv_item)
Improving the melee system is planned for the future (not in this PR though) so i'd like to leave this melee stuff in for now

2025-01-24 00:30 UTC, Zonespace27 commented on code/modules/mob/living/carbon/human/human.dm
> +/mob/living/carbon/human/Initialize(mapload, new_species = null, ai = FALSE)
nowhere, removed

2025-01-24 00:33 UTC, Zonespace27 commented on code/modules/gear_presets/other.dm
> +		new_human.get_ai_brain().ignore_looting = TRUE
agreed

2025-01-25 04:42 UTC, Zonespace27 commented on tgui/packages/tgui/interfaces/HumanAISpawner.tsx
> +                      <div style={{ paddingBottom: '12px' }} key={squad.path}>
Guilticent

2025-01-25 21:53 UTC, harryob requested changes

2025-01-25 21:53 UTC, harryob commented on code/modules/mob/living/carbon/human/ai/ai_management_menu.dm
> +	if(mob.ckey && tgui_alert("This mob is being controlled by [mob.ckey]. Are you sure you wish to add AI to it?","Make AI", list("Yes","No")) != "Yes")
tgui_alert requires a user argument

2025-01-26 02:25 UTC, Zonespace27 commented on code/modules/mob/living/carbon/human/ai/ai_management_menu.dm
> +	if(mob.ckey && tgui_alert("This mob is being controlled by [mob.ckey]. Are you sure you wish to add AI to it?","Make AI", list("Yes","No")) != "Yes")
resolved

2025-01-26 05:24 UTC, harryob approved these changes

2025-01-26 05:43 UTC, merged