Send in the nyarines
cmss13-devs/cmss13-pve pull request #452
Opened 2024-09-14 21:34 UTC by BonniePandora

# About the pull request

Adds a new helmet cosmetic; attachable cat-ears.

# Explain why it's good for the game

Allows marines to be kbitty  :3
(Honestly this is mostly a shitpost code-project I had, not gonna be overly bothered if this is shit-canned for being too goofy)

# Testing Photographs and Procedure
Compiled and ran fine on a local instance
<details>
<summary>Screenshots & Videos</summary>

![image](https://github.com/user-attachments/assets/e3c4d7dc-7d14-47fe-9051-5f45a477fd3f)

</details>

# Changelog

:cl:
add: Adds a new helmet cosmetic to the loadout menu
/:cl:

2024-09-15 22:08 UTC, Doubleumc requested changes
Cat ears won't be merged.

In the interest in teaching it does have an issue, where you're removing/adding/changing icons besides the kitty ears: <https://github.com/cmss13-devs/cmss13-pve/pull/452/checks?check_run_id=30152395454>

Other than that, everything is done correctly.

2024-09-15 22:49 UTC, BonniePandora commented
> Cat ears won't be merged.
> 
> In the interest in teaching it does have an issue, where you're removing/adding/changing icons besides the kitty ears: https://github.com/cmss13-devs/cmss13-pve/pull/452/checks?check_run_id=30152395454
> 
> Other than that, everything is done correctly.

Oooooh, that'll be 'cause I forgot to update my local before starting on this
Thanks for pointing it out!
Also yeah I didn't expect this to be merged like I said so, no great loss on my part.

2024-09-16 03:47 UTC, KoishiVibe commented
i think it's at least good for TM as a laugh
:3

2024-09-22 18:12 UTC, BonniePandora commented
> Cat ears won't be merged.
> 
> In the interest in teaching it does have an issue, where you're removing/adding/changing icons besides the kitty ears: https://github.com/cmss13-devs/cmss13-pve/pull/452/checks?check_run_id=30152395454
> 
> Other than that, everything is done correctly.

This has been addressed and fixed in the latest commit

2024-09-30 00:39 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-10-04 11:44 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-10-07 05:40 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-10-08 06:49 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-10-28 07:01 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-04-01 19:56 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-04-22 14:34 UTC, cm13-github commented
<!-- tgs_test_merge_comment -->
## Test merge deployment history:

<details><summary>Test Merge Deployed @ 04/22/2025 14:34:12 +00:00:</summary>

##### Server Instance
PVECM: Red

##### Merged By
MessageCypher

##### Revision
Origin: a47d884bc9c691b71bf65a3f85b8a6dbd94ce6ce
Pull Request: b46a48e53d7ffee828827c5a924dc960a502cdad
Server: 231a89328119761ff02bd99b35da4e7443107cad
</details>

2025-05-20 22:06 UTC, closed without merging