Folder and Notepad Sprite Updates
cmss13-devs/cmss13-pve pull request #465
Opened 2024-09-22 03:16 UTC by AmoryBlaine

I made the folders and notepads better conform to a more modern shading and palette.

2024-09-22 21:20 UTC, Doubleumc requested changes
Just a minor phrasing issue. Otherwise, code good.

2024-09-22 21:20 UTC, Doubleumc commented on code/game/objects/prop.dm
> +	desc = "A book critical of the United States Marine Corps by Marine Corps legend, Major General Smedley Butler. In short, the book outlines the function which the historical Marine Corps had in esta
```suggestion
	desc = "A book critical of the United States Marine Corps by Marine Corps legend, Major General Smedley Butler. In short, the book outlines the function which the historical Marine Corps had in establishing and enforcing American global hegemony. Good thing its critiques have no contemporary application. Right?"
```

2024-09-23 20:21 UTC, Doubleumc approved these changes

2024-09-27 21:58 UTC, AndroBetel approved these changes

2024-09-27 21:58 UTC, AndroBetel commented on code/game/objects/prop.dm
> +	desc ="The bare minimum in communist reading."
```suggestion
	desc = "The bare minimum in communist reading."
```

2024-09-27 21:58 UTC, AndroBetel commented on code/modules/paperwork/folders.dm
> +	icon_state = "folder_green"
```suggestion
	icon_state = "folder_green"

```

2024-09-28 12:16 UTC, merged