garrow mod 3
cmss13-devs/cmss13-pve pull request #476
Opened 2024-09-26 01:49 UTC by DexterDude

Replaces all the shitty wood crates in prep with actual crates that store stuff properly, no more crowbar and ugly wood sprites everywhere. Gives most items unique cases with AWESOME overlays (ty umc, andro, and zonespace), and modifies the map a bit. large mk1 crates now exist, they store 32 magazines.

not much else for now.

2024-10-07 05:40 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-10-09 23:39 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-10-23 20:06 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-10-27 02:17 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-10-27 03:19 UTC, DexterDude commented
FUCK YOU

2024-10-27 03:28 UTC, DexterDude commented
STOP FUCKING FAILING

2024-10-28 07:01 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-10-29 18:43 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-11-06 23:50 UTC, BonniePandora commented on maps/map_files/golden_arrow/golden_arrow.dmm
> +/obj/structure/machinery/cm_vending/gear/medic,
This still needs to be swapped out with `/obj/structure/machinery/cm_vending/clothing/medic`, as the current one is the PVP medical equipment vendor

2024-11-09 06:07 UTC, DexterDude commented on maps/map_files/golden_arrow/golden_arrow.dmm
> +/obj/structure/machinery/cm_vending/gear/medic,
done btw

2024-11-24 21:40 UTC, harryob submitted a review, later dismissed

2024-11-24 21:40 UTC, harryob commented on code/game/machinery/ARES/ARES_interface.dm
> +	var/image/source_image = image(src.icon, "ai_interface_top", layer = ABOVE_MOB_LAYER)
```suggestion
	var/image/source_image = image(icon, "ai_interface_top", layer = ABOVE_MOB_LAYER)
```

2024-11-24 21:40 UTC, harryob commented on code/game/objects/structures/stool_bed_chair_nest/chairs.dm
> +	dir = 8
u know there are defines for this

2024-11-24 21:40 UTC, harryob commented on code/modules/almayer/machinery.dm
> +	else return
very redundant line

2024-11-24 21:40 UTC, harryob commented on code/modules/cm_marines/equipment/guncases.dm
> +		overlays += image(src.icon, "+sentrycomp")
```suggestion
		overlays += image(icon, "case_lid_open")
	else
		overlays += image(icon, "sentrycase_lid")
		return
	if(locate(/obj/item/defenses/handheld/sentry) in contents)
		overlays += image(icon, "+sentry")
	if(locate(/obj/item/ammo_magazine/sentry) in contents)
		overlays += image(icon, "+sentrymag")
	if(locate(/obj/item/device/sentry_computer) in contents)
		overlays += image(icon, "+sentrycomp")
```

2024-11-24 21:40 UTC, harryob commented on code/modules/cm_marines/equipment/guncases.dm
> +		overlays += image(src.icon, "+stock")
```suggestion
		overlays += image(icon, "bigcase_lid_open")
	else
		overlays += image(icon, "shotguncase_lid")
		return
	if(locate(/obj/item/weapon/gun/shotgun/pump) in contents)
		overlays += image(icon, "+shotgun")
	if(locate(/obj/item/ammo_magazine/shotgun/buckshot) in contents)
		overlays += image(icon, "+buckshot")
	if(locate(/obj/item/ammo_magazine/shotgun/slugs) in contents)
		overlays += image(icon, "+slug")
	if(locate(/obj/item/storage/large_holster/m37) in contents)
		overlays += image(icon, "+scabbard")
	if(locate(/obj/item/attachable/stock/shotgun) in contents)
		overlays += image(icon, "+stock")
```

2024-11-24 21:40 UTC, harryob commented on code/modules/cm_marines/equipment/guncases.dm
> +	if(length(src.contents) >= storage_slots * 0.25)
```suggestion
		overlays += image(icon, "case_lid_open")
	else
		overlays += image(icon, "mdcase_lid")
		return

	if(length(contents) >= storage_slots)
		var/image/source_image = image(icon, "+md")
		source_image.pixel_x = 0
		overlays += source_image
	if(length(contents) >= storage_slots * 0.75)
		var/image/source_image = image(icon, "+md")
		source_image.pixel_x = 6
		overlays += source_image
	if(length(contents) >= storage_slots * 0.5)
		var/image/source_image = image(icon, "+md")
		source_image.pixel_x = 12
		overlays += source_image
	if(length(contents) >= storage_slots * 0.25)
```

2024-11-24 21:40 UTC, harryob commented on code/modules/cm_marines/equipment/guncases.dm
> +		overlays += source_image
```suggestion
		overlays += image(icon, "case_lid_open")
	else
		overlays += image(icon, "fuelcase_lid")
		return

	if(length(contents) >= 1)
		var/image/source_image = image(icon, "+fuel_bottom")
		source_image.pixel_x = 0
		overlays += source_image
	if(length(contents) >= 2)
		var/image/source_image = image(icon, "+fuel_bottom")
		source_image.pixel_x = 8
		overlays += source_image
	if(length(contents) >= 3)
		var/image/source_image = image(icon, "+fuel_bottom")
		source_image.pixel_x = 16
		overlays += source_image
	if(length(contents) >= 4)
		var/image/source_image = image(icon, "+fuel")
		source_image.pixel_x = 0
		overlays += source_image
	if(length(contents) >= 5)
		var/image/source_image = image(icon, "+fuel")
		source_image.pixel_x = 8
		overlays += source_image
	if(length(contents) >= 6)
		var/image/source_image = image(icon, "+fuel")
		source_image.pixel_x = 16
		overlays += source_image
```

2024-11-24 21:40 UTC, harryob commented on code/modules/reagents/chemistry_machinery/chem_dispenser.dm
> +
stop that

```suggestion
	if(!beaker)
		return
	
	overlays += "+beaker"
	if(inoperable())
		return
	
	overlays += "+onlight"

```

2024-11-24 21:40 UTC, harryob commented on code/modules/vehicles/interior/interactable/vehicle_locker.dm
> +									)
```suggestion
	container.bypass_w_limit = list(
		/obj/item/reagent_container/glass,
		/obj/item/reagent_container/food,
		/obj/item/tool/kitchen,
	)
```

2024-11-24 21:40 UTC, harryob commented on code/modules/vehicles/interior/interactable/vehicle_locker.dm
> +	new /obj/item/tool/kitchen/utensil/fork(container)
```suggestion
	for(var/i in 1 to 12)
		new /obj/item/tool/kitchen/utensil/fork(container)
```

2024-11-24 21:40 UTC, harryob commented on code/modules/vehicles/interior/interactable/vehicle_locker.dm
> +	new /obj/item/reagent_container/food/drinks/plasticcup(container)
```suggestion
	for(var/i in 1 to 12)
		new /obj/item/reagent_container/food/drinks/plasticcup(container)
```

2024-11-25 11:54 UTC, DexterDude commented
weird issue with mapgen variations always spawning no matter the chance being changed

2024-11-26 04:28 UTC, Doubleumc requested changes
Other than that, code good.

2024-11-26 04:28 UTC, Doubleumc commented on code/game/objects/items/reagent_containers/food/snacks.dm
> +	reagents.add_reagent("carpotoxin", 1)
```suggestion
/obj/item/reagent_container/food/snacks/cracker/tachyon/Initialize()
	. = ..()
	reagents.add_reagent("carpotoxin", 1)
```
`...cracker/Initialize()` is already defined, you were redefining it here. You probably meant to define `...cracker/tachyon/Initialize()`.

The `. = ..()` bit means its executing the proc of its parent type (cracker), as in adding 1 unit of bread and salt already. The only additional ingredient you want to add here is just the carpotoxin.

2024-12-02 00:18 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-12-11 23:57 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-12-15 07:46 UTC, Meatstuff882 commented
Could there be a non-wooden crate added to the supply launch room? We've had a supply launch room for a while but for the most part we haven't had suitable crates to launch supplies with.

2024-12-17 01:04 UTC, AndroBetel requested changes

2024-12-17 01:04 UTC, AndroBetel commented on code/game/objects/items/reagent_containers/food/drinks.dm
> +	icon_state = "plasticcup"
same icon_state?

2024-12-17 01:04 UTC, AndroBetel commented on code/game/objects/items/reagent_containers/food/snacks.dm
> +/obj/item/reagent_container/food/snacks/canteen
all of this is unused isnt it

2024-12-17 01:04 UTC, AndroBetel commented on code/game/objects/items/storage/misc.dm
> +	can_hold = list(
unused too? kind of?

2024-12-17 01:04 UTC, AndroBetel commented on code/game/turfs/walls/wall_types.dm
> +/turf/closed/wall/almayer/outer/friegt
i love friegt...

2024-12-17 01:04 UTC, AndroBetel commented on code/modules/vehicles/powerloader.dm
> +			set_light(0)
light doesnt turn off when you leave the powerloader via dropping the clamp (check for more ways to do this)

2024-12-27 08:39 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-01-03 17:58 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-01-03 20:42 UTC, merged