Make Arterial Bleeds Disco Again
cmss13-devs/cmss13-pve pull request #503
Opened 2024-10-12 12:30 UTC by The32bitguy

To do: Make separate proc for spraying blood, so game does not runtime when another dev touches the proc. Let humans "pack" the IB to slow it eg first aid

# About the pull request

# Explain why it's good for the game

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: Added something
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
spellcheck: fixed a few typos
ui: changed something relating to user interfaces
code: changed some code
refactor: refactored some code
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
mapadd: added a new map or section to a map
maptweak: tweaked a map
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2024-12-22 03:48 UTC, AndroBetel commented on code/datums/effects/bleeding.dm
> +	if(prob(10) || src.show_spray_immediately)
no need to use src. here and further

2024-12-22 03:48 UTC, AndroBetel commented on code/modules/mob/living/blood.dm
> +	src.visible_message(\
no need for src. here and further

2024-12-22 03:48 UTC, AndroBetel commented on code/modules/mob/living/blood.dm
> +					//if(rand_zone() == "head")
redundant comment

2024-12-22 03:48 UTC, AndroBetel commented on code/game/objects/items/stacks/medical.dm
> +		for(var/datum/effects/bleeding/internal/I in affecting.bleeding_effects_list)
this should be done by a different item (a proper tourniqet)

2024-12-22 03:48 UTC, AndroBetel commented on code/modules/organs/limbs.dm
> +		I.has_been_bandaged = TRUE
having to pack it with gauze seems like a move in any given situation, tq should have some advantages

2024-12-22 03:49 UTC, AndroBetel requested changes
see above

2024-12-22 03:50 UTC, AndroBetel submitted a review, later dismissed

2024-12-22 03:50 UTC, AndroBetel commented on code/datums/effects/bleeding.dm
> +			affected_mob.blood_volume = max(affected_mob.blood_volume - blood_loss*20*(affected_mob.blood_volume/BLOOD_VOLUME_NORMAL), 0)
`20` should be a define, else its just some random arbitrary number

2024-12-23 14:26 UTC, The32bitguy commented on code/modules/organs/limbs.dm
> +		I.has_been_bandaged = TRUE
It seems to be a bind between making it a medical item that would be carried by a non-medic and making it a dedicated tq item, and how they would differ in effectiveness. Maybe make it gauze for now.

2024-12-23 16:44 UTC, The32bitguy commented on code/game/objects/items/stacks/medical.dm
> +		for(var/datum/effects/bleeding/internal/I in affecting.bleeding_effects_list)
Changed to using gauze https://github.com/cmss13-devs/cmss13-pve/blob/9f5c4aca39d08601830572fbbb91e0f2a68a4b92/code/game/objects/items/stacks/medical.dm#L82-L85

Changed to using trauma kit https://github.com/cmss13-devs/cmss13-pve/blob/9f5c4aca39d08601830572fbbb91e0f2a68a4b92/code/game/objects/items/stacks/medical.dm#L196-L199

2024-12-23 16:46 UTC, The32bitguy commented on code/datums/effects/bleeding.dm
> +			affected_mob.blood_volume = max(affected_mob.blood_volume - blood_loss*20*(affected_mob.blood_volume/BLOOD_VOLUME_NORMAL), 0)
https://github.com/cmss13-devs/cmss13-pve/blob/9f5c4aca39d08601830572fbbb91e0f2a68a4b92/code/datums/effects/bleeding.dm#L5

2025-01-26 05:47 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-02-11 03:41 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-03-23 09:05 UTC, cm13-github commented
<!-- tgs_test_merge_comment -->
## Test merge deployment history:

<details><summary>Test Merge Updated @ 03/23/2025 09:05:10 +00:00:</summary>

##### Server Instance
PVECM: Green

##### Merged By
Drathek

##### Revision
Origin: 1172d1f1588b01be620a11e22ea32db183fc2560
Pull Request: cdd07ebee15a056d0978cbf8260201fefe39a283
Server: 3869c77485a8e03a741435052c3c16ca233f3258
</details>

2025-05-23 19:01 UTC, BonniePandora approved these changes
Code lgtm, changes have been addressed & the PR's commonly used in test-merges

2025-05-23 20:52 UTC, merged