Goggles Updated
cmss13-devs/cmss13-pve pull request #507
Opened 2024-10-13 19:05 UTC by AmoryBlaine

Gets rid of the M1A1 goggles and uses their outline to replace the standard ballistic goggle variants. All goggle variants now available from vendor, PRESCRIPTION goggles now loadout only.

2024-10-23 05:19 UTC, Doubleumc requested changes
Otherwise, code good.

2024-10-23 05:19 UTC, Doubleumc commented on code/game/machinery/vending/vendor_types/squad_prep/squad_prep.dm
> +		list("prescription glasses", round(scale * 10), /obj/item/clothing/glasses/regular, VENDOR_ITEM_REGULAR),
```suggestion
		list("Prescription glasses", round(scale * 10), /obj/item/clothing/glasses/regular, VENDOR_ITEM_REGULAR),
```

2024-10-23 05:19 UTC, Doubleumc commented on code/game/machinery/vending/vendor_types/squad_prep/squad_prep.dm
> +		list("prescription glasses", round(scale * 10), /obj/item/clothing/glasses/regular, VENDOR_ITEM_REGULAR),
```suggestion
		list("Prescription glasses", round(scale * 10), /obj/item/clothing/glasses/regular, VENDOR_ITEM_REGULAR),
```

2024-10-23 05:19 UTC, Doubleumc commented on code/modules/clothing/glasses/glasses.dm
> +	name = "custom ballistic goggles"
```suggestion
	name = "prescription ballistic goggles"
```
Prefer these be labeled "prescription" rather than "custom". "Prescription" makes it immediately clear why they're special, "custom" could mean many things.

2024-10-23 05:19 UTC, Doubleumc commented on code/modules/clothing/glasses/glasses.dm
> +	name = "custom sun-shaded ballistic goggles"
```suggestion
	name = "prescription sun-shaded ballistic goggles"
```

2024-10-23 05:19 UTC, Doubleumc commented on code/modules/clothing/glasses/glasses.dm
> +	name = "custom laser-shaded ballistic goggles"
```suggestion
	name = "prescription laser-shaded ballistic goggles"
```

2024-10-23 20:35 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-11-15 20:58 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-11-18 15:41 UTC, closed without merging