Tougher Airlocks + Airlock Assemblies on Destruction
cmss13-devs/cmss13-pve pull request #508
Opened 2024-10-13 21:28 UTC by GriffinMan4455

# About the pull request

Airlocks have twice the health (slightly more than twice, for multitiles) which means it takes ~70-75% of a regular M41 magazine to kill one. Xenos do the same amount of damage as before so kill doors the same speed, though i'm open to upping this as a balancing countermeasure to Xenos tearing through welded doors too fast.

Has been tested, everything works fine that I thought to test, Xenos still kill doors at the same speed.

Remember: something that is self-evident to you might not be to others. Explain your rationale fully, even if you feel it goes without saying. -->

# Explain why it's good for the game

 Heavily discourages marines gunning down doors instead of just taking TOOLS! Tool-marines and running Bypasses are much more important now that it takes a significant ammo investment when we don't carry a ton of ammo per mission, and there's potentially lots of doors to bust through on most maps.

# Testing Photographs and Procedure

![image](https://github.com/user-attachments/assets/9e3470b3-1a5f-4eb1-93e8-927a5f5ad070)

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: Made destroyed airlocks spawn an airlock assembly on the tiles they cover, this includes both Airlocks and Multitiles.
balance: Airlocks have much more damage_cap, meaning it takes more rounds from a marine to kill them, Xeno damage unchanged.
/:cl:

2024-10-13 21:28 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-10-13 21:29 UTC, GriffinMan4455 commented
What why the hell is walkman.dm even IN this PR I don't even HAVE that branch anymore what the fuck is up with VSC dawg

2024-10-13 21:40 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-10-19 20:37 UTC, KoishiVibe commented
Ideally I think xenos should take more strikes to get through welded doors? Or it should be an admin toggle for suitably dramatic moments.

2024-10-19 21:57 UTC, GriffinMan4455 commented
> Ideally I think xenos should take more strikes to get through welded doors? Or it should be an admin toggle for suitably dramatic moments.

Even more? I already upped it to 20, damn  
I can up it again, sure

2024-10-23 01:39 UTC, Doubleumc requested changes

2024-10-23 01:39 UTC, Doubleumc commented on code/game/machinery/doors/airlock.dm
> +		new /obj/structure/airlock_assembly
```suggestion
```
This creates a new airlock assembly in the provided location. Since no location was provided, it spawns in nullspace.
`deconstruct()` below is what's adding airlock assemblies to the tiles the airlock occupies.

2024-10-24 21:00 UTC, Doubleumc approved these changes

2024-10-30 06:05 UTC, merged