Chemical Weapons (CN20) in the FS Menu
cmss13-devs/cmss13-pve pull request #510
Opened 2024-10-17 01:04 UTC by GriffinMan4455

# About the pull request

End-goal of this PR is to have a CN20 Banshee variant (already done as of submitting to git), ideally a CN20 mortar round, and in supreme USCM fashion, a CN20 OB (fuckhueg gas muahahaha)

Banshee was tested already, works fine. Probably cludgecode but fuck you it works

Remember: something that is self-evident to you might not be to others. Explain your rationale fully, even if you feel it goes without saying. -->

# Explain why it's good for the game

GM's always want more fire support stuff, and CN20 has been mentioned by name several times now especially in chemical weapons ops, since using it without spawning a person and having them chuck nades can be difficult

# Testing Photographs and Procedure

I'll add some after everything's in maybe (I said this for all my other PR's and half of them I forgot lmao)

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: Added something
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
spellcheck: fixed a few typos
ui: changed something relating to user interfaces
code: changed some code
refactor: refactored some code
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
mapadd: added a new map or section to a map
maptweak: tweaked a map
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2024-10-23 01:26 UTC, Doubleumc requested changes

2024-10-23 01:26 UTC, Doubleumc commented on code/modules/cm_marines/dropship_ammo.dm
> +		cell_explosion(impact, 25, 44, EXPLOSION_FALLOFF_SHAPE_LINEAR, null, create_cause_data(initial(name), source_mob))
```suggestion
	spawn(5)
		cell_explosion(impact, 25, 44, EXPLOSION_FALLOFF_SHAPE_LINEAR, null, create_cause_data(initial(name), source_mob))
```
`addtimer(..., 0.5 SECONDS)` is queuing an explosion to happen half a second after detonation
`spawn(5) cell_explosion(...)` is also queueing an explosion to happen half a second after detonation (5 deciseconds = 0.5 seconds)
I don't think you intended to have two explosions happen on top on one another.

2024-10-23 01:26 UTC, Doubleumc commented on code/modules/cm_marines/dropship_ammo.dm
> +			var/datum/effect_system/smoke_spread/cn20 = new/datum/effect_system/smoke_spread/cn20()
```suggestion
			var/datum/effect_system/smoke_spread/cn20/cn20 = new()
```
`var/datum/effect_system/smoke_spread/cn20` is a variable (`var`), of type `/datum/effect_system/smoke_spread`, and it is named `cn20`.
`new/datum/effect_system/smoke_spread/cn20()` is creating a new entity of type `/datum/effect_system/smoke_spread/cn20` and storing it in that var.
Since `.../smoke_spread/cn20` is a subtype of `.../smoke_spread` it fits and works, but the explicit type for `new()` can be confusing and is unnecessary.

An untyped `new()` assumes the type of the variable its being assigned into, so instead by explicitly typing the variable to the smoke type you want can simplify the expression. A variable (`var`) of type `/datum/effect_system/smoke_spread/cn20` that's named `cn20` can be expressed like this:
```
var/datum/effect_system/smoke_spread/cn20/cn20 = new()
```

2024-10-23 01:26 UTC, Doubleumc commented on code/modules/cm_marines/dropship_ammo.dm
> +			cn20.set_up(8,0,impact,null)
```suggestion
			cn20.set_up(8, 0, impact, null)
```
Prefer spaces between the arguments for readability.

2024-10-23 01:26 UTC, Doubleumc commented on code/modules/cm_marines/orbital_cannon.dm
> +		cn20.set_up(12,0,target,null)
```suggestion
		var/datum/effect_system/smoke_spread/cn20/cn20 = new()
		cn20.set_up(12, 0, target, null)
```
Same as previous w/r/t new typing and spacing.

2024-10-23 01:26 UTC, Doubleumc commented on code/modules/admin/game_master/extra_buttons/fire_support_menu.dm
> +#define MORTAR_ORDNANCE list("High Explosive Shell", "Incendiary Shell", "Fragmentation Shell", "Flare Shell", "Nerve Gas Shell")
You add a "Nerve Gas Shell" to the options, but do not specify what that option will do within the `InterceptClickOn` proc. Need to specify it as you did with "CN-20 Missile" and "Nerve Gas OB".

2024-10-23 01:26 UTC, Doubleumc commented on code/modules/admin/game_master/extra_buttons/fire_support_menu.dm
> +				var/obj/structure/ob_ammo/warhead/nerve/ammo= new()
```suggestion
				var/obj/structure/ob_ammo/warhead/nerve/ammo = new()
```

2024-10-23 20:52 UTC, GriffinMan4455 commented on code/modules/admin/game_master/extra_buttons/fire_support_menu.dm
> +#define MORTAR_ORDNANCE list("High Explosive Shell", "Incendiary Shell", "Fragmentation Shell", "Flare Shell", "Nerve Gas Shell")
Oh! I was working on these a couple days ago, I just completely forgot to finish them up, my bad lmao
I think I set the actual mortar shell coding aside when someone, Amory maybe, suggested seperating the chemical weapons to a new menu subpart entirely and I started looking into how to do so w/ the TGUI

2024-10-24 20:59 UTC, Doubleumc approved these changes

2024-10-24 21:03 UTC, merged