Fire Support Menu GAU and Laser fixes
cmss13-devs/cmss13-pve pull request #511
Opened 2024-10-19 07:14 UTC by GriffinMan4455

# About the pull request

Makes the GAU's and Laser in the GM Fire Support menu work again

Tested, they work fine now.

Remember: something that is self-evident to you might not be to others. Explain your rationale fully, even if you feel it goes without saying. -->

# Explain why it's good for the game

GM tools should work 👍 

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
fix: GAU and Laser in FS Menu work again yippeee
/:cl:

2024-10-19 17:01 UTC, Drulikar requested changes
Cause data is very flexible what you can give it. Simply handle the fired from location sometimes not being provided e.g. `fired_from?.name` rather than remove all cause data functionality.

2024-10-19 21:59 UTC, GriffinMan4455 commented
It's like I said in the discord, I did it this way because I don't know how to do what you're asking, and it's better to have features GM's use work fine rather than have cause data (something that's not...really useful on PvE anyways?)  
That was my reasoning at least, and none of the GM's took issue with it when I said that was what I was doing /shrug

2024-10-20 04:48 UTC, GriffinMan4455 commented
Oh? Hold off on that review then lemee see what I did

2024-10-20 07:36 UTC, Drulikar approved these changes

2024-10-21 00:30 UTC, merged