Makes Dogtags removable after 30 seconds
cmss13-devs/cmss13-pve pull request #514
Opened 2024-10-22 04:02 UTC by GriffinMan4455

# About the pull request

Lets marines take the identifier off a dead buddie's tags after just 30 seconds of them being dead.

Tested, works fine

Remember: something that is self-evident to you might not be to others. Explain your rationale fully, even if you feel it goes without saying. -->

# Explain why it's good for the game

Stinky PvP thing where you can only remove them after five minutes since they have like revives and stuff but we don't have that

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
qol: Dogtags removable after 30 seconds
/:cl:

2024-10-22 20:50 UTC, DexterDude approved these changes

2024-10-23 05:13 UTC, Doubleumc requested changes

2024-10-23 05:13 UTC, Doubleumc commented on code/modules/mob/living/carbon/human/life.dm
> +				if(life_tick > 0.5 && timeofdeath && (timeofdeath < 0.5 || world.time - timeofdeath > revive_grace_period) && !issynth(src)) //We are dead beyond revival, or we're junk mobs spawned like the clow
```suggestion
				if(life_tick > 5 && timeofdeath && (timeofdeath < 5 || world.time - timeofdeath > revive_grace_period) && !issynth(src)) //We are dead beyond revival, or we're junk mobs spawned like the clowns on the clown shuttle
```
This change doesn't help w/r/t dogtags.

2024-10-23 05:13 UTC, Doubleumc commented on code/modules/mob/living/carbon/human/human_defines.dm
> +	var/revive_grace_period = 30 SECONDS //30 Seconds
```suggestion
	var/revive_grace_period = 5 MINUTES //5 minutes
```
While this *works*, I'd suggest removing the undefibbable check for dogtags altogether.

You can find the checks in `human_stripping.dm`:
https://github.com/cmss13-devs/cmss13-pve/blob/1ad2ce94ac72293a10b3cae710b04e87a99688b7/code/modules/mob/living/carbon/human/human_stripping.dm#L212
https://github.com/cmss13-devs/cmss13-pve/blob/1ad2ce94ac72293a10b3cae710b04e87a99688b7/code/modules/mob/living/carbon/human/human_stripping.dm#L227

Removing the `!sourcemob.undefibbable` bit means it no longer cares if the subject is revivable or not.

2024-10-24 07:17 UTC, GriffinMan4455 commented on code/modules/mob/living/carbon/human/human_defines.dm
> +	var/revive_grace_period = 30 SECONDS //30 Seconds
I was gonna do this but updated from master, so I tried doing it locally but it...didn't *seem* to work? I'll push what I did and maybe I just SUCK, but I thought I did it right at least

2024-10-24 08:34 UTC, Doubleumc requested changes

2024-10-24 08:34 UTC, Doubleumc commented on code/modules/mob/living/carbon/human/human_stripping.dm
> +	if (!skillcheck(user, SKILL_POLICE, SKILL_POLICE_SKILLED) || sourcemob.stat != DEAD)
```suggestion
	if (sourcemob.stat != DEAD)
```

2024-10-24 08:34 UTC, Doubleumc commented on code/modules/mob/living/carbon/human/human_stripping.dm
>  		return
```suggestion
```

2024-10-24 08:57 UTC, GriffinMan4455 commented
You the goat UMC, everything works perfectly now! Tags are immediately grabbable on death o7

2024-10-24 21:01 UTC, Doubleumc approved these changes

2024-10-24 21:02 UTC, merged