UGL rounds expansion
cmss13-devs/cmss13-pve pull request #517
Opened 2024-10-23 18:02 UTC by BonniePandora

# About the pull request

Adds the M38 HEAP grenade round, a non-throwable explosive device designed to deliver maximum damage to targets it hits whilst retaining an appreciable casualty radius. This one uses the WPDP/CCDP green-cap for it's sprite.

Also adds the M108 canister round, another non-throwable grenade type that is meant to function much like shots from the U7 underbarrel shotgun or the XM51 breaching shotgun do. Great at obliterating structures, imparts reasonable knockback, but is still low-velocity buckshot and as such, doesn't hit as hard as a shotgun for combat purposes. This one uses the MFHS sprite as it was the only black-tip one I could see.

Along with that, I've adjusted some of the existing grenades to match with techmanual versions or be in-line with the designations.
M40 CCDP (aka WP but not as shit) -> M60 WPDP, white-cap
M40 HSDP -> M47 HSDP, same sprite
M40 HIDP -> M77 HIAM (High-explosive-Incendiary, Anti-Mobility), same sprite

Finally, I've added boxes for the types that were missing them from the above list, and adjusted the existing ones sprites to match the new designations

Credit to the code behind the M108 goes to [Koishi](https://github.com/cmss13-devs/cmss13-pve/pull/192) & [vero5123](https://github.com/cmss13-devs/cmss13-pve/pull/182/files)

# Explain why it's good for the game

With the canister round added, the U7 can largely be relegated to the shelf for any non-explosive breaching purposes needed by the marines.
The HEAP round offers them a much more powerful, instant-detonation round that suffers from a less damaging blast radius, rewarding direct hits on targets. (It still won't do _much_ to a crusher, but it's better than the HEDP at hurting it)
As for the remaining changes, it always struck me as really quite odd we had grenades that all shared the same designation but with vastly different purposes. This should help alleviate that somewhat.

# Testing Photographs and Procedure
Tested on my local server, no issues present
Compiled without issue too.

<details>
<summary>Screenshots & Videos</summary>

![image](https://github.com/user-attachments/assets/beb6d015-888d-42d5-a751-fd2b48af093c)
The M40 HEFA box is unchanged, this is just meant to have a roster of the various grenade types shown.
The CAN. box at the end is the M108 canister rounds, the limited sprite-space for the designations made putting the 4 character marker in the available space untenable.

</details>

# Changelog

:cl:
add: M38 HEAP grenade rounds.
add: M108 Canister grenade rounds
qol: Changed the M40 HSDP, CCDP & HIDP into their own discrete models instead (M47, M60, M77)
imageadd: Added new model_icons for the various new grenade designations
imageadd: Added new colour-bands for the new grenade designations
/:cl:

2024-10-24 04:51 UTC, XSlayer300 commented on code/game/objects/items/explosives/grenades/marines.dm
> +	name = "\improper M38 HEAP "
```suggestion
	name = "\improper M38 HEAP"
```
one cannot simply leave that space here.

2024-10-28 07:01 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-10-28 10:40 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-11-11 06:46 UTC, Doubleumc requested changes

2024-11-11 06:46 UTC, Doubleumc commented on code/game/objects/items/explosives/grenades/flashbang.dm
> +		if(skillcheck(H, SKILL_POLICE, SKILL_POLICE_DEFAULT))	//Default is 0 skill, should allow any and all to use
```suggestion
		if(skillcheck(H, SKILL_POLICE, SKILL_POLICE_SKILLED))
```
If you're changing this to make it usable by everyone, that's not necessary. This check doesn't prevent unskilled users from using it, its for reducing the flashbang effects on those with police training.

2024-11-11 06:46 UTC, Doubleumc commented on code/game/objects/items/explosives/grenades/marines.dm
> +		return
When possible, prefer early returns over branching. Creates less indenting overall and is easier to read.
```suggestion
	if(fuse_type == IMPACT_FUSE)
		to_chat(user, SPAN_WARNING("This grenade is set for impact-fusing!"))
		return

	set waitfor = 0
	if(shrapnel_count)
		create_shrapnel(loc, shrapnel_count, , ,shrapnel_type, cause_data)
	apply_explosion_overlay()
	cell_explosion(loc, explosion_power, explosion_falloff, falloff_mode, null, cause_data)
	qdel(src)
```

2024-11-11 06:46 UTC, Doubleumc commented on code/game/objects/items/explosives/grenades/marines.dm
> +			qdel(src)
Early returns.
```suggestion
	if(fuse_type != IMPACT_FUSE)
		return

	var/detonate = TRUE
	if(isobj(hit_atom) && !rebounding)
		detonate = FALSE
	if(isturf(hit_atom) && hit_atom.density && !rebounding)
		detonate = FALSE
	if(active && detonate) // Active, and we reached our destination.
		if(shrapnel_count)
			create_shrapnel(loc, shrapnel_count, , ,shrapnel_type, cause_data)
			sleep(1) //so that mobs are not knocked down before being hit by shrapnel. shrapnel might also be getting deleted by explosions?
		apply_explosion_overlay()
		if(explosion_power)
			cell_explosion(loc, explosion_power, explosion_falloff, falloff_mode, last_move_dir, cause_data)
		qdel(src)
```

2024-11-11 06:46 UTC, Doubleumc commented on code/game/objects/items/explosives/grenades/marines.dm
> +	dual_purpose = TRUE
Why is this being set in `New()`? If you want it to have `dual_purpose = TRUE` on creation, may as well put it in the definition.

2024-11-11 06:46 UTC, Doubleumc commented on icons/obj/items/weapons/grenade.dmi
Lots of issues with icon states animating to clearly wrong and probably wrong frames. Looks like its all the `..._active` states. `grenade_active`, `grenade_hefa_active`, etc. Can see it clearly in the icon diff: https://github.com/cmss13-devs/cmss13-pve/pull/517/checks?check_run_id=32767999933

2024-11-11 09:45 UTC, BonniePandora commented on code/game/objects/items/explosives/grenades/marines.dm
> +	dual_purpose = TRUE
Thought behind putting it on the New() one was so the base definition has it flagged as FALSE for all the other ones to inherit from, rather than having to go through and make every other one flagged as FALSE

2024-11-11 19:27 UTC, BonniePandora commented on icons/obj/items/weapons/grenade.dmi
Compared the sprites against those showing issue on icondiffbot, the sprites themselves are showing correctly. I think the bot's freaking out over the fact many of those changes are going from an animated state to a single-frame one and is pulling the following sprites from the sheet for some godforsaken reason. 
Can see it with the metal_foam_active one, where it shows the stick grenade and CLF phosphorus grenade sprites.
![image](https://github.com/user-attachments/assets/d34a5881-3a1f-4411-a65b-d9946b4b7538)
![image](https://github.com/user-attachments/assets/a2ced681-1913-4674-878b-c491be41ca64)

2024-11-11 19:34 UTC, Doubleumc commented on code/game/objects/items/explosives/grenades/marines.dm
> +	dual_purpose = TRUE
Currently, that is already happening. Since all subtypes of `high_explosive` either don't define their own `New()` or also run their parent's version (the `..()` bit), they all have `dual_purpose = TRUE`.

2024-11-11 19:34 UTC, Doubleumc commented on icons/obj/items/weapons/grenade.dmi
The bot is wrong. Looks fine in the files and in the game.

2024-11-11 19:57 UTC, BonniePandora commented on code/game/objects/items/explosives/grenades/flashbang.dm
> +		if(skillcheck(H, SKILL_POLICE, SKILL_POLICE_DEFAULT))	//Default is 0 skill, should allow any and all to use
Addressed in the latest commit

2024-11-11 19:58 UTC, BonniePandora commented on code/game/objects/items/explosives/grenades/marines.dm
> +	dual_purpose = TRUE
Addressed in the latest commit

2024-11-26 03:30 UTC, Doubleumc approved these changes
Code good.

Confirming to myself that the icon diff bot is WRONG, and that the icon states are fine.

2024-12-07 18:03 UTC, merged