Quick Fix: Frequencies
cmss13-devs/cmss13-pve pull request #527
Opened 2024-10-27 22:47 UTC by KoishiVibe

# Summary
- Almayer is now Marine. This eliminates an oddity with shortwaves.
- The Solar Devils now have their own tacfreq, SOLDEV. For some reason they were on the Marine Raider frequency?
- THe Solar Devils headset has five keyspaces which should cover any reasonable combination of prop commo.

2024-10-27 22:47 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-10-27 22:48 UTC, KoishiVibe reviewed
might scrap the custom headsets and stuff, move it all over to common marine band in case the gamemaster spawns prop reinforcements??? idk.

2024-11-11 19:09 UTC, AndroBetel requested changes

2024-11-11 19:09 UTC, AndroBetel commented on code/game/jobs/job/marine/squads.dm
> +	radio_freq = SOLDEV_FREQ
if anything, this squad should be removed for causing confusion since its a pvp ert squad

2024-11-13 21:47 UTC, KoishiVibe commented on code/game/jobs/job/marine/squads.dm
> +	radio_freq = SOLDEV_FREQ
Might be useful in certain cases for raiders to have their own tacfreq

2024-11-19 06:25 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-02-25 01:18 UTC, closed without merging