UA Civilian Overhaul
cmss13-devs/cmss13-pve pull request #529
Opened 2024-10-29 18:52 UTC by AmoryBlaine

Removes PvP survivor presets in favour of more generic colonist presets in order to provide an aesthetically coherent roster of props to the setting, largely building off the props added in the UPP update.
- Adds shirtless variants of all businesswear
- Adds khaki and grey businesswear
- Adds code around assignment name allowing variance for the same prop
- Drops security belt storage capacity

2024-11-07 06:30 UTC, XSlayer300 commented on code/modules/projectiles/guns/rifles.dm
> +	desc = "Predecessor to the M41A pulse rifle still utilized by the UA's Colonial Guard and various other organizations . Aside from its 10x24 chambering, the 'Harrington' rifle is largely considered
```suggestion
	desc = "Predecessor to the M41A pulse rifle still utilized by the UA's Colonial Guard and various other organizations . Aside from its 10x24 chambering, the 'Harrington' rifle is largely considered to be in every metric the polar opposite of the M41A."
```
```suggestion
	desc = "A predecessor to the M41A pulse rifle still utilized by the UA's Colonial Guard and various other organizations. Aside from its 10x24mm chambering, the 'Harrington' rifle is largely considered to be in every metric the polar opposite of the M41A; featuring an obsolete three-round burst mode, lower magazine size, and it uses an integrated shotgun attachment."
```

2024-11-11 19:56 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-11-12 06:10 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-11-13 16:35 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-11-13 22:53 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-11-14 01:08 UTC, Doubleumc requested changes
Other than that, code good.

2024-11-14 01:08 UTC, Doubleumc commented on code/modules/gear_presets/_select_equipment.dm
> +	var/random_satchel= rand(1,3)
```suggestion
	var/random_satchel = rand(1,3)
```

2024-11-14 01:08 UTC, Doubleumc commented on code/modules/gear_presets/_select_equipment.dm
> +	var/random_civilian= rand(1,9)
```suggestion
	var/random_civilian = rand(1,9)
```

2024-11-14 01:08 UTC, Doubleumc commented on code/modules/gear_presets/_select_equipment.dm
> +	var/random_civilian_jacket= rand(1,12)
```suggestion
	var/random_civilian_jacket = rand(1,12)
```

2024-11-14 01:08 UTC, Doubleumc commented on code/modules/gear_presets/_select_equipment.dm
> +	var/random_worker= rand(1,7)
```suggestion
	var/random_worker = rand(1,7)
```

2024-11-14 01:08 UTC, Doubleumc commented on code/modules/gear_presets/_select_equipment.dm
> +	var/random_worker_jacket= rand(1,4)
```suggestion
	var/random_worker_jacket = rand(1,4)
```

2024-11-14 01:08 UTC, Doubleumc commented on code/modules/gear_presets/_select_equipment.dm
> +	var/random_business_outfit= rand(1,4)
```suggestion
	var/random_business_outfit = rand(1,4)
```

2024-11-14 01:08 UTC, Doubleumc commented on code/modules/gear_presets/_select_equipment.dm
> +	var/random_professionalwear= rand(1,4)
```suggestion
	var/random_professionalwear = rand(1,4)
```

2024-11-14 01:08 UTC, Doubleumc commented on code/modules/gear_presets/_select_equipment.dm
> +	var/random_tie= rand(1,5)
```suggestion
	var/random_tie = rand(1,5)
```

2024-11-14 01:08 UTC, Doubleumc commented on code/modules/gear_presets/_select_equipment.dm
> +	var/random_boilersuit= rand(1,4)
```suggestion
	var/random_boilersuit = rand(1,4)
```

2024-11-14 01:08 UTC, Doubleumc commented on icons/obj/items/weapons/guns/ammo_by_faction/uscm.dmi
Purpose for removing the unnamed "FIX ME" icon state?

It is useful in that it gets displayed whenever there's an invalid icon state.

2024-11-14 18:44 UTC, AmoryBlaine commented on icons/obj/items/weapons/guns/ammo_by_faction/uscm.dmi
I have no idea why, but for some reason, whenever the M20A would load a magazine, it would display the FIX ME icon. I deleted it, and the sprite worked properly. I kinda assumed I accidentally carried it over from my own DMI file for guns and that was the issue with it. Idk why me deleting it fixed the issue though

2024-11-14 22:08 UTC, Doubleumc commented on icons/obj/items/weapons/guns/ammo_by_faction/uscm.dmi
The unnamed icon state is used whenever an invalid icon state is set. If you saw the "FIX ME" icon, that means something is trying to display a bad/nonexistent icon state. Deleting the "FIX ME" doesn't fix the bad icon state, it just makes it invisible.

Here you're setting the M20's `bonus_overlay` to "m20a_mag_overlay". No such icon state exists.
https://github.com/cmss13-devs/cmss13-pve/pull/529/files#diff-be3d4d73b5f70c3f2a08c13827f188668a81c4ac2ed344726edc3af4aba3b6d9R448

You may or may not want a `bonus_overlay` at all. They're meant for displaying the extra bits of, say, extended mags.
https://github.com/cmss13-devs/cmss13-pve/blob/dd4b994fa20a62cdcacfe45f2c64a2aa70a8c7d5/code/modules/projectiles/ammunition.dm#L12

You should restore the "FIX ME" icon, and either create a "m20a_mag_overlay" icon or remove the `bonus_overlay` entirely.

2024-11-14 22:33 UTC, AmoryBlaine commented on icons/obj/items/weapons/guns/ammo_by_faction/uscm.dmi
Oh, thanks, yeah I'll remove that. I was gonna add more stuff but didn't want it in this PR since it's not necessary

2024-11-27 22:03 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-11-28 01:44 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-11-30 19:06 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-12-01 23:50 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-12-02 00:14 UTC, Doubleumc approved these changes

2024-12-02 00:14 UTC, merged