Tech-manual compliant attachment (and a sovl one)
cmss13-devs/cmss13-pve pull request #531
Opened 2024-10-30 14:30 UTC by BonniePandora

# About the pull request

Adds the mentioned scope from the tech manual; the AN/RVS-52, only fits on the mk1
Also adds a new subtype of the magnetic-harness; the two point sling! Now even juggalo marines can retain their weapons upon dropping, provided they have their back-slot free of course...
Fits the mk1, M120, M4RA-R2 and the M240.
Swaps the sprite used by the B8 smart-scope to the current goofy ahh PVP one, as befits a goofy ahh scope, the old one now used by the RVS. The sling sprites are a mix of a repurposed R4T one and one I whipped up quickly, there's room for improvement on the latter part.

Planned feature was to have the new optic have a toggle to swap between IR and visible-light modes for when scoped in, but overlay code is a nightmare to try wrap my head around currently. May come back to it when I understand it better

# Explain why it's good for the game

Finally offers some variation on what to stick on your guns besides a rail-flashlight. They aren't currently spawned in as standard anywhere, so it's up to GM's to provide as they see fit. _May_ put a box of (4 or so) slings in the armoury along with a single scope, remains to be considered.
Scope range is also up for adjustment if GM's consider it to be too much zoom to have, I certainly think I'll reduce it when I get around to adding the night-vision mode functionality to it.

# Testing Photographs and Procedure
Tested on local, worked fine but for the night-vision toggle which is no longer included in the scopes code.

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: AN/RVS-52 CCD Television Sight System attachment
add: Two-point sling system attachment
imageadd: New sprite for the B8, ported from PVP so the old one could be used for the new scope
/:cl:

2024-10-31 15:42 UTC, XSlayer300 commented on code/modules/projectiles/gun_attachables.dm
> +		to_chat(usr, SPAN_NOTICE("Optic mode switched to infra-red"))
```suggestion
		to_chat(usr, SPAN_NOTICE("Optic mode switched to infra-red."))
```

2024-10-31 15:43 UTC, XSlayer300 commented on code/modules/projectiles/gun_attachables.dm
> +		to_chat(usr, SPAN_NOTICE("Optic mode switched to visible-light"))
```suggestion
		to_chat(usr, SPAN_NOTICE("Optic mode switched to visible-light."))
```

2024-10-31 16:08 UTC, BonniePandora commented on code/modules/projectiles/gun_attachables.dm
> +		to_chat(usr, SPAN_NOTICE("Optic mode switched to visible-light"))
All this is stuff pertaining to optic modes & such is being gutted for the time being with the next commit.
I'll keep this in mind when I get around to trying it again though

2024-11-01 15:53 UTC, Doubleumc requested changes

2024-11-01 15:53 UTC, Doubleumc commented on code/modules/projectiles/gun_attachables.dm
> +	var/dynamic_aim_slowdown = SLOWDOWN_ADS_SCOPE
If you want `dynamic_aim_slowdown` to do anything, you need to define how it effects the weapon. For example in the mini IFF scope, which also declares a `dynamic_aim_slowdown` var, it will apply or remove a movement modifier whenever zoomed in or not. You'd want a version of that for your scope as well, like so:
```suggestion
	var/dynamic_aim_slowdown = SLOWDOWN_ADS_SCOPE
	
/obj/item/attachable/scope/pve/apply_scoped_buff(obj/item/weapon/gun/G, mob/living/carbon/user)
	. = ..()
	if(G.zoom)
		G.slowdown += dynamic_aim_slowdown
/obj/item/attachable/scope/pve/remove_scoped_buff(mob/living/carbon/user, obj/item/weapon/gun/G)
	G.slowdown -= dynamic_aim_slowdown
	..()
```

2024-11-01 16:25 UTC, BonniePandora commented on code/modules/projectiles/gun_attachables.dm
> +	var/dynamic_aim_slowdown = SLOWDOWN_ADS_SCOPE
I see, I'd been trying to use the apply_scoped_buff proc prior for my attempts to apply a night-vision overlay when using the scope if it was toggled to such but VSC kept screaming about duplicate procs or similar.

2024-11-01 18:08 UTC, BonniePandora commented on code/modules/projectiles/gun_attachables.dm
> +	var/dynamic_aim_slowdown = SLOWDOWN_ADS_SCOPE
Added now

2024-11-05 03:04 UTC, Doubleumc submitted a review, later dismissed

2024-11-06 17:02 UTC, DexterDude commented
This is going to need to be handled carefully. I don't have super strong opinions about the scope, it can be the platoon sergeant's thing, but I don't want the sling to be anything more than cosmetic.

2024-11-06 17:10 UTC, BonniePandora commented
> This is going to need to be handled carefully. I don't have super strong opinions about the scope, it can be the platoon sergeant's thing, but I don't want the sling to be anything more than cosmetic.

Slings gone, just removed it from the PR.
Scope gives a 3 tile boost to vision, no NV and slowdown when used

2024-11-25 01:42 UTC, Doubleumc approved these changes

2024-11-25 19:27 UTC, XSlayer300 commented on code/modules/projectiles/gun_attachables.dm
> +	name = "AN/RVS-52 CCD Television Sight System"
```suggestion
	name = "AN/RVS-52 CCD television sight system"
```

2024-11-26 03:31 UTC, Doubleumc approved these changes

2024-11-27 22:03 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-11-30 17:07 UTC, BonniePandora commented
Should be the final commit to the PR, adjusts what the scope can fit on as per feedback

2024-12-27 20:43 UTC, Doubleumc approved these changes

2025-01-03 20:46 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-01-03 21:26 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-01-16 02:21 UTC, Doubleumc approved these changes

2025-01-21 10:50 UTC, merged