Kill all MK2s (on maps)
cmss13-devs/cmss13-pve pull request #551
Opened 2024-11-14 00:48 UTC by AmoryBlaine

2024-11-15 03:17 UTC, private-tristan commented on maps/map_files/Ice_Colony_v3/Shivas_Snowball.dmm
>  /obj/item/ammo_magazine/rifle,
There's probably other Mk2 mags scattered everywhere but I noticed these three
```suggestion
/obj/item/ammo_magazine/rifle/m41aMK1,
/obj/item/ammo_magazine/rifle/m41aMK1,
/obj/item/ammo_magazine/rifle/m41aMK1,
```

2024-11-16 22:09 UTC, Drulikar requested changes
Fill out the PR template. Why are you making a PR with no description?

Labeler workflow doesn't even have handling for a blank PR.

2024-11-26 03:47 UTC, Doubleumc approved these changes

2024-11-27 22:04 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-12-26 19:08 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-12-26 20:24 UTC, Drulikar commented
You still have missing changelog tag because you have an invalid changelog that will not process. Cannot intermix emjois and non-emojis for CL do both the same way. I have fixed this for you.

2024-12-26 20:29 UTC, Drulikar requested changes
Do not leave unresolved map conflict markers in maps: 
![image](https://github.com/user-attachments/assets/53beb26a-cdfb-4fba-829c-0206f1ae493a)

Looks like there's 68 (not nice) of them: https://github.com/cmss13-devs/cmss13-pve/actions/runs/12507544712/job/34895655885?pr=551#step:7:1068

2024-12-28 03:36 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-01-15 02:15 UTC, closed without merging