USCM Aux Roles & Alt Camo Overhaul
cmss13-devs/cmss13-pve pull request #559
Opened 2024-11-17 08:02 UTC by AmoryBlaine

Changes to most existing remaining marine prop roles, and simplification of camo variety for the sake of a solid aesthetic for the marines.

2024-11-17 18:35 UTC, AndroBetel commented on code/modules/gear_presets/_select_equipment.dm
> +			new_human.equip_to_slot_or_del(new /obj/item/clothing/shoes/stompers(new_human), WEAR_FEET)
would be cool if these were mega rare

2024-11-21 20:37 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-11-21 20:39 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-11-26 03:09 UTC, Doubleumc requested changes

2024-11-26 03:09 UTC, Doubleumc commented on icons/mob/humans/onmob/feet.dmi
Marked as changed but IconDiffBot says no changed icons. This could unnecessarily trigger conflicts with other PRs. Can get a clean copy here: https://github.com/cmss13-devs/cmss13-pve/blob/master/icons/mob/humans/onmob/feet.dmi

2024-11-26 03:09 UTC, Doubleumc commented on code/modules/gear_presets/uscm.dm
> +	role_comm_title = "SQSGT"
```suggestion
	role_comm_title = "SqSgt"
```
There's not really any standard for comm titles, the capitalization is all over the place -- but I find things more readable when only the start of each word is capitalized. Makes it clearer when something is a shortened word vs. an acronym.

2024-11-26 03:09 UTC, Doubleumc commented on code/modules/gear_presets/uscm.dm
> +	role_comm_title = "COMTECH"
```suggestion
	role_comm_title = "ComTech"
```

2024-11-26 03:09 UTC, Doubleumc commented on code/modules/gear_presets/uscm.dm
> +	role_comm_title = "SCTSGT"
```suggestion
	role_comm_title = "SctSgt"
```

2024-11-26 03:09 UTC, Doubleumc commented on code/modules/gear_presets/uscm.dm
> +	role_comm_title = "SQSGT"
```suggestion
	role_comm_title = "SqSgt"
```

2024-11-26 03:09 UTC, Doubleumc commented on code/modules/gear_presets/uscm.dm
> +	role_comm_title = "SCTSGT"
```suggestion
	role_comm_title = "SctSgt"
```

2024-11-26 03:09 UTC, Doubleumc commented on code/modules/gear_presets/uscm.dm
> +	role_comm_title = "COMTECH"
```suggestion
	role_comm_title = "ComTech"
```

2024-11-26 03:09 UTC, Doubleumc commented on code/modules/gear_presets/uscm.dm
> +	role_comm_title = "SPC"
```suggestion
	role_comm_title = "Spc"
```

2024-11-26 03:09 UTC, Doubleumc commented on code/modules/gear_presets/uscm.dm
> +	role_comm_title = "SCTSNPR"
```suggestion
	role_comm_title = "SctSnpr"
```
Possible confusion of "Sct" being "Scout" or "Section", but I can't think of anything better.

2024-11-26 03:09 UTC, Doubleumc commented on code/modules/gear_presets/uscm.dm
> +	role_comm_title = "SCTSNPR"
```suggestion
	role_comm_title = "SctSnpr"
```

2024-11-26 03:11 UTC, AmoryBlaine commented on code/modules/gear_presets/uscm.dm
> +	role_comm_title = "SQSGT"
This is useful, I was moving towards all caps. Will move all comm titles towards this format going forward

2024-11-26 03:15 UTC, AmoryBlaine commented on code/datums/skills/uscm.dm
> +		SKILL_SPEC_WEAPONS = SKILL_SPEC_ALL,
Previously, they'd have to learn each individual specialist weapon, ideally this lets them use all of them, whereas the RPG and sniper being unskilled means anyone can use them, period.

2024-11-27 22:03 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-11-28 01:44 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-11-30 19:06 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-12-01 23:50 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-12-02 00:18 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-12-02 00:28 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-12-23 06:08 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-12-23 21:27 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-12-26 18:55 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-12-26 19:59 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2024-12-28 03:32 UTC, merged