Dropship Weapons Reflavor
cmss13-devs/cmss13-pve pull request #564
Opened 2024-11-21 05:53 UTC by KoishiVibe

# Summary
- Revamps all of the flavor text. Everything is now AGM-220 variants, Mk.10 warhead options, etc, as specced in the TMan.
- Replaces the BLU-200 sprite with the napalm sprite in the interim just to keep things visually nominally similar? Maybe I'll replace all the sprites with the same one with different colors or something.
- Generally kills some PVP13 weirdness and also the GAU-8 IN SPAAAAAAAAAAACE expy.
- Modifies two FS options to make them more clear as to what they are. GAU and Heavy GAU are now 25mm Multipurpose Strike and 25mm Armorpiercing Strike. 

# Rationale
- We love lore compliance . .. ... More seriously, this removes weirdness with two different GAUs, and kills weird PVP13 flavor text.
- its also a nice QOL to know the differences between the two gun options at a glance I think.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog
:cl:
add: Nominally TMan compliant flavortext. Look, there's not a lot to work with here, okay?
del: Basically all of the old names of dropship weapons.
del: The BLU-200 sprite is no longer used. In the interim, the napalm sprite.
qol: GAU and Heavy GAU are now 25mm Multipurpose Strike and 25mm Armorpiercing Strike respectively.
/:cl:

2024-11-22 22:10 UTC, AndroBetel requested changes

2024-11-22 22:10 UTC, AndroBetel commented on code/modules/admin/game_master/extra_buttons/fire_support_menu.dm
> +#define MISC_ORDNANCE list("Laser", "Minirocket", "Incendiary Minirocket",  "Sentry Drop", "25mm Burst", "25mm Barrage")
says "25mm Burst" but earlier its "25mm Skirmish"

2024-11-22 23:07 UTC, KoishiVibe commented on code/modules/admin/game_master/extra_buttons/fire_support_menu.dm
> +#define MISC_ORDNANCE list("Laser", "Minirocket", "Incendiary Minirocket",  "Sentry Drop", "25mm Burst", "25mm Barrage")
GUH
this is why you dont do last minute changes aeugh aeugh aeugh

2024-11-22 23:11 UTC, KoishiVibe commented on code/modules/admin/game_master/extra_buttons/fire_support_menu.dm
> +#define MISC_ORDNANCE list("Laser", "Minirocket", "Incendiary Minirocket",  "Sentry Drop", "25mm Burst", "25mm Barrage")
actually... shiiit, this is why i gotta read code more closely.

2024-11-23 01:32 UTC, AndroBetel approved these changes

2024-11-23 01:33 UTC, merged