Alternative nuclear deployment method
cmss13-devs/cmss13-pve pull request #572
Opened 2024-11-28 09:05 UTC by BonniePandora

# About the pull request

Adds a new way to deploy a nuclear device onto a station/colony without having to lug around a really stupid looking jury-rigged missile. Conveniently sized to be carryable on the back by someone.

# Explain why it's good for the game

I don't think highly of the legacy PVP manner in which nukes are deployed, the marines on the Garrow are properly equipped marines so why is it they use a half-assed jury-rigged nuclear tipped missile as their method of glassing an area in nuclear fire? The nuclear landmine is mentioned in the tech-manual as one of three deployment methods the USCMC uses for it's atomic weapons. 

The undeployed item sprite could likely do with some further work but I am _not_ the greatest of spriters.

# Testing Photographs and Procedure
Works on local, compiles fine, no issues I could see when testing.

<details>
<summary>Screenshots & Videos</summary>

![image](https://github.com/user-attachments/assets/151fb9a2-8e5a-4fb2-8487-e255c3b43da5)

The deployed warhead with safety removed & timer ticking down
</details>

# Changelog

:cl:
add: Adds the Mk-214 Tactical Atomic Demolition Munition, an alternative way of nuking a site from the ground
imageadd: Adds new sprites for the TADM, worn, loose & undeployed and deployed
/:cl:

2024-11-28 09:53 UTC, AndroBetel commented on code/game/machinery/nuclearbomb.dm
> +/obj/item/stack/ADM
why `/obj/item/stack` ?

2024-11-28 09:53 UTC, AndroBetel commented on code/game/machinery/nuclearbomb.dm
> +
unused var?

2024-11-28 09:53 UTC, AndroBetel commented on code/game/machinery/nuclearbomb.dm
> +	density = TRUE
most of these variables are inherited from parent class, no need to redefine them for the same values

2024-11-28 12:20 UTC, BonniePandora commented on code/game/machinery/nuclearbomb.dm
> +/obj/item/stack/ADM
Initially copied the code from how the deployable barricades worked to get this working, will see if making it not a stack subtype will play nicely

2024-11-28 12:51 UTC, BonniePandora commented on code/game/machinery/nuclearbomb.dm
> +/obj/item/stack/ADM
This & other points addressed in latest commit

2024-11-28 17:58 UTC, AndroBetel commented on code/game/machinery/nuclearbomb.dm
> +			to_chat(user, SPAN_WARNING("There is already \a [B] in this direction!"))
is this really needed since its not a cade and can be deployed anyway

2024-11-28 17:59 UTC, AndroBetel commented on code/game/machinery/nuclearbomb.dm
> +	var/obj/structure/machinery/nuclearbomb/ADM/planted = new(user.loc)
maaaaybe place it on turf in front of user? should be easy enough to code

2024-11-28 18:41 UTC, BonniePandora commented on code/game/machinery/nuclearbomb.dm
> +			to_chat(user, SPAN_WARNING("There is already \a [B] in this direction!"))
Sorted in latest commit along with point below

2024-11-30 13:57 UTC, AndroBetel requested changes

2024-11-30 13:57 UTC, AndroBetel commented on code/game/machinery/nuclearbomb.dm
> +	planted.forceMove(get_turf(T))
any reason to not spawn it at `T` turf?

2024-11-30 13:57 UTC, AndroBetel commented on code/game/machinery/nuclearbomb.dm
> +	var/turf/T = get_step(user, user.dir)
single letter vars here and below

2024-11-30 16:52 UTC, BonniePandora commented on code/game/machinery/nuclearbomb.dm
> +	planted.forceMove(get_turf(T))
Okay, should be sorted now.

2024-11-30 18:52 UTC, AndroBetel commented on code/game/machinery/nuclearbomb.dm
> +	for(var/obj/O in Tile)
```suggestion
	for(var/obj/Obj in Tile)
```

2024-11-30 18:52 UTC, AndroBetel commented on code/game/machinery/nuclearbomb.dm
> +		if(O.density)
```suggestion
		if(Obj.density)

2024-11-30 18:52 UTC, AndroBetel commented on code/game/machinery/nuclearbomb.dm
> +	for(var/mob/M in Tile)
```suggestion
	for(var/mob/Mob in Tile)
```

2024-11-30 19:02 UTC, AndroBetel approved these changes

2024-11-30 19:02 UTC, merged