More movielike remote-flight console
cmss13-devs/cmss13-pve pull request #593
Opened 2024-12-06 23:44 UTC by BonniePandora

# About the pull request

Adds in a new method of remotely calling a dropship down from the orbiting vessel, should the deployed team lack an APC, LT on overwatch, or the GM wished to simply nuke the existing LZ computers for being the lame-ass things they are.

Code probably has a lot of room for improvement, but it was done in the course of two nights and I'm far from a carreer coder.

# Explain why it's good for the game

Much more feasable manner of remotely calling in a dropship from the overhead vessel that stays truer to the film, what with Lance remote-piloting the backup dropship down via something similar.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

![image](https://github.com/user-attachments/assets/26c6a85e-2eeb-41f0-b7e6-561829d110f0)

![image](https://github.com/user-attachments/assets/f3a7ca67-ae2f-4b9e-bcfc-c3d67cbda9bd)

![image](https://github.com/user-attachments/assets/238f4c60-c108-4fb8-b393-3a903f80566f)
Ignore the icon-state names in this last one, they were adjusted since the screencap was taken
</details>

# Changelog

:cl:
add: Adds in a new method of remotely calling in the dropship; a movielike laptop in a carry case.
imageadd: Sprites for the above, item, deployed & off/inactive and deployed & on/active
/:cl:

2024-12-19 00:56 UTC, Doubleumc requested changes
Otherwise, code good.

2024-12-19 00:56 UTC, Doubleumc commented on code/modules/shuttle/computers/dropship_computer.dm
> +	var/exproof = TRUE
```suggestion
```
`exproof` has meaning for `/obj/structure`, but not for `/obj/item` subtypes. If you want to make it explosion immune, redefine this type's `ex_act()` proc to do nothing. Example:
```
/obj/item/device/flight_laptop/ex_act()
	return
```

2024-12-19 00:56 UTC, Doubleumc commented on code/modules/shuttle/computers/dropship_computer.dm
> +	if(over_object == usr && Adjacent(usr) && has_special_table_placement)
```suggestion

/obj/structure/machinery/computer/shuttle/dropship/flight/laptop/MouseDrop(over_object)
	if(over_object == usr && Adjacent(usr))
```
Defining and using `has_special_table_placement` isn't useful in this case. You're defining something that will always be true, then checking if its true.

2024-12-28 18:22 UTC, BonniePandora commented on code/modules/shuttle/computers/dropship_computer.dm
> +	if(over_object == usr && Adjacent(usr) && has_special_table_placement)
Both addressed in latest commit

2025-01-03 20:46 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2025-01-03 21:05 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-01-16 04:24 UTC, Doubleumc approved these changes

2025-01-17 19:47 UTC, merged