Grenade overhaul part 2, the quest for more havoc
cmss13-devs/cmss13-pve pull request #594
Opened 2024-12-08 18:45 UTC by BonniePandora

# About the pull request

Overhauls the grenade packet icon system, they now share a similar one to how grenade boxes work. Packets once emptied can be folded flat and M40-hull type ones now hold five grenades as standard. Ones that hold M15s, SEBBs, etc etc, retain a capacity of three.
The M60 WPSI & M77 HIAM have both recieved dual-fusing functionality, detonating on impact if fired from a UGL. Beware dinking something in the face with one of those loaded.

Two new grenades added, along with corresponding packets. No grenade boxes for either (yet?)

- M230 LLRB grenade; a less-than-lethal baton round that will shatter on impact after hitting a target, imparting significant knockback to them and putting them on their arse for a short spell. Mostly blue-plastic body.

- M72A2 HIPF starshell grenade; a para-flare grenade for marines to light up areas. Description flavoured as being an advancement on the tech-manual mentioned A1 model and capable of embedding into roofs where it illuminates too. (I did not wish to deal with the jank of roof code and such, ergo this solution). Yellow cap, yellow band on the hull to designate it as launcher-fired only. Available from the gear vendors aboard the Garrow & Rover

# Explain why it's good for the game

Catches the last of the changes I wanted to impliment grenade-wise without feature-creeping the prior grenade overhaul PR.
Packet folding is just... Why wasn't it like that from the get-go when they were added? **WHY?**
The two new grenade types offer up both a less-than-lethal option & illumination round for marines to use.

# Testing Photographs and Procedure
Tested locally, all works as intended. Compiles without issue.

<details>
<summary>Screenshots & Videos</summary>

![image](https://github.com/user-attachments/assets/696fb200-5a50-49b1-b168-8a26e3ec3a00)

![image](https://github.com/user-attachments/assets/3f48e693-1ef4-42aa-9cb9-b38c24c81526)

</details>

# Changelog

:cl:
add: Adds the M230 LLRB & M72A2 HIPF grenades
qol: Grenade packets can be folded flat once emptied
qol: Packet sprites overhauled with overlays & such on a base sprite
balance: The M60 WPSI & M77 HIAM now both have dual-fusing functionality
spellcheck: 'box of flashlight' -> 'box of flashlights' in gear vendor
imageadd: Sprite for the M72A2 grenade
/:cl:

2024-12-17 20:41 UTC, Doubleumc requested changes

2024-12-17 20:45 UTC, BonniePandora commented on icons/obj/structures/mortar.dmi
...That wasn't intentional, no. I didn't open that sprite up at all whilst working on this. Not sure _how_ it's ended up changed nor what exactly is changed on it.

2024-12-17 20:55 UTC, BonniePandora commented on code/modules/projectiles/gun_attachables.dm
> +	if(!breech_open && has_breech)
This & other requested code changes addressed in latest commit

2024-12-17 20:57 UTC, BonniePandora commented on icons/obj/structures/mortar.dmi
Okay, compared the supposedly changed states in the PR against the main branch mortar.dmi, there is _no_ difference between them. Not sure why icondiffbot is flagging it.

2024-12-27 08:39 UTC, cm13-github commented
This pull request has conflicts, please resolve those before we can evaluate the pull request.

2024-12-27 20:58 UTC, Doubleumc commented on icons/obj/structures/mortar.dmi
I agree that visually, they're identical. I'm satisfied that this is merely an iconbot hiccup.

2024-12-27 20:58 UTC, Doubleumc approved these changes

2024-12-27 23:01 UTC, cm13-github commented
Conflicts have been resolved. A maintainer will review the pull request shortly.

2025-01-16 04:22 UTC, Doubleumc submitted a review, later dismissed

2025-01-20 20:37 UTC, AndroBetel requested changes

2025-01-20 20:37 UTC, AndroBetel commented on code/game/objects/items/explosives/grenades/chem_grenade.dm
> +/*	Commented out in favour of teargas that isn't handled via contact
remove, do not comment out

2025-01-20 20:37 UTC, AndroBetel commented on code/game/objects/items/explosives/grenades/grenade.dm
> +/*
ditto

2025-01-20 20:37 UTC, AndroBetel commented on code/datums/ammo/shrapnel.dm
> +		BULLET_TRAIT_ENTRY(/datum/element/bullet_trait_incendiary/heavy)
instead of making a new bullet trait, try something like 
```suggestion
		BULLET_TRAIT_ENTRY(/datum/element/bullet_trait_incendiary/heavy, reagent = /datum/reagent/napalm/blue)
```

2025-01-20 20:37 UTC, AndroBetel commented on code/game/objects/effects/effect_system/smoke.dm
> +		to_chat(creature, SPAN_WARNING("You're feel the sting of the tear gas!"))
your'mstve*

2025-01-21 02:28 UTC, BonniePandora commented on code/game/objects/items/explosives/grenades/chem_grenade.dm
> +/*	Commented out in favour of teargas that isn't handled via contact
Addressed in latest commit

2025-01-21 02:28 UTC, BonniePandora commented on code/game/objects/items/explosives/grenades/grenade.dm
> +/*
As above

2025-01-21 02:28 UTC, BonniePandora commented on code/game/objects/effects/effect_system/smoke.dm
> +		to_chat(creature, SPAN_WARNING("You're feel the sting of the tear gas!"))
And this one

2025-01-21 02:30 UTC, BonniePandora commented on code/datums/ammo/shrapnel.dm
> +		BULLET_TRAIT_ENTRY(/datum/element/bullet_trait_incendiary/heavy)
That trait's gonna be used by something else I'm working on for a different PR, should I still axe it even if I'll just be adding it back in later?

2025-01-21 10:44 UTC, AndroBetel commented on code/datums/ammo/shrapnel.dm
> +		BULLET_TRAIT_ENTRY(/datum/element/bullet_trait_incendiary/heavy)
the original trait was already intended with different reagents in mind (as i show you in my suggestion), and you copy it in its entirety without changing anything but reagent in proc definition

so you either want to change how that trait works (see damage boost trait for example) by adding new variable for reagent, or just use my suggestion here and whenever you wanna use it further

2025-01-21 10:58 UTC, BonniePandora commented on code/datums/ammo/shrapnel.dm
> +		BULLET_TRAIT_ENTRY(/datum/element/bullet_trait_incendiary/heavy)
Right, implimented as of latest commit. Yeah Idk what the hell I was doing when I made that initially if the parent trait was designed for... Modularity isn't quite the right word but something along those lines.

2025-01-21 11:45 UTC, AndroBetel approved these changes

2025-01-21 11:45 UTC, merged