Antiship Wording Tweak
cmss13-devs/cmss13-pve pull request #611
Opened 2024-12-16 23:24 UTC by KoishiVibe

# Summary
- Changes the wording of some player facing AI messages when the antiship panel is used.

# Explain why it's good for the game
- Swing High Hull Peircer Rockets??? What???
- Makes the AI sound a little calmer and more detached. Probably makes it tonally better.
- Impact reports are now less weirdly worded (what is DOT Damage???)

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: Added something
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
spellcheck: fixed a few typos
ui: changed something relating to user interfaces
code: changed some code
refactor: refactored some code
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
mapadd: added a new map or section to a map
maptweak: tweaked a map
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2024-12-17 22:50 UTC, Drulikar commented
Re failed checks, see https://github.com/cmss13-devs/cmss13-pve/actions/runs/12363197453/job/34504052202?pr=611#step:6:11
(`ad:` isn't valid should be `add:`)

2024-12-21 05:48 UTC, KoishiVibe commented
> Re failed checks, see https://github.com/cmss13-devs/cmss13-pve/actions/runs/12363197453/job/34504052202?pr=611#step:6:11 (`ad:` isn't valid should be `add:`)

done
forgot to do that the first time it failed lol

2024-12-21 07:39 UTC, Drulikar requested changes

2024-12-21 07:39 UTC, Drulikar commented on code/modules/admin/verbs/adminpanelweapons.dm
> +		addtimer(CALLBACK(GLOBAL_PROC, GLOBAL_PROC_REF(shipwide_ai_announcement), "ATTENTION: TRACKING INBOUND[quantity > 1 ? "S" : ""]. FIRING AIR DEFENSE. STANDBY FOR INTERCEPT." , MAIN_AI_SYSTEM, 'sound
This is a change from:
ATTENTION: TRACKING TARGETS, SPOOLING UP POINT DEFENSE. ATTEMPTING TO INTERCEPT.
or
ATTENTION: TRACKING TARGET, SPOOLING UP POINT DEFENSE. ATTEMPTING TO INTERCEPT.

to

ATTENTION: TRACKING INBOUNDS. FIRING AIR DEFENSE. STANDBY FOR INTERCEPT.
or
ATTENTION: TRACKING INBOUND. FIRING AIR DEFENSE. STANDBY FOR INTERCEPT.

Inbounds doesn't make sense. And tracking inbound seems like we're about to receive tracking soon?

2024-12-21 07:39 UTC, Drulikar commented on code/modules/almayer/weaponhits.dm
> +	shipwide_ai_announcement("ATTENTION: [hits] IMPACTED. [missed] MISSED. [intercepted] INTERCEPTED.", MAIN_AI_SYSTEM, 'sound/effects/double_klaxon.ogg')
This is a change from (assuming hits=9, missed=7, intercepted=3):
WARNING, 9 HIT SHIP HULL, 7 MISSED AND 3 INTERCEPTED!
to
ATTENTION: 9 IMPACTED. 7 MISSED. 3 INTERCEPTED.

9 what were impacted? Crew?

2024-12-21 07:39 UTC, Drulikar commented on code/modules/almayer/weaponhits.dm
> +	shipwide_ai_announcement("DANGER: HIGH CONFIDENCE KINETIC INBOUND[quantity > 1 ? "S" : ""], INCOMING PROJECTILE[quantity > 1 ? "S" : ""]. BRACE, BRACE, BRACE. [quantity > 1 ? "SALVO SIZE: [quantity]
Again inbounds is really weird. You probably just want to delete the pluralization of INBOUND.

2024-12-21 07:39 UTC, Drulikar commented on code/modules/almayer/weaponhits.dm
> +	shipwide_ai_announcement("DANGER: HIGH CONFIDENCE MISSILE INBOUND[quantity > 1 ? "S" : ""]. BRACE, BRACE, BRACE. [quantity > 1 ? "SALVO SIZE: [quantity]," : ""] ESTIMATED TIME: [hit_eta] SECONDS." ,
Again inbounds is really weird. You probably just want to delete the pluralization of INBOUND.

2024-12-26 08:14 UTC, KoishiVibe commented on code/modules/almayer/weaponhits.dm
> +	shipwide_ai_announcement("ATTENTION: [hits] IMPACTED. [missed] MISSED. [intercepted] INTERCEPTED.", MAIN_AI_SYSTEM, 'sound/effects/double_klaxon.ogg')
in context this is always going to follow up the weapon so it doesnt really matter

2024-12-26 21:14 UTC, KoishiVibe commented on code/modules/admin/verbs/adminpanelweapons.dm
> +		addtimer(CALLBACK(GLOBAL_PROC, GLOBAL_PROC_REF(shipwide_ai_announcement), "ATTENTION: TRACKING INBOUND[quantity > 1 ? "S" : ""]. FIRING AIR DEFENSE. STANDBY FOR INTERCEPT." , MAIN_AI_SYSTEM, 'sound
ill change this to tracking inbound hostile(s) though.

2025-01-19 22:55 UTC, Drulikar commented on code/modules/almayer/weaponhits.dm
> +	shipwide_ai_announcement("DANGER: HIGH CONFIDENCE KINETIC INBOUND[quantity > 1 ? "S" : ""], INCOMING PROJECTILE[quantity > 1 ? "S" : ""]. BRACE, BRACE, BRACE. [quantity > 1 ? "SALVO SIZE: [quantity]
Still not addressed.

2025-01-19 22:55 UTC, Drulikar commented on code/modules/almayer/weaponhits.dm
> +	shipwide_ai_announcement("DANGER: HIGH CONFIDENCE MISSILE INBOUND[quantity > 1 ? "S" : ""]. BRACE, BRACE, BRACE. [quantity > 1 ? "SALVO SIZE: [quantity]," : ""] ESTIMATED TIME: [hit_eta] SECONDS." ,
Still not addressed.

2025-02-03 01:15 UTC, closed without merging